
moot.language = {

  // the language code
  // Translated to Arabic by Omar Bani Al-Marjeh
  $code: 'ar',


  /* New stuff */
  no_notify: 'Disable all email notifications',
  watchall: 'Watch for all new threads',
  move: 'Move thread',
  moved: 'Thread moved',
  custom_path1: 'Custom path',
  custom_path: 'Enter custom path',
  invalid_path: 'Invalid custom path',
  from: 'From',
  to: 'To',
  show_preview: 'Show preview',

  retire: 'Retire',
  retire_title: 'Retire thread',
  retire_desc: 'Retired threads no longer get bumped to top in the feeds they appear in.',
  retired_desc: 'This thread is retired. New replies no longer bump it to the top of the feed.',
  is_retired: 'This thread has been retired',

  unretire: 'Unretire',
  unretire_title: 'Unretire thread',
  unretire_desc: 'This thread will be bumped to top in the feeds they appear in.',
  quote_help1: 'Select',
  quote_help2: 'to quote or share',

  trial_left: 'left of free trial.',
  after_trial: 'After the trial ends you can continue using Muut with the',
  free_plan: 'Free plan',
  reward: 'Referral reward',
  off33: 'Upgrade now and get 33% off all our paid plans!',
  spread: 'Spread the word!',
  invite: 'Invite a friend to start a Muut community and you’ll both get rewarded!',
  start_now: 'Start your own community now – it\'s free!',
  start_btn: 'Create',
  reserve: 'Reserve your forum name',
  free_acc: 'Free account',
  no_dialog: 'and remove this dialogue',
  click_change: 'Click to change',

  moderator: 'Moderator',
  mkadmin: 'Make administrator',
  mkmod: 'Make moderator',
  upgrade_mod: 'to make this user a moderator',
  upgrade_admin: 'to make this user administrator or moderator',

  my_profile: 'My profile',
  post_in: 'Post in',
  address_now: 'Thank you! Your email address has been confirmed.',
  open_pw: 'Please hit the button below to open a password change dialog',
  non_anon: 'You need to be logged in to perform this action',

  plan: 'Plan',
  trial: 'Start free trial',

  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spam?",

  channels: 'Channels',
  ch_name: 'Channel name',
  ban:  'Ban user',
  banned:  'Banned',
  ban_acc: 'Banned account',
  ban_msg: 'You are temporarily banned from posting on this forum.',
  days:  'Days',
  forever: 'Forever',
  slogan:  'Free forums and commenting by Muut',

  add: '+ Add',
  addons: 'Add-ons',
  myaccount: "Account",
  untitled: "Untitled",
  design: "Design",
  no_title: "Title must be given",
  designer: "Designer",
  developer: "Developer",



  img_needed: "Please upload an image file",
  max: 'Maximum image size is 4Mb',
  yes: 'Yes',
  upload: 'Upload images',
  show: 'show',
  hide: 'hide',
  invisible: 'Invisible',
  givebody: 'Body cannot be empty.',
  show_old: 'Show oldest replies',
  show_more: 'Show more replies',
  show_new: 'Show newest replies',
  start: 'Start a new topic...',
  error: 'Oops, an error. Please copy the post to clipboard, reload and try again. Sorry – we will fix this!',
  body: 'Body text',
  admin: 'Admin',
  someone: 'Someone',
  writing: 'is writing...',
  manage: 'Manage',
  fullview: 'Full view',
  title: 'Title',
  link: 'link',
  avatar: 'Change avatar',
  upgrade_link: 'Upgrade',
  branding: 'Branding',
  logo: 'Logo',
  css: 'CSS file',
  single: 'single word',
  /* End new stuff */



  username_fail: 'استخدم أحرف صغيرة، أرقام، أو شرطات',
  bold: 'بالخط العريض',
  italics: 'بالخط المائل',
  monospaced: 'أحادي المسافة',
  learn: 'تعرف أكثر...',
  settings: 'إعدادات',

  all: 'جميع المشاركات', // or alternatively: الكل
  anon_1: 'مجهول',
  anon: 'مجهول',
  badforum: 'منتدى غير صالح',
  c_acc1: 'إن حسابك الآن يعمل على جميع المواقع التي تستخدم Muut',
  c_acc: 'تم تأكيد الحساب',
  c_email: 'تم تحديث عنوان البريد الإلكتروني',
  cancel: 'إلغاء',
  change: 'تغيير',

  changepw: 'تغيير كلمة المرور',
  close: 'إغلاق',
  collapse: 'طي الكل',
  comm_count_1: 'تعليق',
  comm_count_n: 'تعليقات',
  comment1: 'كن أول من يعلق...',
  comment: 'تعليق...',
  edit: 'تحرير',
  email: 'البريد الإلكتروني',
  email_taken: 'هذا البريد مستخدم بالفعل',
  emailtip: 'لن يتم مشاركة بريدك مع أي جهة',
  enter: 'ctrl + enter',
  expired1: 'لقد أرسلنا لك واحدة جديدة، يرجى التحقق من بريدك الإلكتروني.',
  expired: 'انتهت صلاحية هذا الرابط',

  feed: 'ما يتعلق بي', // alternatives: تغذيتي الخاصة, مواضيع مشترك بها


  help2: 'المشاركة',
  help3: 'النص المقتبس',
  help4: 'السطر الثاني',
  help5: 'الرموز البرمجية',
  help6: 'كود برمجي بلغة HTML',
  in_forum: '',
  invalid: 'قيمة غير صالحة',
  join: 'انضم إلى Muut',
  later: 'لاحقًا...',
  less: 'أقل',
  like: 'أعجبني',
  likepost: 'أعجب بهذا المنشور',
  loading: 'جاري التحميل...',
  login: 'تسجيل الدخول',
  login1: 'قم بتسجيل الدخول أولًا',
  login_and: "تسجيل الدخول و",

  login_or: 'أو',

  logout: 'تسجيل الخروج',
  mark: 'البريد المزعج أو هجمات السبام',
  mean: 'هل تقصد',
  name: 'الاسم الظاهر',
  nametip: 'اسمك الحقيقي، من أجل أن يتعرف المستخدمين عليك',
  newpass: 'كلمة مرور جديدة',
  noresults: 'لا يوجد نتائج لـ',
  nospam: 'لا وجود للسبام في منتدياتك!',
  notexist: 'غير موجود.',
  ok: 'موافق',
  online: 'موجود',
  post: 'منشور',
  preview: 'المعاينة',
  progress: ['جاري التحميل...', 'قيد العمل...', 'والعمل...', 'إيقاف العمل'],
  reconnect: 'إعادة الاتصال...',
  removepost: 'إزالة هذا المنشور',
  reply: 'الرد...',
  replybtn: 'الرد',
  save: 'حفظ التغييرات',
  saved: 'تم الحفظ',
  search: 'البحث',
  select: 'اختر المنتدى',
  setup: 'البدء بالإعداد',
  showing: 'يم عرض',
  spam: 'سبام',

  step1: 'لقد قمنا بإرسال رسالة تأكيد إلى بريدك الإلكتروني. لن يتم تحديث بريدك قبل إتمام هذه الخطوة!',
  step: 'خطوة أخرى',
  terms: 'أنا أوافق على <a>شروط الخدمة</a>.',
  thanks: 'شكرًا!',
  uname_len: 'أدخل 4 أحرف أو أكثر',
  uname_taken: 'هذا الاسم مستخدم بالفعل!',
  unametip: 'لا يمكن تغييره بعد الآن',
  undo: 'تراجع',
  unlike: 'إلغاء الإعجاب',
  unspam: 'غير مزعج',
  unver1: 'لم يتم التحقق من الحساب',
  unver2: 'يرجى الاطلاع على بريدك الإلكتروني من أجل تفعيل الحساب. يمكن لكل من فعل حسابه تلقي التنبيهات عبر بريده الإلكتروني.',
  unver3: 'أرسل لي رمز تحقق جديد',
  unver4: "تم الإرسال. يرجى مراجعة صندوق الوارد داخل بريدك الإلكتروني.",
  unver: 'لم يتم التحقق',
  unwall: 'عدم مشاهدة الكل',
  unwatch: 'عدم المشاهدة',
  upgrade2: 'إن Muut يستخدم WebSockets أو CORS لاتمام الاتصال عبر النطاق. جميع المتصفحات الحديثة تعمل باستثناء Opera 11 و IE7.',
  upgrade: 'الرجاء تحديث المتصفح الخاص بك',
  username_taken: 'اسم المستخدم هذا محجوز',
  watch: 'شاهد هذه الـ Muut',
  welcome1: 'الرجاء التحقق من بريدك الإلكتروني من أجل متابعة التسجيل. إذا لم يصلك البريد في غضون الدقيقة أو الدقيقتين، قم بالتحقق من وجوده في صندوق البريد المزعج.',
  welcome2: 'الرجاء اختيار اسم الـ Muut',
  welcome: 'أهلًا بك في Muut',
  you: 'أنت',

  // times
  months: "يناير, فبراير, مارس  ,أبريل, مايو , يونيو, يوليو , أغسطس, سبتمبر, أكتوبر, نوفمبر, ديسمبر", //RTL months order
  min: 'دقيقة',
  hour: 'ساعة',
  day: 'يوم',
  week: 'أسبوع'

}
