moot.language = {

   // the language code
   $code: 'bg',


   /* New stuff */
   untitled: "Untitled",
   design: "Design",
   no_title: "Title must be given",
   designer: "Designer",
   developer: "Developer",

   no_index: 'Disable indexing under moot.it',
   mkpriv: 'Make this forum private',
   sign: 'This forum must be <a>signed</a> first.',

   s3: 'Custom S3 bucket',
   s3_tip: 'Allows custom domain for search engines and a backup storage.',
   s3_tip2: 'Add full access permissions for <em>moot-aws@moot.it</em>',
   s3_no_access: "moot-aws@moot.it cannot access this bucket",
   s3_missing: "This bucket does not exist",

   img_needed: "Please upload an image file",
   max: 'Maximum image size is 4Mb',
   yes: 'Yes',
   upload: 'Upload images',
   show: 'show',
   hide: 'hide',
   invisible: 'Invisible',
   givebody: 'Body cannot be empty.',
   show_old: 'Show oldest replies',
   show_more: 'Show more replies',
   show_new: 'Show newest replies',
   start: 'Start a new topic...',
   monospaced: 'monospaced',
   ga: 'Google Analytics Id',
   error: 'Oops, an error. Please copy the post to clipboard, reload and try again. Sorry – we will fix this!',
   body: 'Body text',
   admin: 'Admin',
   someone: 'Someone',
   writing: 'is writing...',
   basic: 'Basic (free)',
   subs: 'Subscriptions',
   manage: 'Manage',
   fullview: 'Full view',
   title: 'Title',
   link: 'link',
   avatar: 'Change avatar',
   seo_update: 'The SEO pages will be updated within the hour',
   upgrade_link: 'Upgrade',
   branding: 'Branding',
   logo: 'Logo',
   bgcolor: 'Background color',
   brand_name: 'Brand name',
   css: 'CSS file',
   mootbrand: 'Use Moot branding',
   sso: 'Single Sign-On',
   apikey: 'API key',
   apisecret: 'Secret key',
   single: 'single word',
   /* End new stuff */


   username_fail: 'Използвай букви, цифри или чертички',
   bold: 'удебелен шрифт',
   italics: 'наклонен шрифт',
   domain: 'URL Адрес на форума',
   domaintip: 'Пълен адрес на форумите, където потребителите се препращат от резултати от търсенето',
   learn: 'Разбери още...',
   admins: 'Администратори',
   adminstip: 'Едно потребителско име на ред',
   settings: 'Настройки',
   all: 'Всички Статии', // or alternatively: All

   anon_1: 'анонимен',    // singular
   anon: 'анонимни',      // plural

   badforum: 'Невалиден Форум',
   c_acc1: 'Твоят акаунт вече работи на всички сайтове, ползващи Moot',
   c_acc: 'Потвърден акаунт',
   c_email: 'Електронната поща е актуализирана',
   cancel: 'Отказ',
   change: 'Промяна',
   changepw: 'Смяна на парола',
   close: 'Затвори',
   collapse: 'Свий всички',
   comm_count_1: 'коментар',   // singular: "1 comment"
   comm_count_n: 'коментара',  // plural: "3 comments"
   comment1: 'Бъди първият написал коментар...',
   comment: 'Коментирай...',
   edit: 'промяна',
   email: 'Е-Поща',
   email_taken: 'Този адрес вече е зает',
   emailtip: 'Твоя email никога няма да бъде споделян',
   enter: 'ctrl + enter',
   expired1: 'Провери твоя email!', // http://d.pr/i/1OEV
   expired: 'Тази връзка е изтекла',

   feed: 'Новини', // alternatives: My own, personal

   forumname: 'Име на форума',
   forums: 'Форуми',

   help2: 'статия',
   help3: 'цитиран',
   help5: 'код, езика е открит',
   help6: 'HTML код',
   in_forum: 'в',
   invalid: 'Невалидна стойност',
   join: 'Присъедини се към Moot',
   later: 'По-късно...',
   less: 'по-малко',
   like: 'Харесай',
   likepost: 'Харесай тази статия',
   loading: 'Зареждане...',
   login: 'Влез',
   login1: 'Първо влез',
   login_and: "Влез и",

   logout: 'Излез',
   mark: 'Обидно или спам',
   mean: 'Имаш на предвид',
   name: 'Име за показване',
   nametip: 'Твоето истинско име, за да могат хората да те разпознаят',
   newcat: 'Нова категория',
   newpass: 'Нова парола',
   noresults: 'Няма резултати за',
   nospam: 'В този форум няма спам!',
   notexist: 'не съществува.',
   notify: 'Извести ме при нови обновления',
   ok: 'ОК',
   online: 'На линия',
   post: 'Статия',
   preview: 'Преглед',
   progress: ['зареждане...', 'още работя...', 'и работя...', 'предавам се...'],
   reconnect: 'Свързване отново...',
   removecat: 'Премахни. Статиите не бяха премахнати',
   removepost: 'Премахни тази статия',
   reply: 'Отговори...',
   replybtn: 'Отговор',
   save: 'Запази промените',
   saved: 'запазено',
   search: 'Търси',
   select: 'Избери форум',
   setup: 'Настрой сега',
   showing: 'Показване',
   slogan: 'Различните Форуми и Коментари',
   spam: 'Спам',
   step1: 'Изпратихме ти email за потвърждение. Твоят email няма да бъде обновен докато не изпълниш тази стъпка!',
   step: 'Още една стъпка',
   terms: 'Съгласен съм с<a>условията на услугата</a>.',
   thanks: 'Благодаря!',
   uname_len: 'Въведи 6 или повече символа',
   uname_taken: 'Това потребителско име е заето!',
   unametip: 'Това не може да бъде променяно по-късно',
   undo: 'Отмени',
   unlike: 'Вече не харесвам',
   unspam: 'Не е спам',
   unver1: 'Непотвърден профил',
   unver2: 'Моля провери твоя email, за да потвърдиш профила си. Потребителите с потвърдени профили могат да гледат разговорите и да получават известия по email. <a>Изпрати нов код за потвърждение...</a>',
   unver3: '<a>Изпрати нов</a> код за потвърждение на:',
   unver4: "Изпратено. Провери входящата кутия на email-а си.",
   unver: 'Непотвърдено',
   unwall: 'Спри да следиш всички',
   unwatch: 'Спри да следиш',
   upgrade2: 'Moot ползва WebSockets или CORS за комуникация между домейни. Всеки съвременен browser освен Opera 11 и IE7 ще работи.',
   upgrade: 'Обнови твоя WEB browser',
   username_taken: 'Това потребителско име е заето',
   watch: 'Следи за нови отговори',
   welcome1: 'Провери твоя email, за да довършиш регистрацията! Ако не получиш email до 1-2 минути, провери спам папката на твоя email.',
   welcome2: 'Моля посочи Moot потребителско име',
   welcome: 'Добре Дошъл в Moot',
   you: 'Ти',

   // times
   now: 'в момента',
   months: "Ян,Фев,Март,Апр,Май,Юни,Юли,Авг,Септ,Окт,Ное,Дек",
   min: 'м',
   hour: 'ч',
   day: 'д',
   week: 'с'

}
