var language = {

  // the language code
  $code: 'bg',


  /* New stuff */
  no_notify: 'Disable all email notifications',
  watchall: 'Watch for all new threads',
  move: 'Move thread',
  moved: 'Thread moved',
  custom_path1: 'Custom path',
  custom_path: 'Enter custom path',
  invalid_path: 'Invalid custom path',
  from: 'From',
  to: 'To',
  show_preview: 'Show preview',

  retire: 'Retire',
  retire_title: 'Retire thread',
  retire_desc: 'Retired threads no longer get bumped to top in the feeds they appear in.',
  retired_desc: 'This thread is retired. New replies no longer bump it to the top of the feed.',
  is_retired: 'This thread has been retired',

  unretire: 'Unretire',
  unretire_title: 'Unretire thread',
  unretire_desc: 'This thread will be bumped to top in the feeds they appear in.',
  quote_help1: 'Select',
  quote_help2: 'to quote or share',

  trial_left: 'left of free trial.',
  after_trial: 'After the trial ends you can continue using Muut with the',
  free_plan: 'Free plan',
  reward: 'Referral reward',
  off33: 'Upgrade now and get 33% off all our paid plans!',
  spread: 'Spread the word!',
  invite: 'Invite a friend to start a Muut community and you’ll both get rewarded!',
  start_now: 'Start your own community now – it\'s free!',
  start_btn: 'Create',
  reserve: 'Reserve your forum name',
  free_acc: 'Free account',
  no_dialog: 'and remove this dialogue',
  click_change: 'Click to change',

  moderator: 'Moderator',
  mkadmin: 'Make administrator',
  mkmod: 'Make moderator',
  upgrade_mod: 'to make this user a moderator',
  upgrade_admin: 'to make this user administrator or moderator',

  my_profile: 'My profile',
  post_in: 'Post in',
  address_now: 'Thank you! Your email address has been confirmed.',
  open_pw: 'Please hit the button below to open a password change dialog',
  non_anon: 'You need to be logged in to perform this action',

  plan: 'Plan',
  trial: 'Start free trial',

  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spam?",

  channels: 'Channels',
  ch_name: 'Channel name',
  ban:  'Ban user',
  banned:  'Banned',
  ban_acc: 'Banned account',
  ban_msg: 'You are temporarily banned from posting on this forum.',
  days:  'Days',
  forever: 'Forever',
  slogan:  'Free forums and commenting by Muut',

  add: '+ Add',
  addons: 'Add-ons',
  myaccount: "Account",
  untitled: "Untitled",
  design: "Design",
  no_title: "Title must be given",
  designer: "Designer",
  developer: "Developer",



  img_needed: "Please upload an image file",
  max: 'Maximum image size is 4Mb',
  yes: 'Yes',
  upload: 'Upload images',
  show: 'show',
  hide: 'hide',
  invisible: 'Invisible',
  givebody: 'Body cannot be empty.',
  show_old: 'Show oldest replies',
  show_more: 'Show more replies',
  show_new: 'Show newest replies',
  start: 'Start a new topic...',
  monospaced: 'monospaced',
  error: 'Oops, an error. Please copy the post to clipboard, reload and try again. Sorry – we will fix this!',
  body: 'Body text',
  admin: 'Admin',
  someone: 'Someone',
  writing: 'is writing...',
  manage: 'Manage',
  fullview: 'Full view',
  title: 'Title',
  link: 'link',
  avatar: 'Change avatar',
  upgrade_link: 'Upgrade',
  branding: 'Branding',
  logo: 'Logo',
  css: 'CSS file',
  single: 'single word',
  /* End new stuff */


  username_fail: 'Използвай букви, цифри или чертички',
  bold: 'удебелен шрифт',
  italics: 'наклонен шрифт',
  learn: 'Разбери още...',
  settings: 'Настройки',
  all: 'Всички Статии', // or alternatively: All

  anon_1: 'анонимен',  // singular
  anon: 'анонимни',  // plural

  badforum: 'Невалиден Форум',
  c_acc1: 'Твоят акаунт вече работи на всички сайтове, ползващи Muut',
  c_acc: 'Потвърден акаунт',
  c_email: 'Електронната поща е актуализирана',
  cancel: 'Отказ',
  change: 'Промяна',
  changepw: 'Смяна на парола',
  close: 'Затвори',
  collapse: 'Свий всички',
  comm_count_1: 'коментар',  // singular: "1 comment"
  comm_count_n: 'коментара',  // plural: "3 comments"
  comment1: 'Бъди първият написал коментар...',
  comment: 'Коментирай...',
  edit: 'промяна',
  email: 'Е-Поща',
  email_taken: 'Този адрес вече е зает',
  emailtip: 'Твоя email никога няма да бъде споделян',
  enter: 'ctrl + enter',
  expired1: 'Провери твоя email!', // http://d.pr/i/1OEV
  expired: 'Тази връзка е изтекла',

  feed: 'Новини', // alternatives: My own, personal


  help2: 'статия',
  help3: 'цитиран',
  help5: 'код, езика е открит',
  help6: 'HTML код',
  in_forum: 'в',
  invalid: 'Невалидна стойност',
  join: 'Присъедини се към Muut',
  later: 'По-късно...',
  less: 'по-малко',
  like: 'Харесай',
  likepost: 'Харесай тази статия',
  loading: 'Зареждане...',
  login: 'Влез',
  login1: 'Първо влез',
  login_and: "Влез и",

  logout: 'Излез',
  mark: 'Обидно или спам',
  mean: 'Имаш на предвид',
  name: 'Име за показване',
  nametip: 'Твоето истинско име, за да могат хората да те разпознаят',
  newpass: 'Нова парола',
  noresults: 'Няма резултати за',
  nospam: 'В този форум няма спам!',
  notexist: 'не съществува.',
  ok: 'ОК',
  online: 'На линия',
  post: 'Статия',
  preview: 'Преглед',
  progress: ['зареждане...', 'още работя...', 'и работя...', 'предавам се...'],
  reconnect: 'Свързване отново...',
  removepost: 'Премахни тази статия',
  reply: 'Отговори...',
  replybtn: 'Отговор',
  save: 'Запази промените',
  saved: 'запазено',
  search: 'Търси',
  select: 'Избери форум',
  setup: 'Настрой сега',
  showing: 'Показване',
  spam: 'Спам',
  step1: 'Изпратихме ти email за потвърждение. Твоят email няма да бъде обновен докато не изпълниш тази стъпка!',
  step: 'Още една стъпка',
  terms: 'Съгласен съм с<a>условията на услугата</a>.',
  thanks: 'Благодаря!',
  uname_len: 'Въведи 4 или повече символа',
  uname_taken: 'Това потребителско име е заето!',
  unametip: 'Това не може да бъде променяно по-късно',
  undo: 'Отмени',
  unlike: 'Вече не харесвам',
  unspam: 'Не е спам',
  unver1: 'Непотвърден профил',
  unver2: 'Моля провери твоя email, за да потвърдиш профила си.',
  unver3: 'Изпрати нов код за потвърждение',
  unver4: "Изпратено. Провери входящата кутия на email-а си.",
  unver: 'Непотвърдено',
  unwall: 'Спри да следиш всички',
  unwatch: 'Спри да следиш',
  upgrade2: 'Muut ползва WebSockets или CORS за комуникация между домейни. Всеки съвременен browser освен Opera 11 и IE7 ще работи.',
  upgrade: 'Обнови твоя WEB browser',
  username_taken: 'Това потребителско име е заето',
  watch: 'Следи за нови отговори',
  welcome1: 'Провери твоя email, за да довършиш регистрацията! Ако не получиш email до 1-2 минути, провери спам папката на твоя email.',
  welcome2: 'Моля посочи Muut потребителско име',
  welcome: 'Добре Дошъл в Muut',
  you: 'Ти',

  // times
  now: 'в момента',
  months: "Ян,Фев,Март,Апр,Май,Юни,Юли,Авг,Септ,Окт,Ное,Дек",
  min: 'м',
  hour: 'ч',
  day: 'д',
  week: 'с'

}

if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
  module.exports = language;
} else {
  window.moot.language = language;
}
