/*

   This file is deprecated, please use zh.js instead

*/
moot.language = {


   // the language code
   $code: 'ch',

   /* New stuff */
   img_needed: "Please upload an image file",

   ban:     'Ban user',
   banned:  'Banned',
   ban_usr: 'Banned users',
   ban_acc: 'Banned account',
   ban_msg: 'You are temporarily banned from posting on this forum.',
   days:    'Days',
   forever: 'Forever',
   slogan:  'Free forums and commenting by Muut',

   add: '+ Add',
   addons: 'Add-ons',
   myaccount: "My account",
   untitled: "Untitled",
   design: "Design",
   no_title: "主题不能为空哦",
   designer: "论坛设计师",
   developer: "论坛开发者",

   no_index: '不排序',
   mkpriv: '私有化论坛',
   sign: '这个论坛需要先<a>signed</a>.',

   s3: '订制的S3 bucket',
   s3_tip: '搜索引擎可以通过你的域名找到的论坛内容。',
   s3_tip2: '增加完整权限的 <em>moot-aws@moot.it</em>',
   s3_no_access: "moot-aws@moot.无法访问bucket",
   s3_missing: "bucket不存在",

   max: '图片最大尺寸4兆',
   yes: '确定',
   upload: '上传图片',
   show: '显示',
   hide: '隐藏',
   invisible: '不可见',
   givebody: '内容不得为空.',
   show_old: '显示最早的回复',
   show_more: '显示更多的回复',
   show_new: '显示最新的回复',
   start: '发起新贴...',
   single: '标准',
   bold: '粗体',
   italics: '斜体',
   monospaced: '单间隔',
   domain: '论坛域名',
   domaintip: '用户通过搜索得到的论坛域名',
   learn: '了解更多...',
   ga: '谷歌分析 Id',
   admins: '管理员',
   adminstip: '一个用户名一行',
   settings: '设置',
   error: '额，有错误，请复制你的帖子内容到剪贴板，刷新页面后粘帖再试!抱歉，我们会尽快修复这个问题',
   body: '内容',
   admin: '管理员',
   someone: '有人',
   writing: '正在输入...',
   basic: '基础版 (免费)',
   subs: '付费',
   manage: '管理',
   fullview: '完整视图',
   title: '主题',
   link: '链接',
   avatar: '头像',
   seo_update: '搜索引擎优化页面会在一个小时内更新',
   upgrade_link: '升级链接',
   branding: '品牌',
   logo: '标志',
   bgcolor: '背景颜色',
   brand_name: '品牌名称',
   css: 'CSS 文件',
   mootbrand: '使用Muut品牌',
   sso: 'Single Sign-On',
   apikey: 'API key',
   apisecret: 'Secret key',



   /* End new stuff */


   username_fail: '使用小写字母、数字或横杠',
   all: '所有帖子', // or alternatively: All
   anon_1: '匿名用户',
   anon: '匿名用户',
   badforum: '非法的论坛',
   c_acc1: '你的账户已经可以在所有使用Muut的网站上登录啦！',
   c_acc: '账户已确认',
   c_email: '邮件地址已升级',
   cancel: '取消',
   change: '更改',

   changepw: '更改密码',
   close: '关闭',
   collapse: '全部折叠',
   comm_count_1: '评论',
   comm_count_n: '所有评论',
   comment1: '强沙发吧！',
   comment: '评论',
   edit: '编辑',
   email: '邮箱',
   email_taken: '这个邮箱已经被注册过了',
   emailtip: '我们确保您的邮箱不会被公开。',
   enter: '按下ctrl + enter发送',
   expired1: '我们已经发送来了一个新的链接，请检查您的邮箱。',
   expired: '这个链接已经过期了',

   feed: '我的帖子', // alternatives: My own, personal

   forumname: '论坛的名字',
   forums: '论坛',

   help2: '发布帖子',
   help3: '引用文字',
   help5: '代码',
   help6: 'html 代码',
   in_forum: '',
   invalid: '无效值',
   join: '加入 Muut',
   later: '稍后……',
   less: '收！',
   like: '喜欢',
   likepost: '喜欢这个帖子',
   loading: '正在载入……',
   login: '登录',
   login1: '请先登录',
   login_and: "登录后",

   logout: '注销',
   mark: '不合适或垃圾内容',
   mean: '你的意思是',
   name: '名字',
   nametip: '建议在这里填入朋友们熟悉的名字, 以便让大家都可以认出你',
   newcat: '增加新板块',
   newpass: '新密码',
   noresults: '没有搜索到',
   nospam: '你的Muut上没有垃圾内容！',
   notexist: '不存在.',
   notify: '有新消息提醒我',
   ok: 'ok',
   online: '在线',
   post: '发布',
   preview: '预览',
   progress: ['载入中……', '仍在载入中……', '依旧在载入中……', '放弃了，5555555'],
   reconnect: '正在重新连接……',
   removecat: '删除。 这个帖子还没有被删除。',
   removepost: '删除这个帖子',
   reply: '回复……',
   replybtn: '回复',
   save: '保存更改',
   saved: '已保存',
   search: '搜索',
   select: '选择板块',
   setup: '设置',
   showing: '演示中',
   spam: '垃圾内容',
   step1: '我们已经向你发送了一封确认邮件. 在你完成这一步之前你的邮箱不会被升级',
   step: '下一步',
   terms: '我同意 <a>服务条款</a>.',
   thanks: '谢谢！',
   uname_len: '请输入6个或更多字符',
   uname_taken: '这个用户名已经被注册过了！',
   unametip: '用户名确认后就不能更改哦！',
   undo: '取消',
   unlike: '不喜欢',
   unspam: '这不是垃圾内容',
   unver1: '未验证用户',
   unver2: '请检查你的邮箱以验证你的账户. 已经验证过的用户可以看到帖子内容并可以在帖子更新时收到邮件提醒. <a>再发送一次验证邮件……</a>',
   unver3: '<a>在发送一封</a> 验证邮件给:',
   unver4: "已发送。请检查你的收件箱。",
   unver: '未验证',
   unwall: '取消关注所有',
   unwatch: '取消关注',
   upgrade2: 'Muut使用WebSockets或CORS（跨域资源共享）来实现跨域通信。 除了Opera 11和IE7，现行的主流浏览器都可以使用。 ',
   upgrade: '请升级您的浏览器。',
   username_taken: '这个用户名已经被注册过了！',
   watch: '关注！',
   welcome1: '请查看您的邮箱以完成注册. 假如您在几分钟内没有收到邮件, 请检查您的垃圾邮件箱。',
   welcome2: '请提供一个Muut用户名',
   welcome: '欢迎来到Muut！',
   you: '你',

   // times

   now: '刚刚',
   months: '1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月',
   min: '分钟',
   hour: '小时',
   day: '天',
   week: '周'


}
