moot.language = {

  // the language code
  $code: 'cz',

  no_notify: 'Vypnout všechy e-mailové upozornění',
  watchall: 'Sleduj všechny nové diskuze',
  move: 'Přesunout téma',
  moved: 'Téma přesunuto',
  custom_path1: 'Vlastní cesta',
  custom_path: 'Vlož vlastní cestu',
  invalid_path: 'Neplatná vlastní cesta',
  from: 'Od',
  to: 'Komu',
  show_preview: 'Zobrazit náhled',

  retire: 'Označit jako staré',
  retire_title: 'Označit téma jako staré',
  retire_desc: 'Stará témata se již nebudou zobrazovat na začátku své diskuze.',
  retired_desc: 'Toto téma je staré. Nové odpovědi se nepřipínají na začátek diskuze.',
  is_retired: 'Toto téma bylo označeno jako staré.',

  unretire: 'Obnovit',
  unretire_title: 'Obnovit téma',
  unretire_desc: 'Toto téma se bude opět zobrazovat na začátku své diskuze.',
  quote_help1: 'Označit',
  quote_help2: 'citovat nebo sídlet',

  trial_left: 'zůstává ze zkušební verze.',
  after_trial: 'Po skončení zkušební verze můžete pokračovat v používání služby s',
  free_plan: 'Plán zdarma',
  reward: 'Odměna za doporučení',
  off33: 'Upgradujte teď a získejte slevu 33% na placenou verzi!',
  spread: 'Sdílejte to se všemi!',
  invite: 'Pozvi přátele, založte svoji komunitu a nechte se oba odměnit!',
  start_now: 'Založte svoji komunitu - je to zdrama!',
  start_btn: 'Vytvořit',
  reserve: 'Rezervujte si jméno vašeho fóra',
  free_acc: 'Účet zdarma',
  no_dialog: 'a odstraňte tuto hlášku',
  click_change: 'Klikni pro změnu',

  moderator: 'Moderátor',
  mkadmin: 'Určit administrátorem',
  mkmod: 'Určit moderátorem',
  upgrade_mod: 'povýšit tohoto uživatele na moderátora',
  upgrade_admin: 'povýšit tohoto uživatele na admina nebo moderátora',

  my_profile: 'Můj profil',
  post_in: 'Přispět v',
  address_now: 'Děkujeme! Vaše e-mailová adresa byla potvrzena.',
  open_pw: 'Pro otevření formuláře na změnu hesla, stiskněte tlačítko níže',
  non_anon: 'Pro provedení této akce musíte být přihlášeni',

  plan: 'Plán',
  trial: 'Začněte se zkušební verzí',

  is_private: "Tato komunita je soukromá",
  owner_msg: "Vaše zpráva majitelům fóra... (volitelné)",
  req_access: "Vyžádat přístup",
  req_sent: "Žádost o přístup odeslána",
  or_join: "nebo se <a>Registrujte</a> do této komunity.",
  save_with: "Ušetříte 20% z roční ceny",
  rem_post: "Odstranit tento příspěvek?",
  is_spam: "Je tento příspěvek spam?",

  channels: 'Kanály',
  ch_name: 'Název kanálu',
  ban: 'Zablokovat uživatele',
  banned: 'Zablokovaný',
  ban_acc: 'Zablokovaný účet',
  ban_msg: 'Jste dočasně zablokovaný z tohoto fóra.',
  days: 'Dny',
  forever: 'Navždy',
  slogan: 'Fóra a komentáře od Muut',

  add: '+ Přidat',
  addons: 'Rozšíření',
  myaccount: "Účet",
  untitled: "Bez jména",
  design: "Design",
  no_title: "Název je povinný",
  designer: "Designer",
  developer: "Vývojář",


  warning: 'Varování',
  profanity: 'Neuctivé příspěvky jsou na tomto fóru zakázány! Pokud budete pravilda dále porušovat, budete zablokováni.',

  img_needed: "Prosím nahrajte soubor obrázku",
  max: 'Maximální velikost obrázku je 4Mb',
  yes: 'Ano',
  upload: 'Nahrát obrázky',
  show: 'Zobrazit',
  hide: 'Skrýt',
  invisible: 'Neviditelný',
  givebody: 'Tělo zprávy nemůže být prázdné.',
  show_old: 'Nejstarší odpovědi',
  show_more: 'Více odpovědí',
  show_new: 'Nejnovější odpovědi',
  start: 'Založit nové téma...',
  error: 'Oops, chyba. Prosím zkopírujte si příspěvek do schránky a zkuste to znova. Omlouváme se – brzy to vyřešíme!',
  body: 'Tělo textu',
  admin: 'Administrátor',
  someone: 'Někdo',
  title: 'Název',
  writing: 'právě píše...',
  manage: 'Spravovat',
  fullview: 'Celý náhled',
  link: 'odkaz',
  avatar: 'Změnit profilovou fotku',

  upgrade_link: 'Upgradovat',
  branding: 'Značka',
  logo: 'Logo',

  title: 'Název',
  css: 'CSS soubor',

  single: 'jedno slovo',

  username_fail: 'Použijte písmena, čísla nebo pomlčky',
  bold: 'tučně',
  italics: 'kurzíva',
  monospaced: 'neproporcionální písmo',

  settings: 'Nastavení',

  all: 'Všechny příspěvky', // or alternatively: All
  anon_1: 'anonym',  // singular
  anon: 'anonymové',  // plural

  badforum: 'Neplatné fórum',
  c_acc1: 'Váš účet nyní funguje na všech stránkách, které využívají Muut',
  c_acc: 'Účet potvrzen',
  c_email: 'E-mailová adresa aktualizována',
  cancel: 'Zrušit',
  change: 'Změnit',
  changepw: 'Změnit heslo',
  close: 'Zavřít',
  collapse: 'Seskupit',
  comm_count_1: 'komentář',  // singular: "1 comment"
  comm_count_n: 'komentáře',  // plural: "3 comments"
  comment1: 'Přidejte komentář jako první...',
  comment: 'Přidat komentář...',
  edit: 'Upravit',
  email: 'E-mail',
  email_taken: 'Tento e-mail je již používán',
  emailtip: 'Váš e-mail není nikdy veřejný',
  enter: 'ctrl + enter',
  expired1: 'Právě jsme vám poslali nový. Zkontrolujte si e-mail.', // http://d.pr/i/1OEV
  expired: 'Odkaz je neplatný',
  feed: 'Mé diskuze', // alternatives: My own, personal

  help2: 'příspěvek',
  help3: 'citované',
  help5: 'kód, odhadnutý jazyk',
  help6: 'HTML kód',
  in_forum: 'v',
  invalid: 'Neplatná hodnota',
  join: 'Přidejte se k Muut',
  later: 'Později...',
  less: 'méně',
  like: 'To se mi líbí',
  likepost: 'Příspěvek se mi líbí',
  loading: 'Nahrávání...',
  login: 'Přihlásit se',
  login1: 'Napřed se přihlašte',
  login_and: "Přihlásit a",

  logout: 'Odhlásit se',
  mark: 'Útočný nebo spam',
  mean: 'Měli jste na mysli',
  name: 'Veřejné jméno',
  nametip: 'Vaše skutečné jméno, aby vás lidé poznali',

  newpass: 'Nové heslo',
  noresults: 'Žádné výsledky pro',
  nospam: 'Žádný spam na našem fóru!',
  notexist: 'neexistuje.',
  ok: 'ok',
  online: 'Online',
  post: 'Přidat příspěvek',
  preview: 'Náhled',
  progress: ['načítání...', 'stále pracujeme...', 'a pracujeme...', 'vzdáváme to'],
  reconnect: 'Připojování...',
  removepost: 'Odstranit',
  reply: 'Odpovědět...',
  replybtn: 'Odpovědět',

  saved: 'uložené',
  search: 'Vyhledat',
  select: 'Zvolit kanál',
  setup: 'Teď nastavit',
  showing: 'Zobrazuje se',

  spam: 'Spam',
  step1: 'Poslali jsme vám potvrzující e-mail. Váš e-mail se neaktualizuje dokud nedokončíte tento krok!',
  step: 'Už jen jeden krok',
  terms: 'Souhlasím s <a>podmínkami služby</a>.',
  thanks: 'Děkujeme!',
  uname_len: 'Vložte 4 znaky nebo více',
  uname_taken: 'Toto jméno je již obsazené!',
  unametip: 'Toto už nemůžete znovu změnit.',
  undo: 'Zpět',
  unlike: 'Už se mi nelíbí',
  unspam: 'Není spam',
  unver1: 'Neověřený účet',
  unver2: 'Prosím zkontrolujte si e-mail a potvrďte svůj účet.',
  unver3: 'Poslat potvrzující e-mail znovu',
  unver4: "Odesláno. Zkontrolujte si e-mail.",
  unver: 'Neověřeno',
  unwall: 'přestat sledovat vše',
  unwatch: 'Přestat sledovat',
  upgrade2: 'Muut používá WebSockety nebo CORS pro mezidoménovou komunikaci. Všechny moderní prohlížeče jsou kompatibilní.',
  upgrade: 'Prosím aktualizujte si svůj prohlížeč',
  username_taken: 'Toto uživatelské jméno je obsazené',
  watch: 'Sledujte nové odpovědi',
  welcome1: 'Pro dokončení registrace si zkontrolujte e-mail. Pokud vám e-mail nepříjde do dvou minut, zkontrolujte složku SPAM.',
  welcome2: 'Prosím zvolte si Muut jméno',
  welcome: 'Vítejte v Muut',
  you: 'Vy',

  // times
  now: 'právě teď',
  months: "Led,Úno,Bře,Dub,Kvě,Čer,Červ,Srp,Zář,Říj,Lis,Pro",
  min: 'm',
  hour: 'h',
  day: 'd',
  week: 't'

}
