moot.language = {

  // the language code
  $code: 'en',

  my_profile: 'My profile',
  post_in: 'Post in',
  address_now: 'Thank you! Your email address has been confirmed.',
  open_pw: 'Please hit the button below to open a password change dialog',
  non_anon: 'You need to be logged in to perform this action',

  plan: 'Plan',
  trial: 'Start free trial',

  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spam?",

  channels: 'Channels',
  ch_name: 'Channel name',
  ban: 'Ban user',
  banned: 'Banned',
  ban_acc: 'Banned account',
  ban_msg: 'You are temporarily banned from posting on this forum.',
  days: 'Days',
  forever: 'Forever',
  slogan: 'Free forums and commenting by Muut',

  add: '+ Add',
  addons: 'Add-ons',
  myaccount: "My account",
  untitled: "Untitled",
  design: "Design",
  no_title: "Title must be given",
  designer: "Designer",
  developer: "Developer",


  warning: 'Warning',
  profanity: 'Profanity is not allowed on this forum. Continued abuse of this policy will result in being banned.',

  img_needed: "Please upload an image file",
  max: 'Maximum image size is 4Mb',
  yes: 'Yes',
  upload: 'Upload images',
  show: 'show',
  hide: 'hide',
  invisible: 'Invisible',
  givebody: 'Body cannot be empty.',
  show_old: 'Show oldest replies',
  show_more: 'Show more replies',
  show_new: 'Show newest replies',
  start: 'Start a new topic...',
  error: 'Oops, an error. Please copy the post to clipboard, reload and try again. Sorry – we will fix this!',
  body: 'Body text',
  admin: 'Admin',
  someone: 'Someone',
  title: 'Title',
  writing: 'is writing...',
  manage: 'Manage',
  fullview: 'Full view',
  link: 'link',
  avatar: 'Change avatar',

  upgrade_link: 'Upgrade',
  branding: 'Branding',
  logo: 'Logo',

  title: 'Title',
  css: 'CSS file',

  single: 'single word',

  username_fail: 'Use letters, numbers or dashes',
  bold: 'bold',
  italics: 'italics',
  monospaced: 'monospaced',

  settings: 'Settings',

  all: 'All posts', // or alternatively: All
  anon_1: 'anonymous',  // singular
  anon: 'anonymous',  // plural

  badforum: 'Invalid forum',
  c_acc1: 'Your account now works on all sites using Muut',
  c_acc: 'Account confirmed',
  c_email: 'Email address updated',
  cancel: 'Cancel',
  change: 'Change',
  changepw: 'Change password',
  close: 'Close',
  collapse: 'Collapse all',
  comm_count_1: 'comment',  // singular: "1 comment"
  comm_count_n: 'comments',  // plural: "3 comments"
  comment1: 'Be the first to comment...',
  comment: 'Comment...',
  edit: 'Edit',
  email: 'Email',
  email_taken: 'This email is taken',
  emailtip: 'Your email is never shared',
  enter: 'ctrl + enter',
  expired1: 'We just sent you a new one. Please check your email.', // http://d.pr/i/1OEV
  expired: 'This link has expired',
  feed: 'My feed', // alternatives: My own, personal

  help2: 'post',
  help3: 'quoted',
  help5: 'code, language guessed',
  help6: 'HTML code',
  in_forum: 'in',
  invalid: 'Invalid value',
  join: 'Join Muut',
  later: 'Later...',
  less: 'less',
  like: 'Like',
  likepost: 'Like this post',
  loading: 'Loading...',
  login: 'Log in',
  login1: 'Log in first',
  login_and: "Login and",

  logout: 'Log out',
  mark: 'Offensive or spam',
  mean: 'Did you mean',
  name: 'Display name',
  nametip: 'Your real name, so people will recognize you',

  newpass: 'New password',
  noresults: 'No results for',
  nospam: 'No spam on your forum!',
  notexist: 'does not exist.',
  ok: 'ok',
  online: 'Online',
  post: 'Post',
  preview: 'Preview',
  progress: ['loading...', 'still working...', 'and working...', 'giving up'],
  reconnect: 'Reconnecting...',
  removepost: 'Remove',
  reply: 'Reply...',
  replybtn: 'Reply',

  saved: 'saved',
  search: 'Search',
  select: 'Select channel',
  setup: 'Setup now',
  showing: 'Showing',

  spam: 'Spam',
  step1: 'We have sent you a confirmation email. Your email is not updated before you complete this step!',
  step: 'One more step',
  terms: 'I agree to the <a>terms of service</a>.',
  thanks: 'Thanks!',
  uname_len: 'Type 4 characters or more',
  uname_taken: 'This username is taken!',
  unametip: 'This cannot be changed later',
  undo: 'Undo',
  unlike: 'Unlike',
  unspam: 'Not spam',
  unver1: 'Unverified account',
  unver2: 'Please check your email to verify your account.',
  unver3: 'Resend verification link',
  unver4: "Sent. Please check your inbox.",
  unver: 'Unverified',
  unwall: 'unwatch all',
  unwatch: 'Unwatch',
  upgrade2: 'Muut uses WebSockets or CORS for cross domain communication. All modern browsers above Opera 11 and IE7 work.',
  upgrade: 'Please upgrade your browser',
  username_taken: 'This username is taken',
  watch: 'Watch for new replies',
  welcome1: 'Please check your email to complete the registration. If you dont receive email within a minute or two, check your spam folder.',
  welcome2: 'Please provide a Muut username',
  welcome: 'Welcome to Muut',
  you: 'You',

  // times
  now: 'just now',
  months: "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
  min: 'm',
  hour: 'h',
  day: 'd',
  week: 'w'

}
