moot.language = {

  // the language code
  $code: 'en',

  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spa?",

  channels: 'Kanallar',
  ch_name: 'Channel name',
  ban: 'Ban user',
  banned: 'Banned',
  ban_acc: 'Banned account',
  ban_msg: 'You are temporarily banned from posting on this forum.',
  days: 'Days',
  forever: 'Forever',
  slogan: 'Free forums and commenting by Muut',

  add: '+ Add',
  addons: 'Add-ons',
  myaccount: "My account",
  untitled: "Untitled",
  design: "Design",
  no_title: "Başlıq verilməlidir",
  designer: "Designer",
  developer: "Developer",


  warning: 'Warning',
  profanity: 'Profanity is not allowed on this forum. Continued abuse of this policy will result in being banned.',

  img_needed: "Please upload an image file",
  max: 'Maximum image size is 4Mb',
  yes: 'Yes',
  upload: 'Upload images',
  show: 'show',
  hide: 'hide',
  invisible: 'Invisible',
  givebody: 'Body cannot be empty.',
  show_old: 'Köhnə cavabları göstər',
  show_more: 'Daha çox cavab göstər',
  show_new: 'Ən yeni cavabları göstər',
  start: 'Yeni mövzu aç...',
  error: 'Oops, an error. Please copy the post to clipboard, reload and try again. Sorry – we will fix this!',
  body: 'Body text',
  admin: 'Admin',
  someone: 'Kimsə',
  title: 'Başlıq',
  writing: 'yazır...',
  basic: 'Basic (free)',
  subs: 'Subscriptions',
  manage: 'Manage',
  fullview: 'Tam görünüş',
  link: 'link',
  avatar: 'Change avatar',

  upgrade_link: 'Upgrade',
  branding: 'Branding',
  logo: 'Logo',

  title: 'Title',
  css: 'CSS file',

  single: 'single word',

  username_fail: 'Use letters, numbers or dashes',
  bold: 'bold',
  italics: 'italics',
  monospaced: 'monospaced',

  settings: 'Settings',

  all: 'Bütün', // or alternatively: All
  anon_1: 'anonim',  // singular
  anon: 'anonim',  // plural

  badforum: 'Invalid forum',
  c_acc1: 'Your account now works on all sites using Muut',
  c_acc: 'Account confirmed',
  c_email: 'Email address updated',
  cancel: 'Ləğv',
  change: 'Ləğv',
  changepw: 'Change password',
  close: 'Close',
  collapse: 'Hamısını yığ',
  comm_count_1: 'şərh',  // singular: "1 comment"
  comm_count_n: 'şərhlər',  // plural: "3 comments"
  comment1: 'İlk şərh edən siz olun...',
  comment: 'şərh...',
  edit: 'Düzəlt',
  email: 'Email',
  email_taken: 'This email is taken',
  emailtip: 'Your email is never shared',
  enter: 'ctrl + enter',
  expired1: 'We just sent you a new one. Please check your email.', // http://d.pr/i/1OEV
  expired: 'This link has expired',
  feed: 'My feed', // alternatives: My own, personal

  help2: 'post',
  help3: 'quoted',
  help5: 'code, language guessed',
  help6: 'HTML code',
  in_forum: 'in',
  invalid: 'Invalid value',
  join: 'Join Muut',
  later: 'Later...',
  less: 'less',
  like: 'Bəyən',
  likepost: 'Like this post',
  loading: 'Yüklənir...',
  login: 'Gir',
  login1: 'Log in first',
  login_and: "Gir və",

  logout: 'Çıx',
  mark: 'Offensive or spam',
  mean: 'Did you mean',
  name: 'Display name',
  nametip: 'Your real name, so people will recognize you',

  newpass: 'New password',
  noresults: 'No results for',
  nospam: 'No spam on your forum!',
  notexist: 'does not exist.',
  notify: 'Notify me of new releases',
  ok: 'ok',
  online: 'Online',
  post: 'Post',
  preview: 'Görünüş',
  progress: ['yüklənir...', 'çalışır...', 'və çalışır...', 'alınmır'],
  reconnect: 'Yenidən qoşulur...',
  removepost: 'Sil',
  reply: 'Cavab...',
  replybtn: 'Cavab',

  saved: 'saxlandı',
  search: 'Axtar',
  select: 'Kanal seçin',
  setup: 'Setup now',
  showing: 'Showing',

  spam: 'Spam',
  step1: 'We have sent you a confirmation email. Your email is not updated before you complete this step!',
  step: 'One more step',
  terms: 'I agree to the <a>terms of service</a>.',
  thanks: 'Çox sağolun!',
  uname_len: 'Type 6 characters or more',
  uname_taken: 'This username is taken!',
  unametip: 'This cannot be changed later',
  undo: 'Undo',
  unlike: 'Unlike',
  unspam: 'Not spam',
  unver1: 'Unverified account',
  unver2: 'Please check your email to verify your account. Verified users can watch threads and receive email notifications. <a>Send a new verification code...</a>',
  unver3: '<a>Send a new</a> verification code to:',
  unver4: "Sent. Please check your inbox.",
  unver: 'Unverified',
  unwall: 'unwatch all',
  unwatch: 'Unwatch',
  upgrade2: 'Muut uses WebSockets or CORS for cross domain communication. All modern browsers above Opera 11 and IE7 work.',
  upgrade: 'Please upgrade your browser',
  username_taken: 'This username is taken',
  watch: 'Watch for new replies',
  welcome1: 'Please check your email to complete the registration. If you dont receive email within a minute or two, check your spam folder.',
  welcome2: 'Please provide a Muut username',
  welcome: 'Welcome to Muut',
  you: 'You',

  // times
  now: 'indicə',
  months: "Yan,Fev,Mar,Apr,May,İyn,İyl,Avq,Sen,Okt,Noy,Dek",
  min: 'dəq',
  hour: 'saat',
  day: 'gün',
  week: 'həftə'

}
