moot.language = {

  // the language code
  $code: 'es',

  /* New stuff */
  moderator: 'Moderator',
  mkadmin: 'Make administrator',
  mkmod: 'Make moderator',
  upgrade_mod: 'to make this user a moderator',
  upgrade_admin: 'to make this user administrator or moderator',

  my_profile: 'My profile',
  post_in: 'Post in',
  address_now: 'Thank you! Your email address has been confirmed.',
  open_pw: 'Please hit the button below to open a password change dialog',
  non_anon: 'You need to be logged in to perform this action',

  plan: 'Plan',
  trial: 'Start free trial',

  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spam?",

  channels: 'Foros',
  ch_name: 'Nombre del foro',
  ban:  'Banear usuario',
  banned:  'Baneado',
  days:  'Días',
  forever: 'Siempre',
  slogan:  'Foros y comentarios gratis de Muut',

  add: '+ Añadir',
  addons: 'Complementos',
  myaccount: "Mi cuenta",
  untitled: "Sin título",
  design: "Diseño",

  no_title: "El título no debe estar vacío",
  designer: "Diseñador",
  developer: "Desarrollador",

  ban_acc: 'Cuenta expulsada',
  ban_msg: 'Estás temporalmente expulsado de este foro por violar las políticas del foro. Tiempo restante:',
  banned4: 'Ya no puedes publicar en este foro.',
  warning: 'Atención',
  profanity: 'No están permitidas los insultos en este foro. El abuso continuado de está política provocará su expulsión.',

  img_needed: "Por favor sube una imagen",
  max: 'El tamaño máximo de imagen es 4MB',
  yes: 'Sí',
  upload: 'Subir imágenes',
  show: 'mostrar',
  hide: 'ocultar',
  invisible: 'Invisible',
  givebody: 'El cuerpo no puede estar vacio.',
  show_old: 'Mostrar respuestas más antiguas',
  show_more: 'Mostrar más respuestas',
  show_new: 'Mostrar respuestas más nuevas',
  start: 'Comienza un nuevo tema...',
  single: 'palabra sola',
  bold: 'negrita',
  italics: 'cursiva',
  monospaced: 'monoespaciada',
  learn: 'Saber más...',
  settings: 'Ajustes',
  error: 'Oops, un error. Por favor cópialo en el portapapeles, y recarga. ¡Lo corregiremos!',
  body: 'Texto del cuerpo',
  admin: 'Admin',
  someone: 'Alguien',
  writing: 'está escribiendo...',
  manage: 'Manage',
  admin: 'Administrar',
  fullview: 'Vista entera',
  title: 'Título',
  link: 'enlace',
  avatar: 'Cambiar avatar',
  upgrade_link: 'Actualización',
  branding: 'Creación de Marca (Branding)',
  logo: 'Logotipo',
  css: 'Archivo CSS',

  /* End new stuff */
  username_fail: 'Usar letras, números o guiones',
  all: 'Todo', // or alternatively: All
  anon_1: 'anónimo',
  anon: 'anónimos',
  badforum: 'Foro no válido',
  c_acc1: 'Tu cuenta está ahora habilitada en todos los sitios que usen Muut',
  c_acc: 'Cuenta confirmada',
  c_email: 'Email confirmado',
  cancel: 'Cancelar',
  change: 'Cambiar',

  changepw: 'Cambiar contraseña',
  close: 'Cerrar',
  collapse: 'Contraer todo',
  comm_count_1: 'comentario',
  comm_count_n: 'comentarios',
  comment1: 'Sé el primero en comentar...',
  comment: 'Comentar...',
  edit: 'editar',
  email: 'Email',
  email_taken: 'Este email ya está registrado',
  emailtip: 'Tu email nunca será compartido',
  enter: 'ctrl + enter',
  expired1: 'Hemos enviado uno nuevo. Por favor revisa tu email.',
  expired: 'Este enlace ha expirado',

  feed: 'Míos',

  help2: 'enviar',
  help3: 'citado',
  help5: 'código, lenguaje adivinado',
  help6: 'código html',
  in_forum: 'en',
  invalid: 'Valor no válido',
  join: 'Unirse a Muut',
  later: 'Más tarde...',
  less: 'menos',
  like: 'Me gusta',
  likepost: 'Me gusta ésta entrada',
  loading: 'Cargando...',
  login: 'Iniciar sesión',
  login1: 'Primero iniciar sesión',
  login_and: "Iniciar sesión y",

  logout: 'Salir',
  mark: 'Ofensivo o spam',
  mean: 'Te refieres a',
  name: 'Mostrar nombre',
  nametip: 'Tu nombre real, por el que la gente te reconocerá',
  newpass: 'Nueva contraseña',
  noresults: 'Sin resultados para',
  nospam: '¡Sin spam en tu foro!',
  notexist: 'no existe.',
  ok: 'ok',
  online: 'Online',
  post: 'Enviar',
  preview: 'Previo',
  progress: ['cargando...', 'todavía trabajando...', 'y trabajando...', 'abandonando'],
  reconnect: 'Reconectando...',
  removepost: 'Eliminar esta entrada',
  reply: 'Contestar...',
  replybtn: 'Contestar',
  save: 'Guardar cambios',
  saved: 'guardados',
  search: 'Buscar',
  select: 'Seleccionar foro',
  setup: 'Configurar ahora',
  showing: 'Mostrando',
  spam: 'Spam',
  step1: 'Hemos enviado un email de confirmación. ¡Tu email no será actualizado antes de que completes este paso!',
  step: 'Un paso más',
  terms: 'Acepto los <a>términos del servicio</a>.',
  thanks: '¡Gracias!',
  uname_len: 'Escribe 4 caracteres o más',
  uname_taken: '¡Este nombre de usuario está ocupado!',
  unametip: 'Esto no puede ser cambiado luego',
  undo: 'Deshacer',
  unlike: 'No me gusta',
  unspam: 'No spam',
  unver1: 'Cuenta no verificada',
  unver2: 'Por favor revisa tu email para verificar tu cuenta.',
  unver3: 'Enviar un nuevo código de verificación',
  unver4: "Enviado. Por favor, revisa tu bandeja de entrada.",
  unver: 'No verificado',
  unwall: 'dejar de vigilar',
  unwatch: 'No vigilar',
  upgrade2: 'Muut usa WebSockets o CORS para la comunicación entre dominios. Funciona en todos los navegadores modernos excepto en Opera 11 y IE7.',
  upgrade: 'Por favor, actualice su navegador',
  username_taken: 'Este nombre de usuario está ocupado',
  watch: 'Vigilar nuevas respuestas',
  welcome1: 'Por favor revisa tu email para completar la registración. Si no recibes un email en un minuto o dos, revisa tu carpeta de spam.',
  welcome2: 'Por favor, proporciona un nombre de usuario',
  welcome: 'Bienvenido a Muut',
  you: 'Tú',

  // times
  months: "Ene,Feb,Mar,Abr,May,Jun,Jul,Ago,Set,Oct,Nov,Dic",
  min:  'm',
  hour: 'h',
  day:  'd',
  week: 's'

}
