moot.language = {

   // the language code
   $code: 'es',

   /* New stuff */
   no_title: "Title must be given",
   designer: "Designer",
   developer: "Developer",

   s3: 'Custom S3 bucket',
   s3_tip: 'Allows custom domain for search engines and a backup storage.',
   s3_tip2: 'Add full access permissions for <em>moot-aws@moot.it</em>',
   s3_no_access: "moot-aws@moot.it cannot access this bucket",
   s3_missing: "This bucket does not exist",

   max: 'Maximum image size is 4Mb',
   yes: 'Yes',
   upload: 'Upload images',
   show: 'show',
   hide: 'hide',
   invisible: 'Invisible',
   givebody: 'Cuerpo no puede ser vacio.',
   show_old: 'Muestra respuestas más antiguas',
   show_more: 'Muestra más respuestas',
   show_new: 'Muestra respuestas más nuevas',
   start: 'Comienza con un nuevo tema...',
   single: 'palabra sola',
   bold: 'negrita',
   italics: 'cursiva',
   monospaced: 'monospaced',
   domain: 'URL Foro',
   domaintip: 'Full URL to the forums where users are pushed from search results',
   learn: 'Aprendá más...',
   ga: 'Google Analytics Id',
   admins: 'Administradores',
   adminstip: 'Nombre de un usuario por linea',
   settings: 'Sobreseimientos',
   error: 'Oops, un error. Por favor copialo en la memoria temporal, y recarga. ¡Vamos a corrigir esto!',
   body: 'Texto del cuerpo',
   admin: 'Admin',
   someone: 'Alguien',
   writing: 'esta escribiendo...',
   basic: 'Basico (gratis)',
   subs: 'Suscripciones',
   manage: 'Adminsitrar',
   fullview: 'Vista entera',
   title: 'Titlulo',
   link: 'enlace',
   avatar: 'Cambiar avatar',
   seo_update: 'La página SEO será actualizada dentro una hora',
   upgrade_link: 'Actualización',
   branding: 'Creación de Marca (Branding)',
   logo: 'Logotip',
   bgcolor: 'Color del fondo',
   brand_name: 'Brand name',
   css: 'Archivo CSS',
   mootbrand: 'Usa branding de Moot',
   sso: 'Single Sign-On',
   apikey: 'Clave de API',
   apisecret: 'Clave secreto',

   /* End new stuff */
   username_fail: 'Usar letras, números o guiones',
   all: 'Todas las entradas', // or alternatively: All
   anon_1: 'anónimo',
   anon: 'anónimo',
   badforum: 'Foro no válido',
   c_acc1: 'Tu cuenta está ahora habilitada en todos los sitios que usen Moot',
   c_acc: 'Cuenta confirmada',
   c_email: 'Email confirmado',
   cancel: 'Cancelar',
   change: 'Cambiar',

   changepw: 'Cambiar contraseña',
   close: 'Cerrar',
   collapse: 'Contraer todo',
   comm_count_1: 'comentario',
   comm_count_n: 'comentarios',
   comment1: 'Sé el primero en comentar...',
   comment: 'Comentar...',
   edit: 'editar',
   email: 'Email',
   email_taken: 'Este email está ocupado',
   emailtip: 'Tu email nunca es compartido',
   enter: 'ctrl + enter',
   expired1: 'Hemos enviado uno nuevo. Por favor revisa tu email.',
   expired: 'Este link ha expirado',

   feed: 'Mis feeds', // alternatives: My own, personal

   forumname: 'Nombre del foro',
   forums: 'Foros',

   help2: 'enviar',
   help3: 'citado',
   help5: 'codígo, lenguaje supuesto',
   help6: 'código html',
   in_forum: 'en',
   invalid: 'Valor no válido',
   join: 'Unirse a Moot',
   later: 'Más tarde...',
   less: 'menos',
   like: 'Me gusta',
   likepost: 'Me gusta esta entrada',
   loading: 'Cargando...',
   login: 'Iniciar sesión',
   login1: 'Primero iniciar sesión',
   login_and: "Iniciar sesión y",

   logout: 'Salir',
   mark: 'Ofensivo o spam',
   mean: 'Te refieres a',
   name: 'Mostrar nombre',
   nametip: 'Tu nombre real, por el que la gente te reconocerá',
   newcat: 'Nueva categoría',
   newpass: 'Nueva contraseña',
   noresults: 'Sin resultados para',
   nospam: '¡Sin spam en tu foro!',
   notexist: 'no existe.',
   notify: 'Notifícame las novedades',
   ok: 'ok',
   online: 'Online',
   post: 'Enviar',
   preview: 'Preview',
   progress: ['cargando...', 'todavía trabajando...', 'y trabajando...', 'abandonando'],
   reconnect: 'Reconectando...',
   removecat: 'Eliminar. La entradas no son removidas',
   removepost: 'Eliminar esta entrada',
   reply: 'Contestar...',
   replybtn: 'Contestar',
   save: 'Guardar cambios',
   saved: 'guardados',
   search: 'Buscar',
   select: 'Seleccionar foro',
   setup: 'Configurar ahora',
   showing: 'Mostrando',
   slogan: 'Foros y comentarios re-imaginados',
   spam: 'Spam',
   step1: 'Hemos enviado un email de confirmación. ¡Tu email no será actualizado antes de que completes este paso!',
   step: 'Un paso más',
   terms: 'Adhiero a los <a>términos del servicio</a>.',
   thanks: '¡Gracias!',
   uname_len: 'Escribe 6 caracteres o más',
   uname_taken: '¡Este nombre de usuario está ocupado!',
   unametip: 'Esto no puede ser cambiado luego',
   undo: 'Deshacer',
   unlike: 'No me gusta',
   unspam: 'No spam',
   unver1: 'Cuenta no verificada',
   unver2: 'Por favor revisa tu email para verificar tu cuenta. Los usuarios verificdos puede ver moots y recibir notificaciones por email. <a>Enviar un nuevo código de verificación...</a>',
   unver3: '<a>Enviar un nuevo</a> código de verificación a:',
   unver4: "Enviado. Por favor, revisa tu bandeja de entrada.",
   unver: 'No verificado',
   unwall: 'todo no visto',
   unwatch: 'No visto',
   upgrade2: 'Moot usa WebSockets o CORS para la comunicación entre dominios. Trabaja en todos los navegadores modernos excepto en Opera 11 y IE7.',
   upgrade: 'Por favor, actualice su navegador',
   username_taken: 'Este nombre de usuario está ocupado',
   watch: 'Ver este moot',
   welcome1: 'Por favor revisa tu email para completar la registración. Si no recibes un email en un minuto o dos, revisa tu carpeta de spam.',
   welcome2: 'Por favor, provéenos un nombre de usuario',
   welcome: 'Bienvenido a Moot',
   you: 'Tu',

   // times
   months: "Ene,Feb,Mar,Abr,May,Jun,Jul,Ago,Set,Oct,Nov,Dic",
   min:  'm',
   hour: 'h',
   day:  'd',
   week: 's'

}