moot.language = {

  // the language code
  $code: 'eu',

  no_notify: 'Disable all email notifications',
  watchall: 'Watch for all new threads',

  move: 'Mugitu haria',
  moved: 'Mugitutako haría',
  custom_path1: 'Bide Pertsonalizatua',
  custom_path: 'Sartu bide pertsonalizatua',
  invalid_path: 'Bide pertsonalizatu Baliogabea',
  from: 'tik',
  to: 'ra',
  show_preview: 'Show preview',

  retire: 'Ezabatu',
  retire_title: 'Haria ezabatu',
  retire_desc: 'Ezabatutako hariak ez dira berriz hasierara itzuliko agertzen diren jarioetan',
  retired_desc: 'Hari hau ezabatu da. Erantzunak ez dira berriz agertuko jarioaetan',
  is_retired: 'Hari hau ezabatu da',

  unretire: 'Unretire',
  unretire_title: 'Unretire thread',
  unretire_desc: 'This thread will be bumped to top in the feeds they appear in.',
  quote_help1: 'Aukeratu',
  quote_help2: 'Aipatu edo elkarbanatu',

  trial_left: 'Froga modua utzi',
  after_trial: 'Froga epea amaitzen denean Muut erabiltzen jarraitu ahal duzu',
  free_plan: 'Dohako plana',
  reward: 'Erreferentzia saria',
  off33: 'Hobetu orain eta %33 aurreztu gure ordaiketa plan guztietan',
  spread: 'Hitza zabaldu!',
  invite: 'Gonbidatu lagun bat Muut komunitatera eta biak sarituko zaituztegu! ',
  start_now: 'Hasi zure komunitateax train , dohakoa da!',
  start_btn: 'Sortu',
  reserve: 'Erreserbatu zure foroaren izena',
  free_acc: 'Dohako kontua',
  no_dialog: 'eta elkarrizketa hau ezabatu',
  click_change: 'Sakatu aldatatzeko',

  moderator: 'Moderatzailea',
  mkadmin: 'Egin Administratzailea',
  mkmod: 'Egin Moderatzailea',
  upgrade_mod: 'erabiltzaile hau moderatzaile egiteko',
  upgrade_admin: 'erabiltzaileak administratzaile edo moderatzaile egiteko',

  my_profile: 'Nire profila',
  post_in: 'Idatzi',
  address_now: 'Eskerrik asko! Zure e-posta helbidea egiaztatu da.',
  open_pw: 'Mesedez sakatu beheko botoia pasahitz aldaketa egiteko',
  non_anon: 'Ekintza hori burutzeko logeatuta egon behar zara',

  plan: 'Plana',
  trial: 'Hasi froga moduan dohan',

  is_private: 'Komunitate hau pribatua da',
  owner_msg: 'Zure mezua foroaren jabearentzat… (aukerakoa)',
  req_access: 'Sarbidea eskatu',
  req_sent: 'Sarbide eskaera bidalita',
  or_join: 'edo <a>Eman izena/a> Komunitatenan sartzeko.',
  save_with: 'aurreztu %20a urte osoko fakturazioarekin',
  rem_post: 'Post hau ezabatu nahi duzu?',
  is_spam: 'Post hau spam-a da?',

  channels: 'Kanalak',
  ch_name: 'Kanalaren izena',
  ban: 'Erabiltzailea blokeatu',
  banned: 'Blokeatuta',
  ban_acc: 'Kontu hau blokeatuta dago',
  ban_msg: 'Foro honetan idaztea debekatuta duzu aldi batez',
  days: 'Egunak',
  forever: 'Betirako',
  slogan: 'Doako foroak eta iruzkinak Muut-en eskutik',

  add: '+ Gehitu',
  addons: 'gehigarriak',
  myaccount: 'Kontua',
  untitled: 'Izenik gabe',
  design: 'Disieinua',
  no_title: 'Izenburua eman behar zaio',
  designer: 'Diseinatzailea',
  developer: 'Sustatzailea',


  warning: 'Oharra',
  profanity: 'Blasfemia debekatuta dago foro honetan. Praktika honekin jarraitu ez gero kontua blokeatuko da.',

  img_needed: 'Kargatu irudi fitxategi bat',
  max: 'Gehienezko irudi tamaina 4Mb da',
  yes: 'Bai',
  upload: 'Irudiak igo',
  show: 'Erakutsi',
  hide: 'Ezkutatu',
  invisible: 'Ikusteziña',
  givebody: 'Ezin da hutsik egon.',
  show_old: 'Erakutsi erantzun zaharragoak',
  show_more: 'Erakutsi erantzun gehiago',
  show_new: 'Erakutsi erantzun berriagoak',
  start: 'Gai berri bat hasi ...',
  error: 'Errore bat gertatu da. Mesedez, kopia bat egin, arbelera freskatu eta saiatu berriro. Sentitzen dugu - Laster konpondu egingo dugu',
  body: 'Gorputza',
  admin: 'Admin',
  someone: 'Norbait',
  title: 'Izenburua',
  writing: 'idazten dabil…',
  manage: 'Kudeatu',
  fullview: 'ikuspegi osoa',
  link: 'Esteka',
  avatar: 'Aldatu avatar-a',

  upgrade_link: 'Berritu',
  branding: 'Irudia',
  logo: 'Logotipoa',

  title: 'Izenburua',
  css: 'CSS fitxategia',

  single: 'Hitz bakarra',

  username_fail: 'Erabili letra, zenbaki edo marrak',
  bold: 'beltzez',
  italics: 'letra etzanez',
  monospaced: 'espaziobakarra',

  settings: 'Ezarpenak',

  all: 'Mezu guztiak', // or alternatively: Guztiak
  anon_1: 'anonimoa',  // singular
  anon: 'anonimoak',  // plural

  badforum: 'Foro baliogabea',
  c_acc1: 'Zure kontzak Muut erabiltzen duen leku gurtietan funtzionatzen du ',
  c_acc: 'Kontua berretsita',
  c_email: 'Helbide elektronikoa eguneratua',
  cancel: 'Utzi',
  change: 'Aldatu',
  changepw: 'Pasahitza aldatu',
  close: 'Itxi',
  collapse: 'Tolestu guztiak',
  comm_count_1: 'Iruzkina',  // singular: '1 iruzkin'
  comm_count_n: 'Iruzkinak',  // plural: '3 iruzkin'
  comment1: 'Izan zaitez lehena iruzkintzen…',
  comment: 'Iruzkindu…',
  edit: 'Editatu',
  email: 'E-posta',
  email_taken: 'E-posta hau hartuta dago',
  emailtip: 'Zure e-posta ez da inoiz partekatuko',
  enter: 'ctrl + enter',
  expired1: 'Berri bat bidali dizugu. Mesedez egiaztatu zure e-posta.', // http://d.pr/i/1OEV
  expired: 'Esteka hau iraungi egin da',
  feed: 'Nire jarioa', // alternatives: Nirea, pertsonala

  help2: 'post',
  help3: 'Aipatua',
  help5: 'kodea, Hizkuntza asmatua',
  help6: 'HTML kodea',
  in_forum: 'in',
  invalid: 'baliogabea',
  join: 'Muut-en izena eman',
  later: 'Beranduago…',
  less: 'gutxiago',
  like: 'Atsegin',
  likepost: 'Post hau atsegin',
  loading: 'Kargatzen…',
  login: 'Saioa hasi',
  login1: 'Saioa hasi lehenego',
  login_and: 'Saioa hasi eta',

  logout: 'Saioa itxi',
  mark: 'Iraingarria edo spam-',
  mean: 'Esan nahi zenuen',
  name: 'Izena bistaratu',
  nametip: 'Zure benetako izena, jendeak ezagutu egingo zaitu orduan',

  newpass: 'Pasahitz berria',
  noresults: 'Ez da emaitzarik izan',
  nospam: 'Spam-ik ez zure foroan!',
  notexist: 'ez da existitzen',
  ok: 'Ados',
  online: 'Online',
  post: 'Argitaratu',
  preview: 'Aurrebista',
  progress: ['kargatzen…', 'oraindik lanean…', 'eta lanean…', 'etsi egin du'],
  reconnect: 'Berkonektatzen…',
  removepost: 'Kendu',
  reply: 'Erantzun…',
  replybtn: 'Erantzun',

  saved: 'Gordeta',
  search: 'Bilatu',
  select: 'Kanala hautatu',
  setup: 'Konfiguratu orain',
  showing: 'erakusten',

  spam: 'Spam',
  step1: 'Egiaztapen mezu bat bidali dizugu. Zure eposta ez da eguneratuko urrats hau burutu aurretik!',
  step: 'Pausu bat gehiago',
  terms: 'Ados <a>zerbitzuaren baldintzekin</a>.',
  thanks: 'Eskerrik asko!',
  uname_len: 'Idatzi 4 karaktere edo gehiago',
  uname_taken: 'Erabiltzaile izan hora hartuta dago!',
  unametip: 'Hau ezin da aldatu geroago',
  undo: 'Ezabatu',
  unlike: 'Desatsegin',
  unspam: 'Hau ez da Spam-a',
  unver1: 'Ziurtatu gabeko kontua',
  unver2: 'Mesedez begiratu zure e-posta kontua egiaztatzeko.',
  unver3: 'Berbidali egiaztapen lotura',
  unver4: 'Bidalita. Mesedez egiaztatu zure sarrera-ontzia.',
  unver: 'Ziurtatu gabe',
  unwall: 'Guztiak ikusi gabe',
  unwatch: 'Ikusi gabe',
  upgrade2: 'Muut-ek WebSockets edo CORS erabiltzen ditu domeinuen komunikaziorako. All modern browsers above Opera 11 and IE7 work.',
  upgrade: 'Mesedez, eguneratu zure nabigatzailea',
  username_taken: 'Erabiltzaile izen hau hartu da',
  watch: 'Ikusi erantzun berriak',
  welcome1: 'Mesedez egiaztatu zure e-posta erregistroa osatzeko. Minute baten ego bitten e-postarik paso ez baduzu, begirati Spam-ean',
  welcome2: 'Mesedez eman Muut erabiltzaile izena',
  welcome: 'Ongi etorri Muut-era',
  you: 'Zu',

  // times
  now: 'oraintxe',
  months: 'Urt,Ots,Mar,Apr,Mai,Eka,Uzt,Abu,Ira,Urr,Aza,Abe',
  min: 'm',
  hour: 'o',
  day: 'e',
  week: 'a'

}
