moot.language = {

   $code: 'fi',

   mods:    'Moderators',
   ban:     'Estä',
   banned:  'Estetty',
   ban_usr: 'Estetyt käyttäjät',
   ban_acc: 'Käyttö estetty',
   ban_msg: 'Et voi toistaiseksi kirjoittaa tähän yhteisöön.',
   days:    'Päivää',
   forever: 'Ikuisesti',
   slogan:  'Muut – Ilmainen foorumi ja kommentointi',

   add: '+ Lisää',
   addons: 'Laajennukset',
   myaccount: "Oma tilini",
   untitled: "Ei otsikkoa",
   design: "Ulkoasu",
   no_title: "Otsikko on annettava",
   designer: "Designer",
   developer: "Developer",

   no_index: 'Poista indexointi muut.com- domainin alaisuudesta',
   mkpriv: 'Estä pääsy tähän foorumiin muualta',
   sign: 'Forumi pitää ensin <a>signeerata</a>.',

   s3: 'Custom S3 bucket',
   s3_tip: 'Allows custom domain for search engines and a backup storage.',
   s3_tip2: 'Add full access permissions for <em>moot-aws@moot.it</em>',
   s3_no_access: "moot-aws@moot.it cannot access this bucket",
   s3_missing: "This bucket does not exist",


   img_needed: "Vain kuvatiedostot kelpaavat",
   max: 'Maksimi kuvakoko: 4Mb',
   yes: 'Kyllä',
   upload: 'Lataa kuvia',

   show_old: 'Näytä vanhimmat vastaukset',
   show_more: 'Lisää vastauksia',
   show_new: 'Näytä uusimmat vastaukset',
   start: 'Uusi aihe...',
   someone: 'Joku',
   writing: 'kirjoittaa...',
   basic: 'Perus (ilmainen)',
   subs: 'Tilaukset',
   manage: 'Ylläpito',
   fullview: 'Näytä kokonaan',
   title: 'Otsikko',
   link: 'linkki',
   avatar: 'Vaihda kuva',
   seo_update: 'Staattiset sivusi päivittyvät tunnin sisällä',
   upgrade_link: 'Päivitä',
   branding: 'Brändäys',
   logo: 'Logo',
   bgcolor: 'Taustaväri',
   brand_name: 'Brändisi nimi',
   css: 'CSS tiedosto',
   mootbrand: 'Käytä Muut- brändäystä',
   sso: 'Single Sign-On',
   apikey: 'API avain',
   apisecret: 'Salainen avain',
   single: 'yksi sana',
   bold: 'lihavoitu',
   italics: 'kursiivilla',
   monospaced: 'kiinteävälistä',
   domain: 'Foorumin URL',
   domaintip: 'Foorumisi osoite jonne käyttäjät ohjataan hakutuloksista',
   learn: 'Lue lisää...',
   ga: 'Google Analytics tunnus',
   admin: 'Ylläpitäjä',
   admins: 'Ylläpitäjät',
   adminstip: 'Yksi käyttäjätunnus per rivi',
   settings: 'Asetukset',

   username_fail: 'Käytä kirjaimia, numeroita tai väliviivaa',
   all: 'Kaikki',
   anon_1: 'anonyymi',  // singular
   anon: 'anonyymiä',   // plural
   badforum: 'Epäkelpo foorumi',
   c_acc1: 'Voit nyt käyttää kaikkia sivustoja, joissa on Muut käytössä',
   c_acc: 'Sinut on vahvistettu',
   c_email: 'Osoitteesi on vahvistettu',
   cancel: 'Peru',
   change: 'Muuta',

   changepw: 'Muuta salasanaa',
   close: 'Sulje',
   collapse: 'Sulje kaikki',
   comm_count_1: 'kommentti',
   comm_count_n: 'kommenttia',
   comment1: 'Kommentoi ensimmäisenä...',
   comment: 'Kommentoi...',
   edit: 'muokkaa',
   email: 'Sähköposti',
   email_taken: 'Tämä osoite on jo käytössä',
   emailtip: 'Osoite on salainen, eikä sitä anneta eteenpäin',
   enter: 'ctrl + rivinvaihto',
   expired1: 'Lähetimme sinulle juuri mailitse uuden',
   expired: 'Vanhentunut vahvistuskoodi',
   feed: 'Omat',
   forumname: 'Foorumin nimi',
   forums: 'Foorumit',

   help2: 'lähetä',
   help3: 'lainaus',
   help5: 'koodia, kieli arvataan',
   help6: 'html koodia',
   in_forum: 'foorumissa',
   invalid: 'Virheellinen kentän arvo',
   join: 'Liity Muut:tiin',
   later: 'Myöhemmin...',
   less: 'vähemmän',
   like: 'Tykkää',
   likepost: 'Tykkää tästä kirjoituksesta',
   loading: 'Ladataan...',
   login: 'Kirjaudu',
   login1: 'Kirjaudu ensin sisään',
   login_and: "Kirjaudu ja",

   logout: 'Poistu',
   mark: 'Asiaton tai roskaa',
   mean: 'Tarkoititko',
   name: 'Näkyvä nimi',
   nametip: 'Oikea nimesi, jolla sinut tunnetaan',
   newcat: 'Uusi foorumi',
   newpass: 'Uusi salasana',
   noresults: 'Ei tuloksia haulle',
   nospam: 'Ei spämmiä!',
   notexist: 'ei löydy.',
   notify: 'Ilmoita uusista Muut-pävityksistä',
   ok: 'ok',
   online: 'Paikalla',
   post: 'Lähetä',
   preview: 'Esikatselu',
   progress: ['ladataan...', 'edelleen...', 'yhä vielä...', 'luovutetaan'],
   reconnect: 'Luodaan yhteys...',
   removecat: 'Poista nimi. Itse keskustelua ei tuhota',
   removepost: 'Poista',
   reply: 'Vastaa...',
   replybtn: 'Vastaa',
   save: 'Tallenna',
   saved: 'tallennettu',
   search: 'Hae',
   select: 'Valitse foorumi',
   setup: 'Luo heti',
   showing: 'Näytetään',
   spam: 'Roskapostit',
   step: 'Vahvistus lähetetty',
   step1: 'Osoitteesi päivittyy, kun klikkaat mailissa olevaa linkkiä.',
   terms: 'Hyväksyn <a>käyttäjäehdot</a>.',
   thanks: 'Kiitos!',
   uname_len: '6 kirjainta tai enemmän',
   uname_taken: 'Tämä tunnus on jo varattu!',
   unametip: 'Tunnusta ei voi muuttaa myöhemmin',
   undo: 'Peru',
   unlike: 'En tykkääkään',
   unspam: 'Ei roskapostia!',
   unver1: 'Tiliä ei vahvistettu',
   unver2: 'Vahvista tilisi sinulle lähetetyssä mailissa. Tämän jälkeen voit saada mailitse tietoa uusista vastauksista. <a>Lähetä uusi vahvistuskoodi...</a>',
   unver3: '<a>Lähetä uusi</a> vahvistuskoodi osoitteeseen:',
   unver4: "Maili on lähetetty.",
   unver: 'Vahvistamaton',
   unwall: 'poista kaikkien seuranta',
   unwatch: 'En seuraa',
   upgrade2: 'Muut käyttää WebSocket tai CORS tekniikkaa. Kaikki selaimet, paitsi Opera 11 and IE7 tukevat näitä.',
   upgrade: 'Suosittelemme päivittämään selaimesi',
   username_taken: 'Tämä tunnus on jo käytössä',
   watch: 'Seuraa tätä keskustelua',
   welcome1: 'Vahvista tilisi sinulle lähetetyssä mailissa. Jos viestiä ei näy, tarkasta vielä roskaposteista.',
   welcome2: 'Luo Muut-käyttäjätunnus',
   welcome: 'Tervetuloa Mootin käyttäjäksi',
   you: 'Sinä',

   // times
   days: 'pv',
   hour: 'tunti sitten',
   hours: 'h',
   minute: 'minuutti sitten',
   minutes: 'min',
   now: 'nyt',
   months: "tammi,helmi,maalist,huhti,touko,kesä,heinä,elo,syys,loka,marras,joulu",
   week: 'viikko sitten',
   weeks: 'vk',
   yesterday: 'eilen'

}
