moot.language = {

  $code: 'fi',

  no_notify: 'Kytke sähköposti-ilmoitukset pois päältä',
  watchall: 'Ilmoita kaikista uusista viestiketjuista',
  move: 'Siirrä ketju',
  moved: 'Ketju siirretty',
  custom_path1: 'Oma polku',
  custom_path: 'Anna polku',
  invalid_path: 'Epäkelpo polku',
  from: 'Mistä',
  to: 'Mihin',

  retire: 'Arkistoi',
  retire_title: 'Arkistoi ketju',
  retire_desc: 'Arkistoidut ketjut eivät pomppaa syötteiden alkuun.',
  retired_desc: 'Tämä ketju on arkistoitu. Uudet vastaukset eivät enää pompauta sitä syötteiden alkuun.',
  is_retired: 'Tämä ketju on arkistoitu',

  unretire: 'Poista arkistointi',
  unretire_title: 'Poista ketjun arkistointi',
  unretire_desc: 'Ketju pomppaa jälleen syötteen alkuun.',
  quote_help1: 'Valitse',
  quote_help2: 'siteerataksesi tai jakaaksesi',

  trial_left: 'jäljellä kokeilujaksoa.',
  after_trial: 'Kokeilujakson jälkeen voit jatkaa Muutin käyttöä',
  free_plan: 'ilmaisversiona',
  reward: 'Kaverialennus',
  off33: 'Tilaa heti – 33% alennus',
  spread: 'Levitä sanaa!',
  invite: 'Kutsu kaverisi perustamaan Muut-yhteisö – alennus molemmille',
  start_now: 'Perusta oma yhteisö ilmaiseksi!',
  start_btn: 'Luo',
  reserve: 'Varaa nimi yhteisöllesi',
  free_acc: 'Ilmainen tili',
  no_dialog: 'poistaaksesi tämän ilmoituksen',
  click_change: 'Vaihda',

  moderator: 'Moderaattori',
  mkadmin: 'Tee administraattori',
  mkmod: 'Tee moderaattori',
  upgrade_mod: 'tehdäksesi tästä käyttäjästä moderaattorin',
  upgrade_admin: 'tehdäksesi tästä käyttäjästä administraattorin tai moderaattorin',

  my_profile: 'Oma profiili',
  post_in: 'Kanavassa',
  address_now: 'Kiitos! Sähköpostiosoitteesti on vahvistettu.',
  open_pw: 'Paina allaolevaa nappia vaihtaaksesi salasanasi',
  non_anon: 'Kirjaudu ensin sisään!',

  plan: 'Tilaus',
  trial: 'Kokeile ilmaiseksi',

  is_private: "Suljettu yhteisö",
  owner_msg: "Viestisi ylläpitäjälle... (Ei pakollinen)",
  req_access: "Haluan sisään",
  req_sent: "Kiitos. Pyyntö vastaanotettu",
  or_join: "tai <a>Liity</a> yhteisöön",
  save_with: "Maksa vuosittain ja säästä 20%",
  rem_post: "Poista tämä kommentti?",
  is_spam: "Tämä kommentti on spämmiä?",

  channels: 'Kanavat',
  ch_name: 'Kanavan nimi',
  ban:  'Estä',
  banned:  'Estetty',
  ban_acc: 'Käyttö estetty',
  ban_msg: 'Et voi toistaiseksi kirjoittaa tähän yhteisöön.',
  days:  'Päivää',
  forever: 'Ikuisesti',
  slogan:  'Muut – Ilmainen foorumi ja kommentointi',

  add: '+ Lisää',
  addons: 'Laajennukset',
  myaccount: "Oma tilini",
  untitled: "Ei otsikkoa",
  design: "Ulkoasu",
  no_title: "Otsikko on annettava",
  designer: "Designer",
  developer: "Developer",

  givebody: 'Sisältö on annettava.',
  body: 'Sisältö',
  invisible: 'Piilossa',

  img_needed: "Vain kuvatiedostot kelpaavat",
  max: 'Maksimi kuvakoko: 4Mb',
  yes: 'Kyllä',
  upload: 'Lataa kuvia',

  show_old: 'Näytä vanhimmat vastaukset',
  show_more: 'Lisää vastauksia',
  show_new: 'Näytä uusimmat vastaukset',
  start: 'Uusi aihe...',
  someone: 'Joku',
  writing: 'kirjoittaa...',
  manage: 'Ylläpito',
  fullview: 'Näytä kokonaan',
  title: 'Otsikko',
  link: 'linkki',
  avatar: 'Vaihda kuva',
  upgrade_link: 'Päivitä',
  branding: 'Brändäys',
  logo: 'Logo',
  css: 'CSS tiedosto',
  single: 'yksi sana',
  bold: 'lihavoitu',
  italics: 'kursiivilla',
  monospaced: 'kiinteävälistä',
  learn: 'Lue lisää...',
  admin: 'Ylläpitäjä',
  settings: 'Asetukset',

  username_fail: 'Käytä kirjaimia, numeroita tai väliviivaa',
  all: 'Kaikki',
  anon_1: 'anonyymi',  // singular
  anon: 'anonyymiä',  // plural
  badforum: 'Epäkelpo foorumi',
  c_acc1: 'Voit nyt käyttää kaikkia sivustoja, joissa on Muut käytössä',
  c_acc: 'Sinut on vahvistettu',
  c_email: 'Osoitteesi on vahvistettu',
  cancel: 'Peru',
  change: 'Muuta',

  changepw: 'Muuta salasanaa',
  close: 'Sulje',
  collapse: 'Sulje kaikki',
  comm_count_1: 'kommentti',
  comm_count_n: 'kommenttia',
  comment1: 'Kommentoi ensimmäisenä...',
  comment: 'Kommentoi...',
  edit: 'muokkaa',
  email: 'Sähköposti',
  email_taken: 'Tämä osoite on jo käytössä',
  emailtip: 'Osoite on salainen, eikä sitä anneta eteenpäin',
  enter: 'ctrl + rivinvaihto',
  expired1: 'Lähetimme sinulle juuri mailitse uuden',
  expired: 'Vanhentunut vahvistuskoodi',
  feed: 'Omat',

  help2: 'lähetä',
  help3: 'lainaus',
  help5: 'koodia, kieli arvataan',
  help6: 'html koodia',
  in_forum: 'foorumissa',
  invalid: 'Virheellinen kentän arvo',
  join: 'Liity Muut:tiin',
  later: 'Myöhemmin...',
  less: 'vähemmän',
  like: 'Tykkää',
  likepost: 'Tykkää tästä kirjoituksesta',
  loading: 'Ladataan...',
  login: 'Kirjaudu',
  login1: 'Kirjaudu ensin sisään',
  login_and: "Kirjaudu ja",

  logout: 'Uloskirjaudu',
  mark: 'Asiaton tai roskaa',
  mean: 'Tarkoititko',
  name: 'Näkyvä nimi',
  nametip: 'Oikea nimesi, jolla sinut tunnetaan',
  newpass: 'Uusi salasana',
  noresults: 'Ei tuloksia haulle',
  nospam: 'Ei spämmiä!',
  notexist: 'ei löydy.',
  ok: 'ok',
  online: 'Paikalla',
  show: 'näytä',
  hide: 'piilota',
  post: 'Lähetä',
  preview: 'Esikatselu',
  progress: ['ladataan...', 'edelleen...', 'yhä vielä...', 'luovutetaan'],
  reconnect: 'Luodaan yhteys...',
  removepost: 'Poista',
  reply: 'Vastaa...',
  replybtn: 'Vastaa',
  save: 'Tallenna',
  saved: 'tallennettu',
  search: 'Hae',
  select: 'Valitse foorumi',
  setup: 'Luo heti',
  showing: 'Näytetään',
  spam: 'Roskapostit',
  step: 'Vahvistus lähetetty',
  step1: 'Osoitteesi päivittyy, kun klikkaat mailissa olevaa linkkiä.',
  terms: 'Hyväksyn <a>käyttäjäehdot</a>.',
  thanks: 'Kiitos!',
  uname_len: '4 kirjainta tai enemmän',
  uname_taken: 'Tämä tunnus on jo varattu!',
  unametip: 'Tunnusta ei voi muuttaa myöhemmin',
  undo: 'Peru',
  unlike: 'En tykkääkään',
  unspam: 'Ei roskapostia!',
  unver1: 'Tiliä ei vahvistettu',
  unver2: 'Vahvista tilisi sinulle lähetetystä mailista.',
  unver3: 'Lähetä uusi vahvistuskoodi',
  unver4: "Maili on lähetetty.",
  unver: 'Vahvistamaton',
  unwall: 'poista kaikkien seuranta',
  unwatch: 'En seuraa',
  upgrade2: 'Muut käyttää WebSocket tai CORS tekniikkaa. Kaikki selaimet, paitsi Opera 11 and IE7 tukevat näitä.',
  upgrade: 'Suosittelemme päivittämään selaimesi',
  username_taken: 'Tämä tunnus on jo käytössä',
  watch: 'Seuraa tätä keskustelua',
  welcome1: 'Vahvista tilisi sinulle lähetetyssä mailissa. Jos viestiä ei näy, tarkasta vielä roskaposteista.',
  welcome2: 'Luo Muut-käyttäjätunnus',
  welcome: 'Tervetuloa Mootin käyttäjäksi',
  you: 'Sinä',

  // times
  now: 'nyt',
  months: "tammi,helmi,maalist,huhti,touko,kesä,heinä,elo,syys,loka,marras,joulu",
  min: 'min',
  hour: 't',
  day: 'pv',
  week: 'vk'

}
