moot.language = {

   $code: 'fi',

   all: 'Kaikki',
   anon_1: 'anonyymi',  // singular
   anon: 'anonyymiä',   // plural
   badforum: 'Epäkelpo foorumi',
   c_acc1: 'Voit nyt käyttää kaikkia sivustoja, joissa on Moot käytössä',
   c_acc: 'Sinut on vahvistettu',
   c_email: 'Osoitteesi on vahvistettu',
   cancel: 'Peru',
   change: 'Muuta',

   changepw: 'Muuta salasanaa',
   close: 'Sulje',
   collapse: 'Sulje kaikki',
   comm_count_1: 'kommentti',
   comm_count_n: 'kommenttia',
   comment1: 'Kommentoi ensimmäisenä...',
   comment: 'Kommentoi...',
   edit: 'muokkaa',
   email: 'Sähköposti',
   email_taken: 'Tämä osoite on jo käytössä',
   emailtip: 'Osoite on salainen, eikä sitä anneta eteenpäin',
   enter: 'ctrl + rivinvaihto',
   expired1: 'Lähetimme sinulle juuri mailitse uuden',
   expired: 'Vanhentunut vahvistuskoodi',
   feed: 'Omat',
   forumname: 'Foorumin nimi',
   forums: 'Foorumit',
   help1: '1. rivi = otsikko',
   help2: 'lähetä',
   help3: 'lainaus',
   help4: 'toinen rivi',
   help5: 'koodia, kieli arvataan',
   help6: 'html koodia',
   in_forum: 'foorumissa',
   invalid: 'Virheellinen kentän arvo',
   join: 'Liity Moot:tiin',
   later: 'Myöhemmin...',
   less: 'vähemmän',
   like: 'Tykkää',
   likepost: 'Tykkää tästä kirjoituksesta',
   loading: 'Ladataan...',
   login: 'Kirjaudu',
   login1: 'Kirjaudu ensin sisään',
   login_and: "Kirjaudu ja",

   logout: 'Poistu',
   mark: 'Asiaton tai roskaa',
   mean: 'Tarkoititko',
   name: 'Näkyvä nimi',
   nametip: 'Oikea nimesi, jolla sinut tunnetaan',
   newcat: 'Uusi foorumi',
   newpass: 'Uusi salasana',
   noresults: 'Ei tuloksia haulle',
   nospam: 'Ei spämmiä!',
   notexist: 'ei löydy.',
   notify: 'Ilmoita uusista Moot-pävityksistä',
   ok: 'ok',
   online: 'Paikalla',
   post: 'Lähetä',
   preview: 'Esikatselu',
   progress: ['ladataan...', 'edelleen...', 'yhä vielä...', 'luovutetaan'],
   reconnect: 'Luodaan yhteys...',
   removecat: 'Poista nimi. Itse keskustelua ei tuhota',
   removepost: 'Poista',
   reply: 'Vastaa...',
   replybtn: 'Vastaa',
   save: 'Tallenna',
   saved: 'tallennettu',
   search: 'Hae',
   select: 'Valitse foorumi',
   setup: 'Luo heti',
   showing: 'Näytetään',
   slogan: 'Foorumit ja kommentointi myös sinun sivuille?',
   spam: 'Roskapostit',
   start: 'Mitä mielessä?',
   step: 'Vahvistus lähetetty',
   step1: 'Osoitteesi päivittyy, kun klikkaat mailissa olevaa linkkiä.',
   terms: 'Hyväksyn <a>käyttäjäehdot</a>.',
   thanks: 'Kiitos!',
   uname_len: '6 kirjainta tai enemmän',
   uname_taken: 'Tämä tunnus on jo varattu!',
   unametip: 'Tunnusta ei voi muuttaa myöhemmin',
   undo: 'Peru',
   unlike: 'En tykkääkään',
   unspam: 'Ei roskapostia!',
   unver1: 'Tiliä ei vahvistettu',
   unver2: 'Vahvista tilisi sinulle lähetetyssä mailissa. Tämän jälkeen voit saada mailitse tietoa uusista vastauksista. <a>Lähetä uusi vahvistuskoodi...</a>',
   unver3: '<a>Lähetä uusi</a> vahvistuskoodi osoitteeseen:',
   unver4: "Maili on lähetetty.",
   unver: 'Vahvistamaton',
   unwall: 'poista kaikkien seuranta',
   unwatch: 'En seuraa',
   upgrade2: 'Moot käyttää WebSocket tai CORS tekniikkaa. Kaikki selaimet, paitsi Opera 11 and IE7 tukee tätä.',
   upgrade: 'Suosittelemme päivittämään selaimesi',
   username_taken: 'Tämä tunnus on jo käytössä',
   watch: 'Seuraa tätä keskustelua',
   welcome1: 'Vahvista tilisi sinulle lähetetyssä mailissa. Jos viestiä ei näy, tarkasta vielä roskaposteista.',
   welcome2: 'Luo Moot-käyttäjätunnus',
   welcome: 'Tervetuloa Mootin käyttäjäksi',
   you: 'Sinä',

   // times
   days: 'pv',
   hour: 'tunti sitten',
   hours: 'h',
   minute: 'minuutti sitten',
   minutes: 'min',
   now: 'nyt',
   months: 'kk',
   week: 'viikko sitten',
   weeks: 'vk',
   yesterday: 'eilen'

}
