moot.language = {

   // the language code
   $code: 'fr',

   all: 'Tous les posts', // or alternatively: All

   anon_1: 'anonyme',     // singular
   anon: 'anonymes',      // plural

   badforum: 'Forum invalide',
   c_acc1: 'Votre compte fonctionne maintenant sur tous les sites utilisant Moot',
   c_acc: 'Compte vérifié',
   c_email: 'Adresse e-mail mise à jour',
   cancel: 'Annuler',
   change: 'Changer',
   changepw: 'Changer le mot de passe',
   close: 'Fermer',
   collapse: 'Tout réduire',
   comm_count_1: 'commentaire',   // singular: "1 comment"
   comm_count_n: 'commentaires',  // plural: "3 comments"
   comment1: 'Soyez le premier à commenter...',
   comment: 'Commenter...',
   edit: 'modifier',
   email: 'E-mail',
   email_taken: 'Cette adresse e-mail est prise',
   emailtip: 'Votre adresse e-mail ne sera jamais partagée',
   enter: 'Ctrl + Entrée',
   expired1: 'Nous venons de vous envoyer un nouveau. Veuillez vérifier vos e-mails.', // http://d.pr/i/1OEV
   expired: 'Ce lien a expiré',

   feed: 'Mon fil', // alternatives: My own, personal

   forumname: 'Nom du forum',
   forums: 'Forums',
   help1: 'La première ligne est le titre',
   help2: 'publier',
   help3: 'citation',
   help4: 'deuxième ligne',
   help5: 'code, langue auto-devinée',
   help6: 'code HTML',
   in_forum: 'dans',
   invalid: 'Valeur invalide',
   join: 'Rejoindre Moot',
   later: 'Plus tard...',
   less: 'moins',
   like: 'Aimer',
   likepost: 'Aimer ce post',
   loading: 'Chargement...',
   login: 'Se connecter',
   login1: 'Connectez-vous d\'abord',
   login_and: "Se connecter et",

   logout: 'Se déconnecter',
   mark: 'Offensif ou spam',
   mean: 'Vouliez-vous dire',
   name: 'Nom qui apparaît',
   nametip: 'Votre vrai nom, pour que les gens vous reconaissent',
   newcat: 'Nouvelle catégorie',
   newpass: 'Nouveau mot de passe',
   noresults: 'Aucun résultat pour',
   nospam: 'Aucun spam sur votre forum !',
   notexist: 'n\'existe pas.',
   notify: 'Informez-moi des nouvelles versions',
   ok: 'OK',
   online: 'En ligne',
   post: 'Publier',
   preview: 'Prévisualisation',
   progress: ['Chargement...', 'encore...', 'et encore...', 'abondon'],
   reconnect: 'Reconnexion...',
   removecat: 'Supprimer. Les posts ne seront pas supprimés',
   removepost: 'Supprimer',
   reply: 'Répondre...',
   replybtn: 'Répondre',
   save: 'Enregistrer les modifications',
   saved: 'enregistré',
   search: 'Rechercher',
   select: 'Sélectionnez le forum',
   setup: 'Installer maintenant',
   showing: 'Montrant',
   slogan: 'Forums et commentage ré-imaginés',
   spam: 'Spam',
   start: 'Quoi de neuf ?',
   step1: 'Nous vous avons envoyé un e-mail de confirmation. Votre adresse e-mail ne sera pas mise à jour avant d\'avoir terminé cette étape !',
   step: 'Une dernière étape',
   terms: 'J\'accepte les <a>modalités du service</a>.',
   thanks: 'Merci !',
   uname_len: 'Tapez 6 caractères ou plus',
   uname_taken: 'Ce nom d\'utilisateur est pris !',
   unametip: 'Ceci ne pourra être changé par la suite',
   undo: 'Annuler',
   unlike: 'Ne plus aimer',
   unspam: 'Non spam',
   unver1: 'Compte non vérifié',
   unver2: 'Veuillez consulter vos e-mails pour vérifier votre compte. Les utilisateurs ayant été vérifiés peuvent faire attention aux Moots et recevoir des notifications par e-mail. <a>Envoyer un nouveau code de vérification...</a>',
   unver3: '<a>Envoyer un nouveau</a> code de vérification à :',
   unver4: "Envoyé. Veuillez vérifier votre boîte de réception.",
   unver: 'Non vérifié',
   unwall: 'ne plus faire attention aux Moot',
   unwatch: 'Ne plus y faire attention',
   upgrade2: 'Moot utilise les WebSockets ou CORS pour les communications cross-domain. Tous les navigateurs modernes à part Opera 11 et IE7 fonctionnent.',
   upgrade: 'Veuillez mettre à jour votre navigateur',
   username_taken: 'Ce nom d\'utilisateur est pris',
   watch: 'Faire attention aux nouvelles réponses',
   welcome1: 'Veuillez vérifier vos e-mails pour finir votre inscription. Si vous ne recevez pas d\'e-mails dans une minute ou deux, vérifiez votre dossier "Spam".',
   welcome2: 'Veuillez fournir un nom d\'utilisateur Moot',
   welcome: 'Bienvenue sur Moot',
   you: 'Vous',

   // times
   now: 'à l\'instant',
   months: "Jan,Fév,Mar,Avr,Mai,Juin,Juil,Aoû,Sep,Oct,Nov,Déc",
   min: 'm',
   hour: 'h',
   day: 'j',
   week: 's'

}
