moot.language = {

   // the language code
   $code: 'fr',

   all: 'Tous les posts', // or alternatively: All

   anon_1: 'anonyme',    // singular
   anon: 'anonymes',      // plural

   badforum: 'Forum Invalide',
   c_acc1: 'Votre compte fonctionne maintenant sur tous les sites utilisant Moot',
   c_acc: 'Compte confirmé',
   c_email: 'Adresse email mise à jour',
   cancel: 'Annuler',
   change: 'Modifier',

   changepw: 'Modifier mot de passe',
   close: 'Fermer',
   collapse: 'Réduire tout',
   comm_count_1: 'commentaire',   // singular: "1 comment"
   comm_count_n: 'commentaires',  // plural: "3 comments"
   comment1: 'Soit le premier à commenter...',
   comment: 'Commentaire...',
   edit: 'éditer',
   email: 'Email',
   email_taken: 'Cette adresse email est déjà prise',
   emailtip: 'Votre adresse email ne sera jamais partagé',
   enter: 'ctrl + entré',
   expired1: 'Nous venons de vous envoyer un nouveau. Veuillez vérifier vos emails.', // http://d.pr/i/1OEV
   expired: 'Ce lien a expiré',

   feed: 'Mon flux', // alternatives: My own, personal

   forumname: 'Nom du forum',
   forums: 'Forums',
   help1: 'Première ligne est le titre',
   help2: 'post',
   help3: 'citation',
   help4: 'deuxième line',
   help5: 'code, langue',
   help6: 'HTML code',
   in_forum: 'in',
   invalid: 'valeur invalide',
   join: 'Rejoindre Moot',
   later: 'Plus tard...',
   less: 'moins',
   like: 'Aimer',
   likepost: 'Aimer ce post',
   loading: 'Chargement...',
   login: 'Connexion',
   login1: 'Connectez vous d\'abbord',
   login_and: "Connectez vous et...",

   logout: 'Déconnexion',
   mark: 'Offensive ou spam',
   mean: 'Voulez-vous dire',
   name: 'Nom qui apparaîtra',
   nametip: 'Votre vrai nom, afin que les gens vous reconnaissent',
   newcat: 'Nouvelle catégorie',
   newpass: 'Nouveau mot de passe',
   noresults: 'Aucun résultat pour',
   nospam: 'Pas de spam sur votre forum!',
   notexist: 'existe pas.',
   notify: 'Avertissez-moi des nouvelles versions',
   ok: 'ok',
   online: 'En ligne',
   post: 'Post',
   preview: 'Prévisualisation',
   progress: ['chargement...', 'continue de travailler...', 'et travailler...', 'abandonner'],
   reconnect: 'Reconnection...',
   removecat: 'Supprimer. Ce post n\'est pas supprimé',
   removepost: 'Supprimer ce post',
   reply: 'Répondre...',
   replybtn: 'Répondre',
   save: 'Sauvegarder modification(s)',
   saved: 'sauvegardé',
   search: 'Recherche',
   select: 'Selectionnez un forum',
   setup: 'Installez maintenant',
   showing: 'Présentation',
   slogan: 'Forums et commentaire ré-imaginé',
   spam: 'Spam',
   start: 'Quoi de neuf ?',
   step1: 'Nous vous avons envoyé un e-mail de confirmation. Votre email ne sera pas mis à jour avant d\'avoir terminé cette étape!
',
   step: 'Plus qu\'une étape',
   terms: 'J\'accepte les<a>termes de services</a>.',
   thanks: 'Merci!',
   uname_len: '6 caractères ou plus',
   uname_taken: 'Ce nom d\'utilisateur est déjà pris!',
   unametip: 'Ça ne pourra pas être changé après',
   undo: 'Annuler',
   unlike: 'Contrairement à',
   unspam: 'Pas de spam',
   unver1: 'Compte non vérifié',
   unver2: 'Veuillez regarder vos emails pour confirmer votre compte. Les utilisateurs vérifié peuvent voir Moots et recevoir des notifications par email <a>Envoyer un nouveau code de vérification...</a>',
   unver3: '<a>Envoyer un nouveau</a> code de vérification à:',
   unver4: "Envoyé. Regardez vos emails",
   unver: 'Non vérifié',
   unwall: 'tout cacher',
   unwatch: 'Cacher',
   upgrade2: 'Moot utilise WebSockets ou CORS pour la communication inter-domaines. Tous les navigateurs modernes, sauf Opera 11 et IE7 fonctionnent.',
   upgrade: 'Veuillez mettre à jour votre navigateur.',
   username_taken: 'Ce nom d\'utilisateur est déjà pris',
   watch: 'Regarder ce Moot',
   welcome1: 'Veuillez regarder vos emails pour compléter l\'enregistrement. Si vous n\'avez pas reçu d\'email d\'ici une minute ou deux, regardez dans le dossier "spam"',
   welcome2: 'Veuillez fournir un nom d\'utilisateur Moot',
   welcome: 'Bienvenue sur Moot!',
   you: 'Vous',

   // times
   now: 'à l\'instant',
   months: "Jan,Fev,Mar,Avr,Mai,Jui,Jul,Aoû,Sep,Oct,Nov,Dec",
   min: 'm',
   hour: 'h',
   day: 'j',
   week: 's'

}
