moot.language = {

  // the language code
  $code: 'fr',

  /* New stuff */
  no_notify: 'Disable all email notifications',
  watchall: 'Watch for all new threads',
  move: 'Move thread',
  moved: 'Thread moved',
  custom_path1: 'Custom path',
  custom_path: 'Enter custom path',
  invalid_path: 'Invalid custom path',
  from: 'From',
  to: 'To',

  retire: 'Retire',
  retire_title: 'Retire thread',
  retire_desc: 'Retired threads no longer get bumped to top in the feeds they appear in.',
  retired_desc: 'This thread is retired. New replies no longer bump it to the top of the feed.',
  is_retired: 'This thread has been retired',

  unretire: 'Unretire',
  unretire_title: 'Unretire thread',
  unretire_desc: 'This thread will be bumped to top in the feeds they appear in.',
  quote_help1: 'Select',
  quote_help2: 'to quote or share',

  trial_left: 'left of free trial.',
  after_trial: 'After the trial ends you can continue using Muut with the',
  free_plan: 'Free plan',
  reward: 'Referral reward',
  off33: 'Upgrade now and get 33% off all our paid plans!',
  spread: 'Spread the word!',
  invite: 'Invite a friend to start a Muut community and you’ll both get rewarded!',
  start_now: 'Start your own community now – it\'s free!',
  start_btn: 'Create',
  reserve: 'Reserve your forum name',
  free_acc: 'Free account',
  no_dialog: 'and remove this dialogue',
  click_change: 'Click to change',

  moderator: 'Moderator',
  mkadmin: 'Make administrator',
  mkmod: 'Make moderator',
  upgrade_mod: 'to make this user a moderator',
  upgrade_admin: 'to make this user administrator or moderator',

  my_profile: 'My profile',


  post_in: 'Publier',
  address_now: 'Merci! Votre adresse e-mail a bien été validée.',
  open_pw: 'Merci de cliquer sur le bouton ci-dessous pour ouvrir la boîte de dialogue vous permettant de changer votre mot de passe',
  non_anon: 'Vous devez vous connecter pour réaliser cette action',

  plan: 'Compte',
  trial: 'Commencez votre essai gratuit',

  is_private: "Cette communauté est privée",
  owner_msg: "Votre message à l'administrateur du forum... (Facultatif)",
  req_access: "Demander l'accès",
  req_sent: "Demande d'accès envoyée",
  or_join: "ou <a>S'inscrire</a> pour rejoindre la communauté.",
  save_with: "Economisez 20% sur l'abonnement annuel",
  rem_post: "Souhaitez-vous supprimer cette publication?",
  is_spam: "S'agit-il d'un spam?",

  channels: 'Canaux',
  ch_name: 'Nom du canal',
  ban:  'Bannir',
  banned:  'Banni',
  ban_acc: 'Compte banni',
  ban_msg: 'Vous êtes temporairement banni du forum.',
  days:  'Jours',
  forever: 'De manière permanente', // not sure - it depends on the context - alternatively : pour toujours, à jamais
  slogan:  'Animer des forums et commenter gratuitement avec Muut', // not sure // verbs > nouns

  add: '+ Add',
  addons: 'Add-ons',
  myaccount: "Mon compte",
  untitled: "Titre non défini",
  design: "Design",
  no_title: "Veuillez donner un titre",
  designer: "Designer",
  developer: "Developer",



  img_needed: "Veuillez télécharger une image",
  max: 'La taille maximale est de 4Mb',
  yes: 'Oui',
  upload: 'Télécharger des images',
  show: 'afficher',
  hide: 'masquer',
  invisible: 'Invisible',
  givebody: 'Le contenu ne peut pas être vide.',
  show_old: 'Afficher les premières réponses',
  show_more: 'Afficher plus de réponses',
  show_new: 'Afficher les dernières réponses',
  start: 'Créer un nouveau sujet...',
  error: 'Oups, une erreur s\'est produite. Copiez votre publication, actualisez la page puis réessayez. Désolé - nous allons régler ce problème !',
  body: 'Texte du contenu',
  admin: 'Administrateur',
  someone: 'Quelqu\'un',
  writing: 'est en train d\'écrire...',
  manage: 'Gérer',
  single: 'un seul mot',

  upgrade_link: 'Mettre à niveau',
  branding: 'Branding', // ?
  logo: 'Logo', // same as English
  css: 'Fichier CSS',
  fullview: 'Vue complète',

  username_fail: 'Utilisez des lettres, des chiffres ou des tirets',
  bold: 'en gras',
  italics: 'en italique',
  monospaced: 'mono-espacé',
  learn: 'En savoir plus...',
  settings: 'Paramètres',
  title: 'Title',
  link: 'link',
  avatar: 'Changer l\'avatar',

  all: 'Tous les posts', // or alternatively: All
  anon_1: 'anonyme',  // singular
  anon: 'anonymes',  // plural

  badforum: 'Forum invalide',
  c_acc1: 'Votre compte fonctionne maintenant sur tous les sites utilisant Muut',
  c_acc: 'Compte vérifié',
  c_email: 'Adresse e-mail mise à jour',
  cancel: 'Annuler',
  change: 'Changer',
  changepw: 'Changer le mot de passe',
  close: 'Fermer',
  collapse: 'Tout réduire',
  comm_count_1: 'commentaire',  // singular: "1 comment"
  comm_count_n: 'commentaires',  // plural: "3 comments"
  comment1: 'Soyez le premier à commenter...',
  comment: 'Commenter...',
  edit: 'modifier',
  email: 'E-mail',
  email_taken: 'Cette adresse e-mail est prise',
  emailtip: 'Votre adresse e-mail ne sera jamais partagée',
  enter: 'Ctrl + Entrée',
  expired1: 'Nous venons de vous en envoyer un nouveau. Veuillez vérifier vos e-mails.', // http://d.pr/i/1OEV
  expired: 'Ce lien a expiré',

  feed: 'Mon fil', // alternatives: My own, personal


  help2: 'publier',
  help3: 'citation',
  help5: 'code, langue auto-devinée',
  help6: 'code HTML',
  in_forum: 'dans',
  invalid: 'Valeur invalide',
  join: 'Rejoindre Muut',
  later: 'Plus tard...',
  less: 'moins',
  like: 'Aimer',
  likepost: 'Aimer ce post',
  loading: 'Chargement...',
  login: 'Se connecter',
  login1: 'Connectez-vous d\'abord',
  login_and: "Se connecter et",

  logout: 'Se déconnecter',
  mark: 'Offensif ou spam',
  mean: 'Vouliez-vous dire',
  name: 'Nom',
  nametip: 'Votre vrai nom, pour que les gens vous reconnaissent',
  newpass: 'Nouveau mot de passe',
  noresults: 'Aucun résultat pour',
  nospam: 'Aucun spam sur votre forum !',
  notexist: 'n\'existe pas.',
  ok: 'OK',
  online: 'En ligne',
  post: 'Publier',
  preview: 'Prévisualisation',
  progress: ['Chargement...', 'encore...', 'et encore...', 'abandon'],
  reconnect: 'Reconnexion...',
  removepost: 'Supprimer',
  reply: 'Répondre...',
  replybtn: 'Répondre',
  save: 'Enregistrer les modifications',
  saved: 'enregistré',
  search: 'Rechercher',
  select: 'Sélectionnez le forum',
  setup: 'Installer maintenant',
  showing: 'Montrant',
  spam: 'Spam',
  step1: 'Nous vous avons envoyé un e-mail de confirmation. Votre adresse e-mail ne sera pas mise à jour avant d\'avoir terminé cette étape !',
  step: 'Une dernière étape',
  terms: 'J\'accepte les <a>modalités du service</a>.',
  thanks: 'Merci !',
  uname_len: 'Tapez 4 caractères ou plus',
  uname_taken: 'Ce nom d\'utilisateur est pris !',
  unametip: 'Ceci ne pourra être changé par la suite',
  undo: 'Annuler',
  unlike: 'Ne plus aimer',
  unspam: 'Non spam',
  unver1: 'Compte non vérifié',
  unver2: 'Veuillez consulter vos e-mails pour vérifier votre compte.',
  unver3: 'Envoyer un nouveau code de vérification',
  unver4: "Envoyé. Veuillez vérifier votre boîte de réception.",
  unver: 'Non vérifié',
  unwall: 'ne plus surveiller les Moots',
  unwatch: 'Ne plus surveiller',
  upgrade2: 'Muut utilise les WebSockets ou CORS pour les communications cross-domain. Tous les navigateurs modernes à part Opera 11 et IE7 fonctionnent.',
  upgrade: 'Veuillez mettre à jour votre navigateur',
  username_taken: 'Ce nom d\'utilisateur est pris',
  watch: 'Surveiller les nouvelles réponses',
  welcome1: 'Veuillez vérifier vos e-mails pour finir votre inscription. Si vous ne recevez pas d\'e-mails dans une minute ou deux, vérifiez votre dossier "Spam".',
  welcome2: 'Veuillez fournir un nom d\'utilisateur Muut',
  welcome: 'Bienvenue sur Muut',
  you: 'Vous',

  // times
  now: 'à l\'instant',
  months: "Jan,Fév,Mar,Avr,Mai,Juin,Juil,Aoû,Sep,Oct,Nov,Déc",
  min: 'm',
  hour: 'h',
  day: 'j',
  week: 's'

}
