moot.language = {

  // the language code
  $code: 'he',


  /** NEW **/
  no_notify: 'Disable all email notifications',
  watchall: 'Watch for all new threads',
  move: 'Move thread',
  moved: 'Thread moved',
  custom_path1: 'Custom path',
  custom_path: 'Enter custom path',
  invalid_path: 'Invalid custom path',
  from: 'From',
  to: 'To',
  show_preview: 'Show preview',

  retire: 'Retire',
  retire_title: 'Retire thread',
  retire_desc: 'Retired threads no longer get bumped to top in the feeds they appear in.',
  retired_desc: 'This thread is retired. New replies no longer bump it to the top of the feed.',
  is_retired: 'This thread has been retired',

  unretire: 'Unretire',
  unretire_title: 'Unretire thread',
  unretire_desc: 'This thread will be bumped to top in the feeds they appear in.',
  quote_help1: 'Select',
  quote_help2: 'to quote or share',

  trial_left: 'left of free trial.',
  after_trial: 'After the trial ends you can continue using Muut with the',
  free_plan: 'Free plan',
  reward: 'Referral reward',
  off33: 'Upgrade now and get 33% off all our paid plans!',
  spread: 'Spread the word!',
  invite: 'Invite a friend to start a Muut community and you’ll both get rewarded!',
  start_now: 'Start your own community now – it\'s free!',
  start_btn: 'Create',
  reserve: 'Reserve your forum name',
  free_acc: 'Free account',
  no_dialog: 'and remove this dialogue',
  click_change: 'Click to change',

  moderator: 'Moderator',
  mkadmin: 'Make administrator',
  mkmod: 'Make moderator',
  upgrade_mod: 'to make this user a moderator',
  upgrade_admin: 'to make this user administrator or moderator',

  my_profile: 'My profile',
  post_in: 'Post in',
  address_now: 'Thank you! Your email address has been confirmed.',
  open_pw: 'אנא לחץ על הכפתור למטה כדי לפתוח את הדו שיח שינוי סיסמא',
  non_anon: 'את/ה צריך להיות מחובר/ת כדי לבצע פעולה זו',

  plan: 'תכנית',
  trial: 'התחלת נסיון חינם',

  is_private: "קהילה זו היא פרטית",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "בקשת גישה",
  req_sent: "בקשת גישה נשלחה",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "להסיר הפרסום?",
  is_spam: "הפרסום הוא זבל?",

  channels: 'ערוצים',
  ch_name: 'שם ערוץ',
  ban:  'הרחק משתמש',
  banned:  'מורחק',
  ban_acc: 'חשבון מורחק',
  ban_msg: 'את/ה מורחק/ת באופן זמני מהפורום הזה.',
  days:  'ימים',
  forever: 'לנצח',
  slogan:  'Free forums and commenting by Muut',

  add: '+ הוספה',
  addons: 'תוספים',
  myaccount: "החשבון שלי",
  untitled: "ללא כותרת",
  design: "עיצוב",
  no_title: "יש לתת כותרת",
  designer: "מעצב/ת",
  developer: "מפתח/ת",



  img_needed: "נא להעלות קובץ תמונה.",
  max: 'גודל תמונה מרבי הוא 4Mb',
  yes: 'כן',
  upload: 'העלאת תמונות',
  show: 'הצג',
  hide: 'הסתר',
  invisible: 'בלתי נראה',
  givebody: 'הגוף אינו יכול להיות ריק.',
  show_old: 'הצגת התגובות הישנות ביותר',
  show_more: 'הצגת תגובות נוספות',
  show_new: 'הצגצ התגובות החדשות ביותר',
  start: 'התחלת נושא חדש...',
  error: 'אופס, טעות. אנא העתק את ההודעה אל הלוח, טען מחדש ונסה שוב. מצטערים - אנחנו נתקן את זה!',
  body: 'מלל',
  admin: 'מנהל/ת',
  someone: 'מישהו/י',
  writing: 'כותב/ת...',
  manage: 'ניהול',
  fullview: 'תצוגה מלאה',
  title: 'כותרת',
  link: 'קישור',
  avatar: 'שינוי דמות אישית',
  upgrade_link: 'שדרוג',
  branding: 'מיתוג',
  logo: 'סמל',
  css: 'קובץ CSS',
  single: 'מילה אחת',




  username_fail: 'ניתן להשתמש באותיות, מספרים או מקף',
  bold: 'מודגש',
  italics: 'בכתב נטוי',
  monospaced: 'תו ברוחב קבוע',

  learn: 'מידע נוסף...',
  settings: 'הגדרות',


  all: 'כל הדיונים ',
  anon_1: 'אנונימי',  // singular
  anon: 'אנונימיים',  // plural

  badforum: 'פורום שגוי',
  c_acc1: 'כעת חשבון המשתמש שלך מוכן לעבודה עם כל אתרי Muut',
  c_acc: 'חשבון המשתמש אומת בהצלחה',
  c_email: 'כתובת הדואר האלקטרוני עודכנה',
  cancel: 'ביטול',
  change: 'שינוי',
  changepw: 'שינוי סיסמה',
  close: 'סגירה',
  collapse: 'צמצום הכל',
  comm_count_1: 'תגובה',  // singular: "1 comment"
  comm_count_n: 'תגובות',  // plural: "3 comments"
  comment1: 'התגובה הראשונה יכולה להיות שלך...',
  comment: 'תגובה...',
  edit: 'עריכה',
  email: 'דואר אלקטרוני',
  email_taken: 'כתובת הדואר האלקטרוני תפוסה',
  emailtip: 'כתובת הדואר שלך לא תפורסם',
  enter: 'ctrl + enter',
  expired1: 'שלחנו לך קישור חדש. נא לבדוק את תיבת הדואר האלקטרוני.', // http://d.pr/i/1OEV
  expired: 'הקישור לעמוד זה אינו תקף',

  feed: 'דף הבית שלי ', // alternatives: My own, personal


  help2: 'בכדי לשלוח',
  help3: 'ציטוט טקסט',
  help5: 'קוד, השפה תזוהה באופן אוטומטי',
  help6: 'קוד HTML',
  in_forum: 'בפורום',
  invalid: 'ערך בלתי חוקי',
  join: 'הרשמה ל-Muut',
  later: 'מאוחר יותר...',
  less: 'פחות',
  like: 'אהבתי',
  likepost: 'אהבתי את הפוסט הזה',
  loading: 'טוען...',
  login: 'כניסה',
  login1: 'נא להתחבר קודם',
  login_and: "התחבר ואז",

  logout: 'יציאה',
  mark: 'ספאם או תוכן בלתי הולם',
  mean: 'האם בכוונתך',
  name: 'שם תצוגה',
  nametip: 'שמך האמיתי, כדי שאנשים יזהו אותך',
  newpass: 'סיסמה חדשה',
  noresults: 'אין תוצאות עבור',
  nospam: 'אין ספאם בפורום שלך!',
  notexist: 'לא קיים.',
  ok: 'אישור',
  online: 'מחוברים ',
  post: 'שלח',
  preview: 'תצוגה מקדימה',
  progress: ['טוען...', 'עדיין עובד...', 'ועובד...', 'ויתרנו'],
  reconnect: 'מתחבר מחדש...',
  removepost: 'עריכה או הסרה',
  reply: 'תגובה...',
  replybtn: 'שליחת תגובה',
  save: 'שמירת שינויים',
  saved: 'נשמר',
  search: 'חיפוש',
  select: 'בחירת פורום',
  setup: 'להתחיל עכשיו',
  showing: 'מציג',
  spam: 'ספאם',
  step1: 'שלחנו אליך הודעת אישור. כתובת הדואר לא תשתנה עד להשלמת השלב הזה!',
  step: 'עוד שלב אחד',
  terms: 'קראתי והסכמתי <a>לתנאי השימוש</a>.',
  thanks: 'תודה!',
  uname_len: 'נא להזין 4 תווים או יותר',
  uname_taken: 'שם המשתמש תפוס!',
  unametip: 'לא ניתן לשנות בשלב מאוחר יותר',
  undo: 'ביטול',
  unlike: 'לא אהבתי',
  unspam: 'ביטול סימון ספאם',
  unver1: 'חשבון לא מאומת',
  unver2: 'נא לבדוק את תיבת הדואר האלקטרוני על מנת לאמת את החשבון.',
  unver3: 'שלח שוב את קוד האימות',
  unver4: "נשלח. נא לבדוק את תיבת הדואר האלקטרוני.",
  unver: 'לא מאומת',
  unwall: 'ביטול מעקב מכל הדיונים',
  unwatch: 'ביטול מעקב',
  upgrade2: 'Muut משתמש ב-WebSockets ו-CORS לצורך ההתחברות לשירות. כל דפדפן אינטרנט עדכני למעט Opera 11 ו-IE7 צריך לספק את העבודה.',
  upgrade: 'יש צורך בעדכון דפדפן האינטרנט שלך',
  username_taken: 'שם המשתמש תפוס',
  watch: 'עקוב אחרי הדיון',
  welcome1: 'נא לבדוק את תיבת הדואר האלקטרוני על מנת להשלים את ההרשמה. אם אינך מקבל\ת את הוראות האיפוס בתוך דקה או שתיים, יש לבדוק את תיבת דואר הזבל.',
  welcome2: 'נא הזן את שם המשתמש שלך ב-Muut',
  welcome: 'ברוכים הבאים ל-Muut',
  you: 'אתה',

  // times
  now: 'ממש עכשיו',
  months: "ינואר,פברואר,מרץ,אפריל,מאי,יוני,יולי,אוגוסט,ספטמבר,אוקטובר,נובמבר,דצמבר",
  min: ' דקות',
  hour: ' שעות',
  day: ' ימים',
  week: ' שבועות'

}
