moot.language = {

  // the language code
  $code: 'he',


  /** NEW **/
  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spam?",

  channels: 'Channels',
  ch_name: 'Channel name',
  ban:  'Ban user',
  banned:  'Banned',
  ban_acc: 'Banned account',
  ban_msg: 'You are temporarily banned from posting on this forum.',
  days:  'Days',
  forever: 'Forever',
  slogan:  'Free forums and commenting by Muut',

  add: '+ Add',
  addons: 'Add-ons',
  myaccount: "My account",
  untitled: "Untitled",
  design: "Design",
  no_title: "Title must be given",
  designer: "Designer",
  developer: "Developer",



  img_needed: "Please upload an image file",
  max: 'Maximum image size is 4Mb',
  yes: 'Yes',
  upload: 'Upload images',
  show: 'show',
  hide: 'hide',
  invisible: 'Invisible',
  givebody: 'Body cannot be empty.',
  show_old: 'Show oldest replies',
  show_more: 'Show more replies',
  show_new: 'Show newest replies',
  start: 'Start a new topic...',
  error: 'Oops, an error. Please copy the post to clipboard, reload and try again. Sorry – we will fix this!',
  body: 'Body text',
  admin: 'Admin',
  someone: 'Someone',
  writing: 'is writing...',
  basic: 'Basic (free)',
  subs: 'Subscriptions',
  manage: 'Manage',
  fullview: 'Full view',
  title: 'Title',
  link: 'link',
  avatar: 'Change avatar',
  upgrade_link: 'Upgrade',
  branding: 'Branding',
  logo: 'Logo',
  title: 'Title',
  css: 'CSS file',
  single: 'single word',




  username_fail: 'ניתן להשתמש באותיות, מספרים או מקף',
  bold: 'מודגש',
  italics: 'בכתב נטוי',
  monospaced: 'תו ברוחב קבוע',

  learn: 'מידע נוסף...',
  settings: 'הגדרות',


  all: 'כל הדיונים ',
  anon_1: 'אנונימי',  // singular
  anon: 'אנונימיים',  // plural

  badforum: 'פורום שגוי',
  c_acc1: 'כעת חשבון המשתמש שלך מוכן לעבודה עם כל אתרי Muut',
  c_acc: 'חשבון המשתמש אומת בהצלחה',
  c_email: 'כתובת הדואר האלקטרוני עודכנה',
  cancel: 'ביטול',
  change: 'שינוי',
  changepw: 'שינוי סיסמה',
  close: 'סגירה',
  collapse: 'צמצום הכל',
  comm_count_1: 'תגובה',  // singular: "1 comment"
  comm_count_n: 'תגובות',  // plural: "3 comments"
  comment1: 'התגובה הראשונה יכולה להיות שלך...',
  comment: 'תגובה...',
  edit: 'עריכה',
  email: 'דואר אלקטרוני',
  email_taken: 'כתובת הדואר האלקטרוני תפוסה',
  emailtip: 'כתובת הדואר שלך לא תפורסם',
  enter: 'ctrl + enter',
  expired1: 'שלחנו לך קישור חדש. נא לבדוק את תיבת הדואר האלקטרוני.', // http://d.pr/i/1OEV
  expired: 'הקישור לעמוד זה אינו תקף',

  feed: 'דף הבית שלי ', // alternatives: My own, personal


  help2: 'בכדי לשלוח',
  help3: 'ציטוט טקסט',
  help5: 'קוד, השפה תזוהה באופן אוטומטי',
  help6: 'קוד HTML',
  in_forum: 'בפורום',
  invalid: 'ערך בלתי חוקי',
  join: 'הרשמה ל-Muut',
  later: 'מאוחר יותר...',
  less: 'פחות',
  like: 'אהבתי',
  likepost: 'אהבתי את הפוסט הזה',
  loading: 'טוען...',
  login: 'כניסה',
  login1: 'נא להתחבר קודם',
  login_and: "התחבר ואז",

  logout: 'יציאה',
  mark: 'ספאם או תוכן בלתי הולם',
  mean: 'האם בכוונתך',
  name: 'שם תצוגה',
  nametip: 'שמך האמיתי, כדי שאנשים יזהו אותך',
  newpass: 'סיסמה חדשה',
  noresults: 'אין תוצאות עבור',
  nospam: 'אין ספאם בפורום שלך!',
  notexist: 'לא קיים.',
  notify: 'הודע לי על גרסאות חדשות של Muut',
  ok: 'אישור',
  online: 'מחוברים ',
  post: 'שלח',
  preview: 'תצוגה מקדימה',
  progress: ['טוען...', 'עדיין עובד...', 'ועובד...', 'ויתרנו'],
  reconnect: 'מתחבר מחדש...',
  removepost: 'עריכה או הסרה',
  reply: 'תגובה...',
  replybtn: 'שליחת תגובה',
  save: 'שמירת שינויים',
  saved: 'נשמר',
  search: 'חיפוש',
  select: 'בחירת פורום',
  setup: 'להתחיל עכשיו',
  showing: 'מציג',
  spam: 'ספאם',
  step1: 'שלחנו אליך הודעת אישור. כתובת הדואר לא תשתנה עד להשלמת השלב הזה!',
  step: 'עוד שלב אחד',
  terms: 'קראתי והסכמתי <a>לתנאי השימוש</a>.',
  thanks: 'תודה!',
  uname_len: 'נא להזין 6 תווים או יותר',
  uname_taken: 'שם המשתמש תפוס!',
  unametip: 'לא ניתן לשנות בשלב מאוחר יותר',
  undo: 'ביטול',
  unlike: 'לא אהבתי',
  unspam: 'ביטול סימון ספאם',
  unver1: 'חשבון לא מאומת',
  unver2: 'נא לבדוק את תיבת הדואר האלקטרוני על מנת לאמת את החשבון. משתמשים מאומתים יכולים להירשם לעדכונים ולקבל התראות בדואר. <a>שלח שוב את קוד האימות...</a>',
  unver3: '<a>שלח</a> קוד אישור חדש ל:',
  unver4: "נשלח. נא לבדוק את תיבת הדואר האלקטרוני.",
  unver: 'לא מאומת',
  unwall: 'ביטול מעקב מכל הדיונים',
  unwatch: 'ביטול מעקב',
  upgrade2: 'Muut משתמש ב-WebSockets ו-CORS לצורך ההתחברות לשירות. כל דפדפן אינטרנט עדכני למעט Opera 11 ו-IE7 צריך לספק את העבודה.',
  upgrade: 'יש צורך בעדכון דפדפן האינטרנט שלך',
  username_taken: 'שם המשתמש תפוס',
  watch: 'עקוב אחרי הדיון',
  welcome1: 'נא לבדוק את תיבת הדואר האלקטרוני על מנת להשלים את ההרשמה. אם אינך מקבל\ת את הוראות האיפוס בתוך דקה או שתיים, יש לבדוק את תיבת דואר הזבל.',
  welcome2: 'נא הזן את שם המשתמש שלך ב-Muut',
  welcome: 'ברוכים הבאים ל-Muut',
  you: 'אתה',

  // times
  now: 'ממש עכשיו',
  months: "ינואר,פברואר,מרץ,אפריל,מאי,יוני,יולי,אוגוסט,ספטמבר,אוקטובר,נובמבר,דצמבר",
  min: ' דקות',
  hour: ' שעות',
  day: ' ימים',
  week: ' שבועות'

}