moot.language = {

   // the language code
   $code: 'hu',


   all: 'Összes', // or alternatively: All
   anon: 'névtelen',
   badforum: 'Érvénytelen fórum',
   c_acc1: 'A profilod mostantól az összes Moot oldalon érvényes',
   c_acc: 'Profil megerősítve',
   c_email: 'Email cím frissítve',
   cancel: 'Mégsem',
   change: 'Változtat',
   changed: 'Megváltoztatva!',
   changepw: 'Jelszó változtatás',
   close: 'Bezár',
   collapse: 'Mindet becsuk',
   comm_count_1: 'hozzászólás',
   comm_count_n: 'hozzászólás',
   comment1: 'Légy Te az első hozzászóló...',
   comment: 'Hozzászólás...',
   edit: 'szerkeszt',
   email: 'Email',
   email_taken: 'Ez az email cím már foglalt',
   emailtip: 'Az email címed sosem osztjuk meg',
   enter: 'ctrl + enter',
   expired1: 'Kiküldtünk egy újat. Kérlek, ellenőrizd az email címed.',
   expired: 'A link érvényessége lejárt',

   feed: 'Saját', // alternatives: My own, personal

   forumname: 'Fórum név',
   forums: 'Fórumok',
   help1: 'Az első sor a cím',
   help2: 'bejegyzés',
   help3: 'idézett szöveg',
   help4: 'második sor',
   help5: 'kód, nyelv',
   help6: 'html kód',
   invalid: 'Érvénytelen érték',
   join: 'Moot - Csatlakozz!',
   later: 'Később...',
   less: 'kevesebb',
   like: 'Tetszik',
   likepost: 'Tetszik a bejegyzés',
   loading: 'Töltés...',
   login: 'Belépés',
   login1: 'Először lépj be',
   login_and: "Belépés és",
   loginwith: 'Lépj be',
   login_or: 'vagy',

   logout: 'Kilépés',
   mark: 'Sértő vagy spam',
   mean: 'Erre gondolsz',
   name: 'Megjelenítendő név',
   nametip: 'Az igazi neved, hogy az emberek könnyebben felismerjenek',
   newcat: 'Új kategória',
   newpass: 'Új jelszó',
   noresults: 'Nincs találat',
   nospam: 'Nincs spam a fórumodon!',
   notexist: 'nem létezik.',
   notify: 'Értesíts az új fejlesztésekről',
   ok: 'ok',
   online: 'Online',
   post: 'Bejegyzés',
   preview: 'Előnézet',
   progress: ['töltés...', 'még dolgozunk...', 'és dolgozunk...', 'feladtuk'],
   reconnect: 'Újracsatlakozás...',
   removecat: 'Eltávolítás. A bejegyzés nem lesz eltávolítva',
   removepost: 'Bejegyzés eltávolítása',
   reply: 'Válasz...',
   replybtn: 'Válasz',
   save: 'Változások mentése',
   saved: 'mentve',
   search: 'Keresés',
   select: 'Válassz fórumot',
   setup: 'Beállítás',
   showing: 'Mutasd',
   slogan: 'Fórumok és kommentek újraalkotva',
   spam: 'Spam',
   start: 'Mi a helyzet?',
   step1: 'Elküldtünk egy megerősítő emailt. Az email címed nem frissül mielőtt el nem végzed ezt a lépést!',
   step: 'Még egy lépés',
   terms: 'Elfogadom a <a>Használati feltételeket</a>.',
   thanks: 'Köszönjük!',
   uname_len: 'Adj meg legalább 6 karaktert',
   uname_taken: 'A felhasználónév foglalt!',
   unametip: 'Ezt később nem változtathatod meg',
   undo: 'Vissza',
   unlike: 'Mégsem tetszik',
   unspam: 'Mégsem spam',
   unver1: 'Nem megerősített profil',
   unver2: 'Kérlek, ellenőrizd az email fiókod, hogy megerősítsd a profilod. Az azonosított felhasználók követhetik a mootokat és emailben értesítéseket is kaphatnak. <a>Küldj egy új megerősítő kódot...</a>',
   unver3: '<a>Küldj egy új</a> megerősítő kódot ide:',
   unver4: "Elküldve. Kérlek, ellenőrizd az email fiókod.",
   unver: 'Ellenőrizetlen',
   unwall: 'Összes megtekintés visszavonása',
   unwatch: 'Megtekintés visszavonása',
   upgrade2: 'A Moot WebSockets vagy CORS szabványt használ a kereszt domain kommunikációban. Az összes modern böngészővel működik, kivéve az Opera 11 és IE7.',
   upgrade: 'Kérlek, frissítsd a böngésződ',
   username_taken: 'A felhasználónév foglalt',
   watch: 'Figyeld ezt a mootot',
   welcome1: 'Kérlek, ellenőrizd az email fiókod, hogy befejezd a regisztrációt. Ha nem kapod meg az emailt 1-2 percen belül, ellenőrizd a spam fiókod.',
   welcome2: 'Kérlek, adj meg egy Moot felhasználónevet!',
   welcome: 'Üdvözlünk a Moot oldalán!',
   you: 'Te',

   // times
   days: 'napja',
   hour: '1 órája',
   hours: 'órája',
   minute: '1 perce',
   minutes: 'perce',
   now: 'épp most',
   months: 'hónapja',
   week: 'egy hete',
   weeks: 'hete',
   yesterday: 'Tegnap'

}
