
moot.language = {

  // the language code
  $code: 'hu',

  /* New stuff */
  no_notify: 'Disable all email notifications',
  watchall: 'Watch for all new posts',
  move: 'Move thread',
  moved: 'Thread moved',
  custom_path1: 'Custom path',
  custom_path: 'Enter custom path',
  invalid_path: 'Invalid custom path',
  from: 'From',
  to: 'To',

  retire: 'Retire',
  retire_title: 'Retire thread',
  retire_desc: 'Retired threads no longer get bumped to top in the feeds they appear in.',
  retired_desc: 'This thread is retired. New replies no longer bump it to the top of the feed.',
  is_retired: 'This thread has been retired',

  unretire: 'Unretire',
  unretire_title: 'Unretire thread',
  unretire_desc: 'This thread will be bumped to top in the feeds they appear in.',
  quote_help1: 'Select',
  quote_help2: 'to quote or share',

  trial_left: 'left of free trial.',
  after_trial: 'After the trial ends you can continue using Muut with the',
  free_plan: 'Free plan',
  reward: 'Referral reward',
  off33: 'Upgrade now and get 33% off all our paid plans!',
  spread: 'Spread the word!',
  invite: 'Invite a friend to start a Muut community and you’ll both get rewarded!',
  start_now: 'Start your own community now – it\'s free!',
  start_btn: 'Create',
  reserve: 'Reserve your forum name',
  free_acc: 'Free account',
  no_dialog: 'and remove this dialogue',
  click_change: 'Click to change',

  moderator: 'Moderator',
  mkadmin: 'Make administrator',
  mkmod: 'Make moderator',
  upgrade_mod: 'to make this user a moderator',
  upgrade_admin: 'to make this user administrator or moderator',

  my_profile: 'My profile',
  post_in: 'Post in',
  address_now: 'Thank you! Your email address has been confirmed.',
  open_pw: 'Please hit the button below to open a password change dialog',
  non_anon: 'You need to be logged in to perform this action',

  plan: 'Plan',
  trial: 'Start free trial',

  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spam?",

  channels: 'Channels',
  ch_name: 'Channel name',
  ban:  'Ban user',
  banned:  'Banned',
  ban_acc: 'Banned account',
  ban_msg: 'You are temporarily banned from posting on this forum.',
  days:  'Days',
  forever: 'Forever',
  slogan:  'Free forums and commenting by Muut',

  add: '+ Add',
  addons: 'Add-ons',
  myaccount: "Account",
  untitled: "Untitled",
  design: "Design",
  no_title: "Title must be given",
  designer: "Designer",
  developer: "Developer",



  img_needed: "Please upload an image file",
  max: 'Maximum image size is 4Mb',
  yes: 'Yes',
  upload: 'Upload images',
  show: 'show',
  hide: 'hide',
  invisible: 'Invisible',
  givebody: 'Body cannot be empty.',
  show_old: 'Show oldest replies',
  show_more: 'Show more replies',
  show_new: 'Show newest replies',
  start: 'Start a new topic...',
  error: 'Oops, an error. Please copy the post to clipboard, reload and try again. Sorry – we will fix this!',
  body: 'Body text',
  admin: 'Admin',
  someone: 'Someone',
  writing: 'is writing...',
  manage: 'Manage',
  fullview: 'Full view',
  title: 'Title',
  link: 'link',
  avatar: 'Change avatar',
  upgrade_link: 'Upgrade',
  branding: 'Branding',
  logo: 'Logo',
  css: 'CSS file',
  single: 'single word',


  /* End new stuff */


  username_fail: 'Használj betűket, számokat vagy kötőjeleket',
  bold: 'félkövér',
  italics: 'dőlt',
  monospaced: 'szélességű',
  learn: 'Tudj meg többet...',
  settings: 'Beállítások',


  all: 'Összes', // or alternatively: All
  anon_1: 'vendég',
  anon: 'vendég',
  badforum: 'Érvénytelen fórum',
  c_acc1: 'A profilod mostantól az összes Muut oldalon érvényes',
  c_acc: 'Profil megerősítve',
  c_email: 'Email cím frissítve',
  cancel: 'Mégsem',
  change: 'Változtat',

  changepw: 'Jelszó változtatás',
  close: 'Bezár',
  collapse: 'Mindet becsuk',
  comm_count_1: 'hozzászólás',
  comm_count_n: 'hozzászólás',
  comment1: 'Légy Te az első hozzászóló...',
  comment: 'Hozzászólás...',
  edit: 'szerkeszt',
  email: 'Email',
  email_taken: 'Ez az email cím már foglalt',
  emailtip: 'Az email címed sosem osztjuk meg',
  enter: 'ctrl + enter',
  expired1: 'Kiküldtünk egy újat. Kérünk, ellenőrizd az email címed.',
  expired: 'A link érvényessége lejárt',

  feed: 'Saját', // alternatives: My own, personal


  help2: 'bejegyzés',
  help3: 'idézett szöveg',
  help4: 'második sor',
  help5: 'kód, nyelv',
  help6: 'html kód',
  in_forum: '',
  invalid: 'Érvénytelen érték',
  join: 'Muut - Csatlakozom!',
  later: 'Később...',
  less: 'kevesebb',
  like: 'Tetszik',
  likepost: 'Tetszik a bejegyzés',
  loading: 'Töltés...',
  login: 'Belépés',
  login1: 'Először lépj be',
  login_and: 'Belépés és',
  login_or: 'vagy',

  logout: 'Kilépés',
  mark: 'Sértő vagy spam',
  mean: 'Erre gondolsz',
  name: 'Megjelenítendő név',
  nametip: 'Az igazi neved, hogy az emberek könnyebben felismerjenek',
  newpass: 'Új jelszó',
  noresults: 'Nincs találat',
  nospam: 'Nincs spam a fórumodon!',
  notexist: 'nem létezik.',
  ok: 'ok',
  online: 'Online',
  post: 'Bejegyzés',
  preview: 'Előnézet',
  progress: ['töltés...', 'még dolgozunk...', 'és dolgozunk...', 'feladtuk'],
  reconnect: 'Újracsatlakozás...',
  removepost: 'Bejegyzés eltávolítása',
  reply: 'Válasz...',
  replybtn: 'Válasz',
  save: 'Változások mentése',
  saved: 'Mentve',
  search: 'Keresés',
  select: 'Válassz fórumot',
  setup: 'Beállítás',
  showing: 'Mutasd',
  spam: 'Spam',
  step1: 'Elküldtünk egy megerősítő emailt. Az email címed nem frissül mielőtt el nem végzed ezt a lépést!',
  step: 'Még egy lépés',
  terms: 'Elfogadom a <a>Használati feltételeket</a>.',
  thanks: 'Köszönjük!',
  uname_len: 'Adj meg legalább 4 karaktert',
  uname_taken: 'A felhasználónév foglalt!',
  unametip: 'Ezt később nem változtathatod meg',
  undo: 'Vissza',
  unlike: 'Mégsem tetszik',
  unspam: 'Mégsem spam',
  unver1: 'Nem megerősített profil',
  unver2: 'Kérünk, ellenőrizd az email fiókod, hogy megerősítsd a profilod.',
  unver3: 'Küldj egy új megerősítő kódot',
  unver4: 'Elküldve. Kérünk, ellenőrizd az email fiókod.',
  unver: 'Ellenőrizetlen',
  unwall: 'Összes megtekintés visszavonása',
  unwatch: 'Megtekintés visszavonása',
  upgrade2: 'A Muut WebSockets vagy CORS szabványt használ a kereszt domain kommunikációban. Az összes modern böngészővel működik, kivéve az Opera 11 és IE7.',
  upgrade: 'Kérünk, frissítsd a böngésződ',
  username_taken: 'A felhasználónév foglalt',
  watch: 'Figyeld ezt a mootot',
  welcome1: 'Kérünk, ellenőrizd az email fiókod, hogy befejezd a regisztrációt. Ha nem kapod meg az emailt 1-2 percen belül, ellenőrizd a spam fiókod.',
  welcome2: 'Kérünk, adj meg egy Muut felhasználónevet!',
  welcome: 'Üdvözlünk a Muut oldalán',
  you: 'Te',

  // times
  days: 'napja',
  hour: 'órája',
  hours: 'órája',
  minute: 'perce',
  minutes: 'perce',
  now: 'épp most',

  week: 'hete',
  weeks: 'hete',
  yesterday: 'Tegnap',

  inpage: 'Itt:',
  anon_1: 'vendég', // singular

  months: 'Jan,Feb,Már,Ápr,Máj,Jún,Júl,Aug,Szep,Okt,Nov,Dec',
  min: 'p',
  hour: 'ó',
  day: 'n',
  week: 'h'

}
