moot.language = {

   // the language code
   $code: 'en',


   all: 'Semua', // or alternatively: All
   anon: 'anonnim',
   badforum: 'Forum tidak valid',
   c_acc1: 'Akun Anda sekarang bisa digunakan pada semua situs yang menggunakan Moot',
   c_acc: 'Akun terkonfirmasi',
   c_email: 'Alamat Email diperbarui',
   cancel: 'Batal',
   change: 'Ganti',
   changepw: 'Ganti sandi',
   close: 'Tutup',
   collapse: 'Tutup semua',
   comm_count_1: 'komentar',
   comm_count_n: 'komentar',
   comment1: 'Menjadi komentator pertama...',
   comment: 'Komentar...',
   edit: 'edit',
   email: 'Email',
   email_taken: 'Email ini sudah dipakai',
   emailtip: 'Email Anda tidak akan pernah berikan ke pihak lain',
   enter: 'ctrl + enter',
   expired1: 'Kami telah mengirimkan yang baru. Silakan periksa email Anda.',
   expired: 'Tautan ini telah kadaluwarsa',

   feed: 'Pribadi', // alternatives: My own, personal

   forumname: 'Nama Forum',
   forums: 'Forum',
   help1: 'Baris pertama adalah judul',
   help2: 'pos',
   help3: 'teks kutipan',
   help4: 'baris kedua',
   help5: 'kode, bahasa diprediksi',
   help6: 'kode html',
   in_forum: 'dalam',
   invalid: 'Nilai tidak valid',
   join: 'Gabung Moot',
   later: 'Nanti...',
   less: 'kurang',
   like: 'suka',
   likepost: 'Suka pos ini',
   loading: 'Memuat...',
   login: 'Masuk',
   login1: 'Masuk terlebih dahulu',
   login_and: "Masuk dan",
   login_or: 'atau',

   logout: 'Keluar',
   mark: 'Ofensif atau spam',
   mean: 'Maksud anda',
   name: 'Tampilkan nama',
   nametip: 'Nama asli, supaya pengguna lain bisa mengenal anda',
   newcat: 'Kategori baru',
   newpass: 'Sandi baru',
   noresults: 'Tidak ada hasil untuk',
   nospam: 'Tidak ada spam di forum anda!',
   notexist: 'tidak eksis.',
   notify: 'Beritahu saya ketika ada versi baru',
   ok: 'ok',
   online: 'Online',
   post: 'Pos',
   preview: 'Pratinjau',
   progress: ['memuat...', 'masih diproses...', 'dan diproses...', 'menyerah'],
   reconnect: 'Menghubungi kembali...',
   removecat: 'Buang. Pos tidak dibuang',
   removepost: 'Buang pos ini',
   reply: 'Balas...',
   replybtn: 'Balas',
   save: 'Simpan perubahan',
   saved: 'tersimpan',
   search: 'Cari',
   select: 'Pilih forum',
   setup: 'Atur sekarang',
   showing: 'Menampilkan',
   slogan: 'Forum dan komentar di-definisikan ulang',
   spam: 'Spam',
   start: 'Ada apa?',
   step1: 'Kami telah mengirim email konfirmasi. Email anda tidak diperbarui sebelum anda menyelesaikan langkah ini!',
   step: 'Satu langkah lagi',
   terms: 'Saya setuju dengan <a>syarat dan ketentuan</a>.',
   thanks: 'Terima Kasih!',
   uname_len: 'Ketik 6 karakter atau lebih',
   uname_taken: 'Nama pengguna ini sudah dipakai!',
   unametip: 'Ini tidak bisa diganti lagi',
   undo: 'Kembalikan',
   unlike: 'Tidak sukai',
   unspam: 'Bukan spam',
   unver1: 'Akun belum terverifikasi',
   unver2: 'Silakan periksa email anda untuk melakukan verifikasi. Pengguna terverifikasi bisa mengamati perbincangan dan menerima email notifikasi. <a>Kirim kode verifikasi baru...</a>',
   unver3: '<a>Kirim kode</a> verifikasi baru ke:',
   unver4: "Terkirim. Periksa kotak surat anda.",
   unver: 'Tidak terverifikasi',
   unwall: 'tidak mengamati semua',
   unwatch: 'Tidak mengamati',
   upgrade2: 'Moot menggunakan WebSockets atau CORS untuk komunikasi silang domain. Semua peramban modern telah mendukungnya kecuali Opera 11 dan IE7.',
   upgrade: 'Silakan perbarui peramban anda',
   username_taken: 'nama pengguna ini sudah dipakai',
   watch: 'Amati perbincangan ini',
   welcome1: 'Silakan periksa email anda untuk menyelesaikan pendaftaran. Jika anda tidak menerima email dalam satu atau dua menit, periksa kotak spam anda.',
   welcome2: 'Silakan masukkan nama pengguna untuk Moot',
   welcome: 'Selamat Datang di Moot',
   you: 'Anda',

   // times
   now: 'saat ini',
   months: "Jan,Feb,Mar,Apr,May,Jun,Jul,Agu,Sep,Okt,Nov,Des",
   min: 'm',
   hour: 'j',
   day: 'h',
   week: 'mg'

}
