moot.language = {

  // the language code
  $code: 'id',

  /* New stuff */
  my_profile: 'My profile',
  post_in: 'Post in',
  address_now: 'Thank you! Your email address has been confirmed.',
  open_pw: 'Please hit the button below to open a password change dialog',
  non_anon: 'You need to be logged in to perform this action',

  plan: 'Plan',
  trial: 'Start free trial',

  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spam?",

  channels: 'Channels',
  ch_name: 'Channel name',
  ban:  'Ban user',
  banned:  'Banned',
  ban_acc: 'Banned account',
  ban_msg: 'You are temporarily banned from posting on this forum.',
  days:  'Days',
  forever: 'Forever',
  slogan:  'Free forums and commenting by Muut',

  add: '+ Add',
  addons: 'Add-ons',
  myaccount: "My account",
  untitled: "Untitled",
  design: "Design",
  no_title: "Title must be given",
  designer: "Designer",
  developer: "Developer",



  img_needed: "Please upload an image file",
  max: 'Maximum image size is 4Mb',
  yes: 'Yes',
  upload: 'Upload images',
  show: 'show',
  hide: 'hide',
  invisible: 'Invisible',
  givebody: 'Body cannot be empty.',
  show_old: 'Show oldest replies',
  show_more: 'Show more replies',
  show_new: 'Show newest replies',
  start: 'Start a new topic...',
  error: 'Oops, an error. Please copy the post to clipboard, reload and try again. Sorry – we will fix this!',
  body: 'Body text',
  admin: 'Admin',
  someone: 'Someone',
  writing: 'is writing...',
  manage: 'Manage',
  fullview: 'Full view',
  title: 'Title',
  link: 'link',
  avatar: 'Change avatar',
  upgrade_link: 'Upgrade',
  branding: 'Branding',
  logo: 'Logo',
  css: 'CSS file',
  single: 'single word',
  /* End new stuff */

  username_fail: 'Gunakan huruf kecil, angka atau strip',
  bold: 'tebal',
  italics: 'miring',
  monospaced: 'monospace',
  learn: 'Pelajari...',
  settings: 'Setting',


  all: 'Semua', // or alternatively: All
  anon: 'anonim',
  badforum: 'Forum tidak valid',
  c_acc1: 'Akun Anda sekarang bisa digunakan pada semua situs yang menggunakan Muut',
  c_acc: 'Akun terkonfirmasi',
  c_email: 'Alamat Email diperbarui',
  cancel: 'Batal',
  change: 'Ganti',
  changepw: 'Ganti sandi',
  close: 'Tutup',
  collapse: 'Tutup semua',
  comm_count_1: 'komentar',
  comm_count_n: 'komentar',
  comment1: 'Menjadi komentator pertama...',
  comment: 'Komentar...',
  edit: 'edit',
  email: 'Email',
  email_taken: 'Email ini sudah dipakai',
  emailtip: 'Email Anda tidak akan pernah berikan ke pihak lain',
  enter: 'ctrl + enter',
  expired1: 'Kami telah mengirimkan yang baru. Silakan periksa email Anda.',
  expired: 'Tautan ini telah kadaluwarsa',

  feed: 'Pribadi', // alternatives: My own, personal


  help2: 'pos',
  help3: 'teks kutipan',
  help5: 'kode, bahasa diprediksi',
  help6: 'kode html',
  in_forum: 'dalam',
  invalid: 'Nilai tidak valid',
  join: 'Gabung Muut',
  later: 'Nanti...',
  less: 'kurang',
  like: 'suka',
  likepost: 'Suka pos ini',
  loading: 'Memuat...',
  login: 'Masuk',
  login1: 'Masuk terlebih dahulu',
  login_and: "Masuk dan",
  login_or: 'atau',

  logout: 'Keluar',
  mark: 'Ofensif atau spam',
  mean: 'Maksud anda',
  name: 'Tampilkan nama',
  nametip: 'Nama asli, supaya pengguna lain bisa mengenal anda',
  newpass: 'Sandi baru',
  noresults: 'Tidak ada hasil untuk',
  nospam: 'Tidak ada spam di forum anda!',
  notexist: 'tidak eksis.',
  ok: 'ok',
  online: 'Online',
  post: 'Pos',
  preview: 'Pratinjau',
  progress: ['memuat...', 'masih diproses...', 'dan diproses...', 'menyerah'],
  reconnect: 'Menghubungi kembali...',
  removepost: 'Buang pos ini',
  reply: 'Balas...',
  replybtn: 'Balas',
  save: 'Simpan perubahan',
  saved: 'tersimpan',
  search: 'Cari',
  select: 'Pilih forum',
  setup: 'Atur sekarang',
  showing: 'Menampilkan',
  spam: 'Spam',
  step1: 'Kami telah mengirim email konfirmasi. Email anda tidak diperbarui sebelum anda menyelesaikan langkah ini!',
  step: 'Satu langkah lagi',
  terms: 'Saya setuju dengan <a>syarat dan ketentuan</a>.',
  thanks: 'Terima Kasih!',
  uname_len: 'Ketik 4 karakter atau lebih',
  uname_taken: 'Nama pengguna ini sudah dipakai!',
  unametip: 'Ini tidak bisa diganti lagi',
  undo: 'Kembalikan',
  unlike: 'Tidak sukai',
  unspam: 'Bukan spam',
  unver1: 'Akun belum terverifikasi',
  unver2: 'Silakan periksa email anda untuk melakukan verifikasi.',
  unver3: 'Kirim kode verifikasi baru',
  unver4: "Terkirim. Periksa kotak surat anda.",
  unver: 'Tidak terverifikasi',
  unwall: 'tidak mengamati semua',
  unwatch: 'Tidak mengamati',
  upgrade2: 'Muut menggunakan WebSockets atau CORS untuk komunikasi silang domain. Semua peramban modern telah mendukungnya kecuali Opera 11 dan IE7.',
  upgrade: 'Silakan perbarui peramban anda',
  username_taken: 'nama pengguna ini sudah dipakai',
  watch: 'Amati perbincangan ini',
  welcome1: 'Silakan periksa email anda untuk menyelesaikan pendaftaran. Jika anda tidak menerima email dalam satu atau dua menit, periksa kotak spam anda.',
  welcome2: 'Silakan masukkan nama pengguna untuk Muut',
  welcome: 'Selamat Datang di Muut',
  you: 'Anda',

  // times
  now: 'saat ini',
  months: "Jan,Feb,Mar,Apr,May,Jun,Jul,Agu,Sep,Okt,Nov,Des",
  min: 'm',
  hour: 'j',
  day: 'h',
  week: 'mg'

}
