
var language = {

   join: 'Iscriviti',
   changed: 'Modificato!',

   login: 'Accedi',
   id: 'Email <em>o username</em>',
   password: 'Password',
   forgot: 'Dimenticato?',
   notify: 'Comunicatemi il rilascio di una nuova versione di Moot',
   auth_failed: 'Username o password errati',
   invalid: 'Valore non valido',
   terms: 'Accetto i <a>termini di servizio</a>.',
   minlength: 'Digitare {n} caratteri o più',
   required: 'Per favore compila questo campo',
   checking: 'Controllo...',
   username: 'Username',
   username_done: 'Questo non può essere modificato successivamente',
   username_fail: 'Usa lettere, numeri o trattini',
   username_taken: 'Username in uso con altro account',
   email: 'Email',
   email_tip: 'Il tuo indirizzo non viene mai condiviso con altri.',
   email_done: 'Ti invieremo una conferma',
   email_fail: 'Email non valida',
   email_taken: 'Email in uso con altro account',
   reset: 'Reset password',
   resetbtn: 'Invia instruzioni',
   sent: 'Abbiamo inviato istruzioni per la reimpostazione della password al tuo indirizzo email.',
   sent1: 'Se non ricevi questa email in uno o due minuti, controlla la tua cartella spam.',
   notfound: 'Impossibile trovare questo utente',
   invalidpw: 'Password non valida',
   passtip: 'almeno 6 lettere',
   oldpw: 'Vecchia password',
   newpw: 'Nuova password',
   changepw: 'Cambia password'
};