moot.language = {

  // the language code
  $code: 'it',

  // New stuff
  no_notify: 'Disable all email notifications',
  watchall: 'Watch for all new threads',
  move: 'Move thread',
  moved: 'Thread moved',
  custom_path1: 'Custom path',
  custom_path: 'Enter custom path',
  invalid_path: 'Invalid custom path',
  from: 'From',
  to: 'To',
  show_preview: 'Show preview',

  retire: 'Retire',
  retire_title: 'Retire thread',
  retire_desc: 'Retired threads no longer get bumped to top in the feeds they appear in.',
  retired_desc: 'This thread is retired. New replies no longer bump it to the top of the feed.',
  is_retired: 'This thread has been retired',

  unretire: 'Unretire',
  unretire_title: 'Unretire thread',
  unretire_desc: 'This thread will be bumped to top in the feeds they appear in.',
  quote_help1: 'Select',
  quote_help2: 'to quote or share',

  trial_left: 'left of free trial.',
  after_trial: 'After the trial ends you can continue using Muut with the',
  free_plan: 'Free plan',
  reward: 'Referral reward',
  off33: 'Upgrade now and get 33% off all our paid plans!',
  spread: 'Spread the word!',
  invite: 'Invite a friend to start a Muut community and you’ll both get rewarded!',
  start_now: 'Start your own community now – it\'s free!',
  start_btn: 'Create',
  reserve: 'Reserve your forum name',
  free_acc: 'Free account',
  no_dialog: 'and remove this dialogue',
  click_change: 'Click to change',

  moderator: 'Moderator',
  mkadmin: 'Make administrator',
  mkmod: 'Make moderator',
  upgrade_mod: 'to make this user a moderator',
  upgrade_admin: 'to make this user administrator or moderator',

  my_profile: 'My profile',
  post_in: 'Post in',
  address_now: 'Thank you! Your email address has been confirmed.',
  open_pw: 'Please hit the button below to open a password change dialog',
  non_anon: 'You need to be logged in to perform this action',

  plan: 'Plan',
  trial: 'Start free trial',

  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spam?",

  channels: 'Channels',
  ch_name: 'Channel name',
  ban:  'Ban user',
  banned:  'Banned',
  days:  'Days',
  forever: 'Forever',
  slogan:  'Free forums and commenting by Muut',

  add: '+ Add',
  addons: 'Add-ons',
  myaccount: "Account",
  untitled: "Untitled",
  design: "Design",
  no_title: "Titolo obbligatorio",
  designer: "Disegnatore",
  developer: "Sviluppatore",




  ban_acc: 'Account bloccato',
  ban_msg: 'Sei temporaneamente bloccato e non puoi pubblicare su questo forum per aver violato le regole. Tempo mancante:',
  banned4: 'Non puoi pubblicare su questo forum.',
  warning: 'Attenzione',
  profanity: 'Il linguaggio blasfemo non è consentito su questo forum. Un comportamento contro le regole si traduce in un blocco dell\'account.',

  img_needed: "Carica un\’immagine",
  max: 'La dimensione massima per le immagini è 4Mb',
  yes: 'Si',
  upload: 'Carica immagini',
  show: 'mostra',
  hide: 'nascondi',
  invisible: 'Invisibile',
  givebody: 'Il corpo del testo non può essere vuoto.',
  show_old: 'Mostra vecchi messaggi',
  show_more: 'Mostra altri messaggi',
  show_new: 'Mostra nuovi messaggi',
  start: 'Inizia un nuovo argomento...',
  error: 'Si è verificato un errore. Si prega di copiare il messaggio negli appunti, ricaricare e riprovare. Ci scusiamo per l\'inconveniente - risolveremo il problema!',
  body: 'Corpo del testo',
  admin: 'Amministratore',
  someone: 'Qualcuno',
  title: 'Titolo',
  writing: 'sta scrivendo...',
  manage: 'Gestisci',
  fullview: 'Vista completa',
  link: 'collegamento',
  avatar: 'Cambia avatar',
  upgrade_link: 'Aggiorna',
  branding: 'Marchio',
  logo: 'Logo',
  title: 'Titolo',
  css: 'File CSS',
  single: 'parola singola',


  username_fail: 'Utilizza lettere, numeri o trattini',
  bold: 'grassetto',
  italics: 'corsivo',
  monospaced: 'monospazio',
  learn: 'Leggi altro...',
  settings: 'Impostazioni',

  all: 'Tutti i messaggi', // or alternatively: Tutti
  anon_1: 'anonimo',  // singolare
  anon: 'anonimi',  // plurale

  badforum: 'Forum non valido',
  c_acc1: 'Il tuo account ora funziona su tutti i siti che utilizzano Muut',
  c_acc: 'Account verificato',
  c_email: 'Indirizzo email aggiornato',
  cancel: 'Cancella',
  change: 'Cambia',
  changepw: 'Cambia password',
  close: 'Chiudi',
  collapse: 'Chiudi tutto',
  comm_count_1: 'commento',  // singolare: "1 commento"
  comm_count_n: 'commenti',  // plurale: "3 commenti"
  comment1: 'Commenta per primo...',
  comment: 'Commenta...',
  edit: 'modifica',
  email: 'Email',
  email_taken: 'Email in uso con altro account',
  emailtip: 'Il tuo indirizzo non viene mai condiviso con altri',
  enter: 'ctrl + invio',
  expired1: 'Abbiamo appena inviato i nuovi dati. Controlla la tua email.', // http://d.pr/i/1OEV
  expired: 'Questo link è scaduto',

  feed: 'Le mie attività', // alternatives: Attività personale


  help2: 'messaggio',
  help3: 'quota',
  help5: 'testo',
  help6: 'codice HTML',
  in_forum: 'in',
  invalid: 'Valore non valido',
  join: 'Iscriviti a Muut',
  later: 'Dopo...',
  less: 'meno',
  like: 'Mi piace',
  likepost: 'Metti mi piace',
  loading: 'Caricamento...',
  login: 'Accedi',
  login1: 'Accedi prima',
  login_and: "Accedi e",

  logout: 'Esci',
  mark: 'Offensivo o spam',
  mean: 'Forse intendevi',
  name: 'Nome visualizzato',
  nametip: 'Il tuo vero nome, così le persone potranno riconoscerti',
  newpass: 'Nuova password',
  noresults: 'Nessun risultato per',
  nospam: 'Nessun messaggio spam sul tuo forum!',
  notexist: 'non esiste.',
  ok: 'ok',
  online: 'Online',
  post: 'Messaggio',
  preview: 'Anteprima',
  progress: ['caricamento...', 'ancora in lavorazione...', 'e lavorando...', 'rinunciare'],
  reconnect: 'Riconessione...',
  removepost: 'Rimuovi',
  reply: 'Rispondi...',
  replybtn: 'Rispondi',
  save: 'Salva modifiche',
  saved: 'salvato',
  search: 'Cerca',
  select: 'Seleziona forum',
  setup: 'Configura ora',
  showing: 'Mostra',
  spam: 'Spam',
  step1: 'Ti abbiamo inviato una email di conferma. La tua email non verrà aggiornata se non completi questo passaggio!',
  step: 'Ancora un passaggio',
  terms: 'Accetto i <a>termini di servizio</a>.',
  thanks: 'Grazie!',
  uname_len: 'Digita almeno 4 lettere',
  uname_taken: 'Username in uso con altro account!',
  unametip: 'Questo non può essere modificato successivamente',
  undo: 'Annullare',
  unlike: 'Non mi piace',
  unspam: 'Segna come non spam',
  unver1: 'Account non verificato',
  unver2: 'Controlla la tua posta in arrivo per verificare il tuo account.',
  unver3: 'Invia un nuovo codice di verifica',
  unver4: "Inviato. Si prega di controllare la posta in arrivo.",
  unver: 'Non verificato',
  unwall: 'Guarda tutto',
  unwatch: 'Non guardare',
  upgrade2: 'Muut utilizza WebSockets o CORS per la comunicazione tra domini. Tutti i browser moderni successivi a Opera 11 e IE7 funzionano.',
  upgrade: 'Si prega di aggiornare il browser',
  username_taken: 'Username in uso con altro account',
  watch: 'Guarda nuovi messaggi',
  welcome1: 'Controlla la tua email per completare la registrazione. Se non ricevi email entro un minuto o due, controlla la tua cartella spam.',
  welcome2: 'Si prega di fornire un nome utente Muut',
  welcome: 'Benvenuto su Muut',
  you: 'Tu',

  // times
  now: 'adesso',
  months: "Gen,Feb,Mar,Apr,Mag,Giu,Lug,Ago,Set,Ott,Nov,Dic",
  min: 'm',
  hour: 'h',
  day: 'd',
  week: 'w'

}
