moot.language = {

   // the language code
   $code: 'it',

   no_title: "Titolo obbligatorio",
   designer: "Disegnatore",
   developer: "Sviluppatore",

   no_index: 'Disabilitare l\'indicizzazione sotto moot.it',
   mkpriv: 'Rendere questo forum privato',
   sign: 'Questo forum deve essere <a>registrato</a> prima.',

   s3: 'Bucket S3 personalizzato',
   s3_tip: 'Consenti dominio personalizzato per i motori di ricerca e un archivio di backup.',
   s3_tip2: 'Aggiungi permessi di accesso completo per <em>moot-aws@moot.it</em>',
   s3_no_access: "moot-aws@moot.it non può accedere a questo bucket",
   s3_missing: "Questo bucket non esiste",


   banned: 'Account bloccato',
   banned2: 'Sei temporaneamente bloccato e non puoi pubblicare su questo forum per aver violato le regole. Tempo mancante:',
   banned4: 'Non puoi pubblicare su questo forum.',
   warning: 'Attenzione',
   profanity: 'Il linguaggio blasfemo non è consentito su questo forum. Un comportamento contro le regole si traduce in un blocco dell\'account.',

   img_needed: "Carica un\'immagine",
   max: 'La dimensione massima per le immagini è 4Mb',
   yes: 'Si',
   upload: 'Carica immagini',
   show: 'mostra',
   hide: 'nascondi',
   invisible: 'Invisibile',
   givebody: 'Il corpo del testo non può essere vuoto.',
   show_old: 'Mostra vecchi messaggi',
   show_more: 'Mostra altri messaggi',
   show_new: 'Mostra nuovi messaggi',
   start: 'Inizia un nuovo argomento...',
   error: 'Si è verificato un errore. Si prega di copiare il messaggio negli appunti, ricaricare e riprovare. Ci scusiamo per l\'inconveniente - risolveremo il problema!',
   body: 'Corpo del testo',
   admin: 'Amministratore',
   someone: 'Qualcuno',
   title: 'Titolo',
   writing: 'sta scrivendo...',
   basic: 'Base (gratuito)',
   subs: 'Abbonamento',
   manage: 'Gestisci',
   fullview: 'Vista completa',
   link: 'collegamento',
   avatar: 'Cambia avatar',
   seo_update: 'La pagina SEO verrà aggiornata entro un\'ora',
   upgrade_link: 'Aggiorna',
   branding: 'Marchio',
   logo: 'Logo',
   bgcolor: 'Colore di sfondo',
   brand_name: 'Marca',
   title: 'Titolo',
   css: 'File CSS',
   mootbrand: 'Utilizzare marchio Moot',
   sso: 'Accesso unico',
   apikey: 'Chiave API',
   apisecret: 'Chiave segreta',
   single: 'parola singola',


   username_fail: 'Utilizza lettere, numeri o trattini',
   bold: 'grassetto',
   italics: 'corsivo',
   monospaced: 'monospazio',
   domain: 'URL del forum',
   domaintip: 'URL completo dei forum in cui gli utenti arrivano con i risultati di ricerca',
   learn: 'Leggi altro...',
   ga: 'Google Analytics Id',
   admins: 'Amministratore',
   adminstip: 'Un username per riga',
   settings: 'Impostazioni',

   all: 'Tutti i messaggi', // or alternatively: Tutti
   anon_1: 'anonimo',    // singolare
   anon: 'anonimi',      // plurale

   badforum: 'Forum non valido',
   c_acc1: 'Il tuo account ora funziona su tutti i siti che utilizzano Moot',
   c_acc: 'Account verificato',
   c_email: 'Indirizzo email aggiornato',
   cancel: 'Cancella',
   change: 'Cambia',
   changepw: 'Cambia password',
   close: 'Chiudi',
   collapse: 'Chiudi tutto',
   comm_count_1: 'commento',   // singolare: "1 commento"
   comm_count_n: 'commenti',  // plurale: "3 commenti"
   comment1: 'Commenta per primo...',
   comment: 'Commenta...',
   edit: 'modifica',
   email: 'Email',
   email_taken: 'Email in uso con altro account',
   emailtip: 'Il tuo indirizzo non viene mai condiviso con altri',
   enter: 'ctrl + invio',
   expired1: 'Abbiamo appena inviato i nuovi dati. Controlla la tua email.', // http://d.pr/i/1OEV
   expired: 'Questo link è scaduto',

   feed: 'Le mie attività', // alternatives: Attività personale

   forumname: 'Nome del forum',
   forums: 'Forum',

   help2: 'messaggio',
   help3: 'quota',
   help5: 'testo',
   help6: 'codice HTML',
   in_forum: 'in',
   invalid: 'Valore non valido',
   join: 'Iscriviti a Moot',
   later: 'Dopo...',
   less: 'meno',
   like: 'Mi piace',
   likepost: 'Metti mi piace',
   loading: 'Caricamento...',
   login: 'Accedi',
   login1: 'Accedi prima',
   login_and: "Accedi e",

   logout: 'Esci',
   mark: 'Offensivo o spam',
   mean: 'Forse intendevi',
   name: 'Nome visualizzato',
   nametip: 'Il tuo vero nome, così le persone potranno riconoscerti',
   newcat: 'Nuova categoria',
   newpass: 'Nuova password',
   noresults: 'Nessun risultato per',
   nospam: 'Nessun messaggio spam sul tuo forum!',
   notexist: 'non esiste.',
   notify: 'Segnalatemi nuove versioni',
   ok: 'ok',
   online: 'Online',
   post: 'Messaggio',
   preview: 'Anteprima',
   progress: ['caricamento...', 'ancora in lavorazione...', 'e lavorando...', 'rinunciare'],
   reconnect: 'Riconessione...',
   removecat: 'Rimuovi. I messaggi non sono stati cancellati',
   removepost: 'Rimuovi',
   reply: 'Rispondi...',
   replybtn: 'Rispondi',
   save: 'Salva modifiche',
   saved: 'salvato',
   search: 'Cerca',
   select: 'Seleziona forum',
   setup: 'Configura ora',
   showing: 'Mostra',
   slogan: 'Forums and commenting re-imagined',
   spam: 'Spam',
   step1: 'Ti abbiamo inviato una email di conferma. La tua email non verrà aggiornata se non completi questo passaggio!',
   step: 'Ancora un passaggio',
   terms: 'Accetto i <a>termini di servizio</a>.',
   thanks: 'Grazie!',
   uname_len: 'Digita almeno 6 lettere',
   uname_taken: 'Username in uso con altro account!',
   unametip: 'Questo non può essere modificato successivamente',
   undo: 'Annullare',
   unlike: 'Non mi piace',
   unspam: 'Segna come non spam',
   unver1: 'Account non verificato',
   unver2: 'Controlla la tua posta in arrivo per verificare il tuo account. Gli utenti verificati possono utilizzare Moot e ricevere notifiche email sui messaggi. <a>Invia un nuovo codice di verifica...</a>',
   unver3: '<a>Invia un nuovo</a> codice di verifica:',
   unver4: "Inviato. Si prega di controllare la posta in arrivo.",
   unver: 'Non verificato',
   unwall: 'Guarda tutto',
   unwatch: 'Non guardare',
   upgrade2: 'Moot utilizza WebSockets o CORS per la comunicazione tra domini. Tutti i browser moderni successivi a Opera 11 e IE7 funzionano.',
   upgrade: 'Si prega di aggiornare il browser',
   username_taken: 'Username in uso con altro account',
   watch: 'Guarda nuovi messaggi',
   welcome1: 'Controlla la tua email per completare la registrazione. Se non ricevi email entro un minuto o due, controlla la tua cartella spam.',
   welcome2: 'Si prega di fornire un nome utente Moot',
   welcome: 'Benvenuto su Moot',
   you: 'Tu',

   // times
   now: 'adesso',
   months: "Gen,Feb,Mar,Apr,Mag,Giu,Lug,Ago,Set,Ott,Nov,Dic",
   min: 'm',
   hour: 'h',
   day: 'd',
   week: 'w'

}
