moot.language = {

  // the language code
  $code: 'ja',

  /* New stuff */
  channels: 'Channels',
  ch_name: 'Channel name',
  ban:  'Ban user',
  banned:  'Banned',
  ban_acc: 'Banned account',
  ban_msg: 'You are temporarily banned from posting on this forum.',
  days:  'Days',
  forever: 'Forever',
  slogan:  'Free forums and commenting by Muut',

  add: '+ Add',
  addons: 'Add-ons',
  myaccount: "My account",
  untitled: "Untitled",
  design: "Design",
  no_title: "Title must be given",
  designer: "Designer",
  developer: "Developer",



  img_needed: "Please upload an image file",
  max: 'Maximum image size is 4Mb',
  yes: 'Yes',
  upload: 'Upload images',
  show: 'show',
  hide: 'hide',
  invisible: 'Invisible',
  givebody: 'Body cannot be empty.',
  show_old: 'Show oldest replies',
  show_more: 'Show more replies',
  show_new: 'Show newest replies',
  start: 'Start a new topic...',
  error: 'Oops, an error. Please copy the post to clipboard, reload and try again. Sorry – we will fix this!',
  body: 'Body text',
  admin: 'Admin',
  someone: 'Someone',
  writing: 'is writing...',
  basic: 'Basic (free)',
  subs: 'Subscriptions',
  manage: 'Manage',
  fullview: 'Full view',
  title: 'Title',
  link: 'link',
  single: 'single word',


  username_fail: '英数字とハイフンのみ利用可能です',
  avatar: 'アバターの変更',
  upgrade_link: 'アップグレード',
  branding: 'ブランディング',
  logo: 'ロゴ',
  css: 'CSSファイル',

  bold: '太字',
  italics: '斜体',
  monospaced: '固定幅フォント',
  learn: '詳細...',
  settings: '設定',

  all: 'すべての投稿', // or alternatively: All
  anon_1: '匿名',  // singular
  anon: '匿名',  // plural

  badforum: 'フォーラムが正しくありません',
  c_acc1: 'このアカウントはMuutを使ったすべてのサイトでご利用いただけます',
  c_acc: 'アカウントを確認しました',
  c_email: 'メールアドレスを更新しました',
  cancel: 'キャンセル',
  change: '変更',
  changepw: 'パスワードの変更',
  close: '閉じる',
  collapse: 'すべて折りたたむ',
  comm_count_1: 'コメント',  // singular: "1 comment"
  comm_count_n: 'コメント',  // plural: "3 comments"
  comment1: '最初のコメントを書く…',
  comment: 'コメント…',
  edit: '編集',
  email: 'メールアドレス',
  email_taken: 'このメールアドレスは既に使用されています',
  emailtip: 'メールアドレスは非公開です',
  enter: 'ctrl + enter',
  expired1: '新しいメールを送信しました。メールを確認してください。', // http://d.pr/i/1OEV
  expired: 'このリンクは既に有効期限が切れています。',

  feed: 'あなたのフィード', // alternatives: My own, personal


  help2: '投稿',
  help3: '引用文',
  help5: 'コード、言語は自動推測',
  help6: 'HTMLコード',
  in_forum: 'in',
  invalid: '不正な文字が含まれています',
  join: 'Muutユーザー登録',
  later: '後で…',
  less: '隠す',
  like: 'いいね！',
  likepost: 'この投稿にいいね！をつける',
  loading: '読み込み中…',
  login: 'ログイン',
  login1: 'ログインしてください',
  login_and: "ログインして",

  logout: 'ログアウト',
  mark: '攻撃的、もしくはスパム',
  mean: 'もしかして: ',
  name: '表示名',
  nametip: '本名、他の人があなただと分かるような名前',
  newpass: '新しいパスワード',
  noresults: '見つかりませんでした: ',
  nospam: 'スパムはありません',
  notexist: '見つかりませんでした',
  notify: 'Muutの新着リリースを通知する',
  ok: 'OK',
  online: 'オンライン',
  post: '投稿',
  preview: 'プレビュー',
  progress: ['読み込み中…', 'まだ読み込み中…', 'さらに読み込み中…', '読み込み失敗！'],
  reconnect: '再接続中…',
  removepost: 'この投稿を削除',
  reply: '返信する…',
  replybtn: '返信する',
  save: '変更を保存',
  saved: '保存しました',
  search: '検索',
  select: 'フォーラムを選択',
  setup: 'フォーラムを作成',
  showing: '表示中',
  spam: 'スパム',
  step1: '確認のメールを送信しました。このステップを完了しないとアドレスは更新されません！',
  step: 'もうひとつ',
  terms: '<a>利用規約</a>に同意します',
  thanks: 'ありがとう!',
  uname_len: '6文字以上',
  uname_taken: 'このユーザー名は既に使われています',
  unametip: 'この項目は後から変更できません',
  undo: '取り消す',
  unlike: 'いいね！を取り消す',
  unspam: 'スパムではない',
  unver1: '未確認のアカウント',
  unver2: 'アカウントを確認するためにメールをチェックしてください。確認すると、ムートを見たりメール通知を受け取ることができるようになります。<a>確認コードを再送信…</a>',
  unver3: '確認コードの<a>新しい送信先</a>:',
  unver4: "送信しました。メールを確認してください。",
  unver: '未確認',
  unwall: 'すべてのウォッチを解除',
  unwatch: 'ウォッチ解除',
  upgrade2: 'MuutはWebSocketsかCORSをクロスドメイン通信に使用します。Opera 11とInternet Explorer 7以外の比較的新しいブラウザで動作します。',
  upgrade: 'ブラウザを更新してください',
  username_taken: 'このユーザー名は既に使用されています',
  watch: 'このムートをウォッチ',
  welcome1: 'メールを確認して、登録を完了してください。数分経ってもメールが届かない場合は、迷惑メールフォルダを確認してください。',
  welcome2: 'Muutのユーザー名を入力してください',
  welcome: 'Muutへようこそ',
  you: 'あなた',

  // times
  now: 'たった今',
  months: "1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月",
  min: '分前',
  hour: '時間前',
  day: '日前',
  week: '週間前'

}
