moot.language = {

   // the language code
   $code: 'ja',

   /* New stuff */
   avatar: 'アバターの変更',
   seo_update: 'SEOページはもうすぐ更新されます',
   upgrade_link: 'アップグレード',
   branding: 'ブランディング',
   logo: 'ロゴ',
   bgcolor: '背景色',
   css: 'CSSファイル',
   mootbrand: 'Mootブランディングを使用',
   sso: 'シングルサインオン',
   apikey: 'API key',
   apisecret: 'Secret key',

   /* End new stuff */


   bolded: '太字',
   italics: '斜体',
   monospaced: '固定幅フォント',
   domain: 'フォーラムのURL',
   domaintip: '検索結果からリンクするために必要な、完全なURLを記入して下さい',
   learn: '詳細...',
   ga: 'Google Analytics トラッキングID',
   gatip: '静的ページで利用されます',
   admins: '管理者権限',
   adminstip: '1行につき1ユーザー',
   settings: '設定',

   all: 'すべての投稿', // or alternatively: All
   anon_1: '匿名',    // singular
   anon: '匿名',      // plural

   badforum: 'フォーラムが正しくありません',
   c_acc1: 'このアカウントはMootを使ったすべてのサイトでご利用いただけます',
   c_acc: 'アカウントを確認しました',
   c_email: 'メールアドレスを更新しました',
   cancel: 'キャンセル',
   change: '変更',
   changepw: 'パスワードの変更',
   close: '閉じる',
   collapse: 'すべて折りたたむ',
   comm_count_1: 'コメント',   // singular: "1 comment"
   comm_count_n: 'コメント',  // plural: "3 comments"
   comment1: '最初のコメントを書く…',
   comment: 'コメント…',
   edit: '編集',
   email: 'メールアドレス',
   email_taken: 'このメールアドレスは既に使用されています',
   emailtip: 'メールアドレスは非公開です',
   enter: 'ctrl + enter',
   expired1: '新しいメールを送信しました。メールを確認してください。', // http://d.pr/i/1OEV
   expired: 'このリンクは既に有効期限が切れています。',

   feed: 'あなたのフィード', // alternatives: My own, personal

   forumname: 'フォーラム名',
   forums: 'フォーラム',
   help1: '最初の行はタイトル',
   help2: '投稿',
   help3: '引用文',
   help5: 'コード、言語は自動推測',
   help6: 'HTMLコード',
   in_forum: 'in',
   invalid: '不正な文字が含まれています',
   join: 'Mootに参加',
   later: '後で…',
   less: '隠す',
   like: 'いいね！',
   likepost: 'この投稿にいいね！をつける',
   loading: '読み込み中…',
   login: 'ログイン',
   login1: 'ログインしてください',
   login_and: "ログインして",

   logout: 'ログアウト',
   mark: '攻撃的、もしくはスパム',
   mean: 'もしかして: ',
   name: '表示名',
   nametip: '本名、他の人があなただと分かるような名前',
   newcat: '新しいカテゴリ',
   newpass: '新しいパスワード',
   noresults: '見つかりませんでした: ',
   nospam: 'スパムはありません',
   notexist: '見つかりませんでした',
   notify: 'Mootの新着リリースを通知する',
   ok: 'OK',
   online: 'オンライン',
   post: '投稿',
   preview: 'プレビュー',
   progress: ['読み込み中…', 'まだ読み込み中…', 'さらに読み込み中…', '読み込み失敗！'],
   reconnect: '再接続中…',
   removecat: 'カテゴリを削除(投稿は削除されません)',
   removepost: 'この投稿を削除',
   reply: '返信する…',
   replybtn: '返信する',
   save: '変更を保存',
   saved: '保存しました',
   search: '検索',
   select: 'フォーラムを選択',
   setup: 'フォーラムを作成',
   showing: '表示中',
   slogan: 'フォーラムとディスカッションの、再創造。',
   spam: 'スパム',
   start: '今なにしてる？',
   step1: '確認のメールを送信しました。このステップを完了しないとアドレスは更新されません！',
   step: 'もうひとつ',
   terms: '<a>利用規約</a>に同意します',
   thanks: 'ありがとう!',
   uname_len: '6文字以上',
   uname_taken: 'このユーザー名は既に使われています',
   unametip: 'この項目は後から変更できません',
   undo: '取り消す',
   unlike: 'いいね！を取り消す',
   unspam: 'スパムではない',
   unver1: '未確認のアカウント',
   unver2: 'アカウントを確認するためにメールをチェックしてください。確認すると、ムートを見たりメール通知を受け取ることができるようになります。<a>確認コードを再送信…</a>',
   unver3: '確認コードの<a>新しい送信先</a>:',
   unver4: "送信しました。メールを確認してください。",
   unver: '未確認',
   unwall: 'すべてのウォッチを解除',
   unwatch: 'ウォッチ解除',
   upgrade2: 'MootはWebSocketsかCORSをクロスドメイン通信に使用します。Opera 11とInternet Explorer 7以外の比較的新しいブラウザで動作します。',
   upgrade: 'ブラウザを更新してください',
   username_taken: 'このユーザー名は既に使用されています',
   watch: 'このムートをウォッチ',
   welcome1: 'メールを確認して、登録を完了してください。数分経ってもメールが届かない場合は、迷惑メールフォルダを確認してください。',
   welcome2: 'Mootのユーザー名を入力してください',
   welcome: 'Mootへようこそ',
   you: 'あなた',

   // times
   now: 'たった今',
   months: "1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月",
   min: '分前',
   hour: '時間前',
   day: '日前',
   week: '週間前'

}
