moot.language = {

   // the language code
   $code: 'ko_kr',

   all: '모든 글', // or alternatively: All

   anon_1: '명 익명',    // singular
   anon: '명 익명',      // plural

   badforum: '유효하지 않은 포럼입니다',
   c_acc1: '이제 Moot가 있는 곳이면 어디든지 계정이 통용됩니다',
   c_acc: '계정 승인되었습니다',
   c_email: '이메일 주소가 변정됐습니다',
   cancel: '취소하기',
   change: '변경하기',
   changepw: '비밀번호 변경',
   close: '닫기',
   collapse: '전부 접기',
   comm_count_1: '개 댓글',   // singular: "1 comment"
   comm_count_n: '개 댓글',  // plural: "3 comments"
   comment1: '첫 댓글을 남겨보세요...',
   comment: '댓글 남기기...',
   edit: '편집하기',
   email: '이메일',
   email_taken: '사용중인 이메일입니다',
   emailtip: '이메일 정보는 유출되지 않습니다',
   enter: 'ctrl + enter',
   expired1: '새로운 링크를 보내드렸습니다. 이메일을 확인하세요.', // http://d.pr/i/1OEV
   expired: '이 링크는 기한이 만료되었습니다',

   feed: '구독중인 피드', // alternatives: My own, personal

   forumname: '포럼 이름',
   forums: '포럼',
   help1: '첫 줄은 제목입니다',
   help2: '글 남기기',
   help3: '인용 문구',
   help4: '두번째 줄',
   help5: '컴퓨터 코드 (자동인식)',
   help6: 'HTML 코드',
   in_forum: 'in',
   invalid: '유효하지 않은 값입니다',
   join: 'Moot에 가입하기',
   later: '나중에...',
   less: 'less',
   like: '좋아요!',
   likepost: '좋아요! 설정하기',
   loading: '로딩 중...',
   login: '로그인',
   login1: '로그인하세요',
   login_and: "로그인하고",

   logout: '로그아웃',
   mark: '욕설 또는 스팸',
   mean: '혹시 이런 뜻이었나요:',
   name: '표시할 이름',
   nametip: '실명 (사람들이 알아볼수 있게끔)',
   newcat: '새 분류',
   newpass: '새 비밀번호',
   noresults: '검색결과가 없습니다:',
   nospam: '포럼에 스팸이 없습니다!',
   notexist: '존재하지 않습니다.',
   notify: '새 릴리스가 나올때 알림받기',
   ok: 'ok',
   online: '온라인',
   post: '글 남기기',
   preview: '미리보기입니다',
   progress: ['로딩중...', '열심히 로딩중...', '여전히 로딩중...', '포기했어요'],
   reconnect: '재접속중...',
   removecat: '제거하기. 글이 아직 제거되지 않았습니다.',
   removepost: '글 제거하기',
   reply: '댓글 남기기...',
   replybtn: '댓글 남기기',
   save: '변경내용 저장',
   saved: '저장됨',
   search: '검색',
   select: '포럼 선택하기',
   setup: '지금 설정하기',
   showing: '표시중',
   slogan: '새로운 상상력으로 만든 포럼과 댓글',
   spam: '스팸',
   start: '요즘 어떠세요?',
   step1: '확인 메일을 보내드렸습니다. 이 단계를 완료해야 이메일이 등록될 수 있습니다!',
   step: '마지막 단계입니다',
   terms: '<a>이용 약관</a>에 동의합니다.',
   thanks: '감사합니다',
   uname_len: '6 글자 이상이어야 합니다',
   uname_taken: '아이디가 사용중이래요!',
   unametip: '나중에 변경할 수 없습니다',
   undo: '취소',
   unlike: '좋아요 취소',
   unspam: '스팸등록 취소',
   unver1: '확인되지 않은 계정입니다',
   unver2: '계정을 인증하려면 이메일을 열어보세요. 인증을 받으면  moot를 지켜보거나 이메일로 알림을 받아볼 수 있습니다. <a>새 인증코드</a>를 보내기:',
   unver3: '<a>새 인증코드</a>를 보내기:',
   unver4: "보냈습니다. 받은편지함을 확인해 보세요.",
   unver: '미확인',
   unwall: '전부 지켜보기 취소',
   unwatch: '지켜보기 취소',
   upgrade2: 'Moot는 도메인간 통신을 위해 WebSockets 또는 CORS를 사용합니다. 오페라11과 인터넷 익스플로러7을 제외하고 모든 최신 브라우저에서 정상 작동합니다.',
   upgrade: '브라우저를 업그레이드하시기 바랍니다',
   username_taken: '사용중인 아이디입니다',
   watch: '새로 달리는 댓글 지켜보기',
   welcome1: '가입을 완료하기 위해 이메일을 확인해 보세요. 1-2분 내에 이메일을 받지 못하셨다면 스팸 폴더를 확인하시기 바랍니다.',
   welcome2: 'Moot 아이디를 입력해 주세요',
   welcome: 'Moot에 오신 것을 환영합니다',
   you: '당신',

   // times
   now: '방금',
   months: "1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월",
   min: '분 전',
   hour: '시간 전',
   day: '일 전',
   week: '주 전'

}
