moot.language = {

  // the language code
  $code: 'ko',

  /* New stuff */
  address_now: 'Thank you! Your email address has been confirmed.',
  open_pw: 'Please hit the button below to open a password change dialog',
  non_anon: 'You need to be logged in to perform this action',

  plan: 'Plan',
  trial: 'Start free trial',

  is_private: "비공개 포럼",
  owner_msg: "포럼 관리자에게 메시지 보내기... (선택사항)",
  req_access: "접근 요청",
  req_sent: "접근 요청 보냄",
  or_join: "또는 커뮤니티 <a>가입하기</a>",
  save_with: "20% 할인",
  rem_post: "글 삭제하시겠습니까?",
  is_spam: "스팸글입니까?",

  channels: '채널',
  ch_name: '채널명',
  ban:  '사용자 차단',
  banned:  '차단됨',
  ban_acc: '차단된 계정',
  ban_msg: '현재 포럼에서 일시적으로 차단되었습니다.',
  days:  '일',
  forever: '영구',
  slogan:  'Mutt 무료 포럼 서비스',

  add: '+ 추가',
  addons: '부가 기능',
  myaccount: "계정 정보",
  untitled: "제목 없음",
  design: "디자인",
  no_title: "제목 필수",
  designer: "디자이너",
  developer: "개발자",



  img_needed: "이미지 파일을 올려주세요",
  max: '최대 4Mb입니다',
  yes: '확인',
  upload: '이미지 업로드',
  show: '보기',
  hide: '감추기',
  invisible: '보이지 않음',
  givebody: '본문 내용이 없습니다.',
  show_old: '오래된 답글순',
  show_more: '답글 더보기',
  show_new: '최신 답글순',
  start: '새 주제 시작하기...',
  single: '단순',
  bold: '굵게',
  italics: '기울임',
  monospaced: '소스코드',
  learn: '자세히 보기...',
  settings: '설정',
  error: '오류입니다. 클립보드에 일단 작성 중이던 내용을 복사하신 후, 재시도해주세요. 곧 고치겠습니다!',
  body: '본문 텍스트',
  admin: '관리자',
  someone: '누군가',
  writing: '작성 중...',
  manage: '관리자',
  fullview: '전체 보기',
  title: '제목',
  link: '링크',
  avatar: '아바타 변경',
  upgrade_link: '업그레이드',
  branding: '브랜드',
  logo: '로고',
  css: 'CSS 파일',



  /* End new stuff */


  username_fail: '영문 소문자, 숫자, 하이픈(\'-\')만 사용하실 수 있습니다',
  all: '모든 글', // or alternatively: All

  anon_1: '명 익명',  // singular
  anon: '명 익명',  // plural

  badforum: '유효하지 않은 포럼입니다',
  c_acc1: '이제 Muut가 있는 곳이면 어디든지 계정이 통용됩니다',
  c_acc: '계정 승인되었습니다',
  c_email: '이메일 주소가 변경됐습니다',
  cancel: '취소',
  change: '변경',
  changepw: '비밀번호 변경',
  close: '닫기',
  collapse: '전부 접기',
  comm_count_1: '개 댓글',  // singular: "1 comment"
  comm_count_n: '개 댓글',  // plural: "3 comments"
  comment1: '첫 댓글을 남겨보세요...',
  comment: '댓글 남기기...',
  edit: '편집',
  email: '이메일',
  email_taken: '사용 중인 이메일입니다',
  emailtip: '이메일 정보는 유출되지 않습니다',
  enter: 'ctrl + enter',
  expired1: '새로운 링크를 보내드렸습니다. 이메일을 확인하세요.', // http://d.pr/i/1OEV
  expired: '이 링크는 기한이 만료되었습니다',

  feed: '구독중인 피드', // alternatives: My own, personal


  help2: '글 남기기',
  help3: '인용 문구',
  help5: '컴퓨터 코드 (자동인식)',
  help6: 'HTML 코드',
  in_forum: 'in',
  invalid: '유효하지 않은 값입니다',
  join: 'Muut에 가입하기',
  later: '나중에...',
  less: '닫기',
  like: '좋아요!',
  likepost: '좋아요! 설정하기',
  loading: '로딩 중...',
  login: '로그인',
  login1: '로그인하세요',
  login_and: "로그인 - ",

  logout: '로그아웃',
  mark: '욕설 또는 스팸',
  mean: '혹시 이런 뜻이었나요:',
  name: '표시할 이름',
  nametip: '실명 (사람들이 알아볼수 있게끔)',
  newpass: '새 암호',
  noresults: '검색결과가 없습니다:',
  nospam: '포럼에 스팸이 없습니다!',
  notexist: '존재하지 않습니다.',
  ok: '확인',
  online: '온라인',
  post: '글 남기기',
  preview: '미리보기입니다',
  progress: ['로딩중...', '열심히 로딩중...', '여전히 로딩중...', '포기했어요'],
  reconnect: '재접속중...',
  removepost: '글 제거하기',
  reply: '댓글 남기기...',
  replybtn: '댓글 남기기',
  save: '변경내용 저장',
  saved: '저장됨',
  search: '검색',
  select: '포럼 선택하기',
  setup: '지금 설정하기',
  showing: '표시중',
  spam: '스팸',
  step1: '확인 메일을 보내드렸습니다. 이 단계를 완료해야 이메일이 등록될 수 있습니다!',
  step: '마지막 단계입니다',
  terms: '<a>이용 약관</a>에 동의합니다.',
  thanks: '감사합니다',
  uname_len: '4 글자 이상이어야 합니다',
  uname_taken: '아이디가 사용중이래요!',
  unametip: '나중에 변경할 수 없습니다',
  undo: '취소',
  unlike: '좋아요 취소',
  unspam: '스팸등록 취소',
  unver1: '확인되지 않은 계정입니다',
  unver2: '계정을 인증하려면 이메일을 열어보세요.',
  unver3: '새 인증코드</a>를 보내기',
  unver4: "보냈습니다. 받은편지함을 확인해 보세요.",
  unver: '미확인',
  unwall: '전부 지켜보기 취소',
  unwatch: '지켜보기 취소',
  upgrade2: 'Muut는 도메인간 통신을 위해 WebSockets 또는 CORS를 사용합니다. 오페라11과 인터넷 익스플로러7을 제외하고 모든 최신 브라우저에서 정상 작동합니다.',
  upgrade: '브라우저를 업그레이드하시기 바랍니다',
  username_taken: '사용중인 아이디입니다',
  watch: '새로 달리는 댓글 지켜보기',
  welcome1: '가입을 완료하기 위해 이메일을 확인해 보세요. 1-2분 내에 이메일을 받지 못하셨다면 스팸 폴더를 확인하시기 바랍니다.',
  welcome2: 'Muut 아이디를 입력해 주세요',
  welcome: 'Muut에 오신 것을 환영합니다',
  you: '당신',

  // times
  now: '방금',
  months: "1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월",
  min: '분 전',
  hour: '시간 전',
  day: '일 전',
  week: '주 전'

}
