moot.language = {

   // the language code
   $code: 'nl',

   /* New stuff */
   show_old: 'Show oldest replies',
   show_more: 'Show more replies',
   show_new: 'Show newest replies',
   start: 'Start a new topic...',
   domain: 'Forum URL',
   ga: 'Google Analytics Id',
   error: 'Oops, an error. Please copy the post to clipboard, reload and try again. Sorry – we will fix this!',
   body: 'Body text',
   admin: 'Admin',
   someone: 'Someone',
   writing: 'is writing...',
   basic: 'Basic (free)',
   subs: 'Subscriptions',
   manage: 'Manage',
   fullview: 'Full view',
   title: 'Title',
   link: 'link',
   avatar: 'Change avatar',
   seo_update: 'The SEO pages will be updated within the hour',
   upgrade_link: 'Upgrade',
   branding: 'Branding',
   logo: 'Logo',
   bgcolor: 'Background color',
   brand_name: 'Brand name',
   css: 'CSS file',
   mootbrand: 'Use Moot branding',
   sso: 'Single Sign-On',
   apikey: 'API key',
   apisecret: 'Secret key',
   single: 'single word',
   admins: 'Administrators',

   /* End new stuff */

   username_fail: 'Gebruik letters, nummers of spaties',
   domaintip: 'Volledige URL naar de forums waar gebruikers heen worden verwezen vanaf de zoekresultaten',
   bold: 'vetgedrukt',
   italics: 'cursief',
   monospaced: 'onproportioneel geplaatst',
   learn: 'Kom meer te weten...',
   adminstip: 'Een gebruikersnaam per regel',
   settings: 'Instellingen',

   all: 'Alle posts', // or alternatively: All

   anon_1: 'onbekend',    // singular
   anon: 'onbekenden',      // plural

   badforum: 'Ongeldig forum',
   c_acc1: 'Je account werkt nu op alle sites die gebruik maken van Moot',
   c_acc: 'Account bevestigd',
   c_email: 'Email adres upgedate',
   cancel: 'Annuleer',
   change: 'Verander',
   changepw: 'Verander wachtwoord',
   close: 'Sluit',
   collapse: 'Sluit allen',
   comm_count_1: 'reactie',   // singular: "1 comment"
   comm_count_n: 'reacties',  // plural: "3 comments"
   comment1: 'Ben de eerste om te reageren...',
   comment: 'Reageer...',
   edit: 'aanpassen',
   email: 'Email',
   email_taken: 'Deze email is al in gebruik',
   emailtip: 'Uw email zal nooit worden gedeeld',
   enter: 'ctrl + enter',
   expired1: 'We hebben u zojuis een nieuwe gestuurd. Checkt u alstublieft uw email.', // http://d.pr/i/1OEV
   expired: 'Deze link is verlopen',

   feed: 'Mijn feed', // alternatives: My own, personal

   forumname: 'Forum naam',
   forums: 'Forums',

   help2: 'bericht',
   help3: 'geciteerd bericht',
   help5: 'code, taal is geraden',
   help6: 'HTML code',
   in_forum: 'in',
   invalid: 'Ongeldige waarde',
   join: 'Meld je aan bij Moot',
   later: 'Later...',
   less: 'minder',
   like: 'Vind ik leuk',
   likepost: 'Vind dit bericht leuk',
   loading: 'Laden...',
   login: 'Log in',
   login1: 'Log eerst in',
   login_and: "Login en",

   logout: 'Log out',
   mark: 'Beledigend of spam',
   mean: 'Bedoelde u',
   name: 'Weergeef naam',
   nametip: 'Uw echte naam, zodat mensen u kunnen herkennen',
   newcat: 'Nieuwe catagorie',
   newpass: 'Nieuw wachtwoord',
   noresults: 'Geen resultaten voor',
   nospam: 'Geen span op uw forum!',
   notexist: 'bestaat niet.',
   notify: 'Hou mij op de hoogte van nieuwe versies',
   ok: 'oke',
   online: 'Online',
   post: 'Bericht',
   preview: 'Voorbeeld',
   progress: ['laden...', 'Nog steeds bezig...', 'nog steeds...', 'geeft op'],
   reconnect: 'Herverbinden...',
   removecat: 'Verwijder. De berichten zijn niet verwijderd',
   removepost: 'Verwijder dit bericht',
   reply: 'Antwoord...',
   replybtn: 'Antwoord',
   save: 'Sla aanpassingen op',
   saved: 'opgeslagen',
   search: 'Zoek',
   select: 'Selecteer forum',
   setup: 'Zet nu op',
   showing: 'Zichtbaar',
   slogan: 'Forums en reageren opnieuw bedacht',
   spam: 'Spam',
   step1: 'We hebben u een bevestigings email gestuurd. Uw email is wordt niet upgedate voordat deze stap voltooid is!',
   step: 'Nog een stap',
   terms: 'Ik aanvaard de <a>servicevoorwaarden</a>.',
   thanks: 'Danku!',
   uname_len: 'Typ 6 karakters of meer',
   uname_taken: 'Deze naam is al bezet!',
   unametip: 'Dit kan later niet verandert worden',
   undo: 'Ongedaan maken',
   unlike: 'Vind ik niet meer leuk',
   unspam: 'Geen spam',
   unver1: 'Ongeverifieerde account',
   unver2: 'Check alstiblieft uw email om uw account te bevestigen. Geverifieerde gebruikers kunnen moots bekijken en email notificaties ontvangen. <a>Zend een nieuwe verificatiecode...</a>',
   unver3: '<a>Zend een nieuwe</a> verificatiecode naar:',
   unver4: "Verzonden. Checkt u alstublieft uw inbox.",
   unver: 'Ongeverifieerd',
   unwall: 'Houd mij niet meer op de hoogte van allen',
   unwatch: 'Houd mij niet meer op de hoogte',
   upgrade2: 'Moot gebruikt WebSockets of CORS voor cross domein communicatie. Alle moderne browsers behalve Opera 11 en IE7 werken.',
   upgrade: 'Upgrade u alstublieft uw browser',
   username_taken: 'Deze gebruikersnaam is bezet',
   watch: 'Kijk uit voor nieuwe reacties',
   welcome1: 'Bekijkt u alstublieft uw email om uw registratie te kunnen voltooien. Als u geen email ontvangt binnen 2 minuten, bekijkt u dan alstublieft uw spam map.',
   welcome2: 'Geeft u alstublieft een Moot gebruikersnaam',
   welcome: 'Welkom bij Moot',
   you: 'U',

   // times
   now: 'zo net',
   months: "jan,feb,maa,apr,mei,jun,jul,aug,sep,okt,nov,dec",
   min: 'm',
   hour: 'u',
   day: 'd',
   week: 'w'

}
