moot.language = {

  // the language code
  $code: 'no',

  // new stuff
  no_notify: 'Disable all email notifications',
  watchall: 'Watch for all new posts',
  move: 'Move thread',
  moved: 'Thread moved',
  custom_path1: 'Custom path',
  custom_path: 'Enter custom path',
  invalid_path: 'Invalid custom path',
  from: 'From',
  to: 'To',

  retire: 'Retire',
  retire_title: 'Retire thread',
  retire_desc: 'Retired threads no longer get bumped to top in the feeds they appear in.',
  retired_desc: 'This thread is retired. New replies no longer bump it to the top of the feed.',
  is_retired: 'This thread has been retired',

  unretire: 'Unretire',
  unretire_title: 'Unretire thread',
  unretire_desc: 'This thread will be bumped to top in the feeds they appear in.',
  quote_help1: 'Select',
  quote_help2: 'to quote or share',

  trial_left: 'left of free trial.',
  after_trial: 'After the trial ends you can continue using Muut with the',
  free_plan: 'Free plan',
  reward: 'Referral reward',
  off33: 'Upgrade now and get 33% off all our paid plans!',
  spread: 'Spread the word!',
  invite: 'Invite a friend to start a Muut community and you’ll both get rewarded!',
  start_now: 'Start your own community now – it\'s free!',
  start_btn: 'Create',
  reserve: 'Reserve your forum name',
  free_acc: 'Free account',
  no_dialog: 'and remove this dialogue',
  click_change: 'Click to change',

  moderator: 'Moderator',
  mkadmin: 'Make administrator',
  mkmod: 'Make moderator',
  upgrade_mod: 'to make this user a moderator',
  upgrade_admin: 'to make this user administrator or moderator',

  my_profile: 'Min profil',
  post_in: 'Skriv i',
  address_now: 'Takk! Din epost-adresse har blitt bekreftet.',
  open_pw: 'Vennligst trykk på knappen under for å åpne et vindu for endring av passord.',
  non_anon: 'Du må være innlogget for å utføre denne handlingen',

  plan: 'Plan',
  trial: 'Start free trial',

  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spam?",

  channels: 'Temaer',
  ch_name: 'Tema navn',
  ban: 'Utesteng bruker',
  banned: 'Utestengt',
  ban_acc: 'Sperret konto',
  ban_msg: 'Du er midlertidig utestengt fra dette forumet.',
  days: 'Dager',
  forever: 'For alltid',

  add: '+ legg til',
  addons: 'Add-ons',
  myaccount: 'Min konto',
  untitled: 'Uten tittel',
  design: 'Design',
  no_title: 'Tittel må oppgies',
  designer: 'Designer',
  developer: 'Utvikler',

  img_needed: 'Vennligst last opp et bilde',
  max: 'Maksimum bildestørrelse er 4Mb',
  yes: 'Ja',
  upload: 'Last opp bilde',
  show: 'Vis',
  hide: 'Skjul',


  invisible: 'Usynlig',
  givebody: 'Dette feltet kan ikke stå tomt',
  show_old: 'Vis eldste svar',
  show_more: 'Vis flere svar',
  show_new: 'Vis siste svar',
  start: 'Skriv et nytt innlegg',
  error: 'Oops, det oppstod en feil. Kopier innlegget til clipboard og last inn siden på nytt. Beklager – vi skal fikse dette!',
  body: 'Skriv ditt innlegg her',
  admin: 'Admin',
  someone: 'Noen',
  writing: 'skriver...',
  manage: 'Administrer',

  fullview: 'Maksimer visning',
  title: 'Tittel',
  link: 'lenke',
  single: 'enkeltord',

  username_fail: 'Bruk bokstaver, sifre eller bindestrek',
  avatar: 'Endre avatar',
  upgrade_link: 'Oppgrader',
  branding: 'Branding',
  logo: 'Logotype',
  css: 'CSS-fil',

  bold: 'fet',
  italics: 'kursiv',
  monospaced: 'monospace',
  learn: 'Lær mer...',
  settings: 'Innstillinger',

  all: 'Alle innlegg', // or alternatively: Alle
  anon_1: 'anonym',  // singular
  anon: 'anonyme',  // plural

  badforum: 'Feil forum',
  c_acc1: 'Din konto gjelder nå for alle nettsider som bruker Muut',
  c_acc: 'Konto bekreftet',
  c_email: 'E-postadresse oppdatert',
  cancel: 'Avbryt',
  change: 'Endre',
  changepw: 'Endre Passord',
  close: 'Lukk',
  collapse: 'Lukk alle',
  comm_count_1: 'kommentar',  // singular: '1 comment'
  comm_count_n: 'kommentarer',  // plural: '3 comments'
  comment1: 'Bli den første som kommenterer…',
  comment: 'Kommenter…',
  edit: 'rediger',
  email: 'E-post',
  email_taken: 'Denne e-postadressen er i bruk' ,
  emailtip: 'Din e-postadresse deles aldri',
  enter: 'ctrl + enter',
  expired1: 'Vi sendte deg nettopp et nytt, vennligst kontroller din e-post.', // http://d.pr/i/1OEV
  expired: 'Lenken er ikke lenger aktiv',

  feed: 'Mine innlegg ', // alternatives: My own, personal


  help2: 'poster',
  help3: 'sitat',
  help5: 'kode, språket gjettes',
  help6: 'HTML-kode',
  in_forum: 'i',
  invalid: 'Ugyldig verdi',
  join: 'Registrer deg',
  later: 'Senere...',
  less: 'færre',
  like: 'Lik',
  likepost: 'Lik dette innlegget',
  loading: 'Laster…',
  login: 'Logg inn',
  login1: 'Logg inn først',
  login_and: 'Logg inn og',

  logout: 'Logg ut',
  mark: 'Støtende eller spam',
  mean: 'Mente du',
  name: 'Visningsnavn',
  nametip: 'Ditt virkelige navn, så folk vet hvem du er',
  newpass: 'Nytt passord',
  noresults: 'Ingen resultater for',
  nospam: 'Ingen spam på ditt forum!',
  notexist: 'eksisterer ikke.',
  ok: 'ok',
  online: 'Online',
  post: 'Post',
  preview: 'Forhåndsvisning',
  progress: ['laster…', 'laster fortsatt…', 'litt til…' , 'gir opp'],
  reconnect: 'kobler til på nytt…',
  removepost: 'Slett',
  reply: 'Svar…',
  replybtn: 'Svar',
  save: 'Lagre endringer',
  saved: 'Lagret',
  search: 'Søk',
  select: 'Velg forum',
  setup: 'Installer nå',
  showing: 'Viser',
  slogan: 'nettforum og kommentarer gjenoppfunnet',
  spam: 'Spam',
  step1: 'Vi har sendt deg en bekreftelse på e-post. Din e-post vil ikke oppdateres før dette steget er fullført!',
  step: 'Ett steg igjen',
  terms: 'Jeg godkjenner <a>Brukeravtalen</a>.',
  thanks: 'Tusen takk!',
  uname_len: 'Skriv 4 tegn eller mer',
  uname_taken: 'Dette brukernavnet er opptatt!',
  unametip: 'Dette kan ikke endraes i etterkant',
  undo: 'Angre',
  unlike: 'Ikke lik',
  unspam: 'Ikke spam',
  unver1: 'Uverifisert konto',
  unver2: 'Vennligst kontroller din e-post for att verifisere din konto.',
  unver3: 'Send en ny verifiseringskode',
  unver4: 'Sendt. Vennligst kontroller din e-post.',
  unver: 'Uverifisert',
  unwall: 'Avslutt alle abonnement',
  unwatch: 'Avslutt abonnement ',
  upgrade2: 'Muut bruker WebSockets eller CORS för kryssdomenekommunikasjon. Alle moderne nettlesere utenom Opera 11 och IE7 fungerer.',
  upgrade: 'Vennligst oppgrader din nettleser',
  username_taken: 'Detta brukernavnet er opptatt',
  watch: 'Abonner på nye svar',
  welcome1: 'Vennligst kontroller din e-post for å sluttføre registreringen. Om du ikke mottar en e-post innne ett minutt eller to, kontroller din spam-folder.',
  welcome2: 'Angi et Muut-brukernavn',
  welcome: 'Velkommen til Muut',
  you: 'Du',

  // times
  now: 'Akkurat nå',
  months: 'Jan,Feb,Mar,Apr,Mai,Jun,Jul,Aug,Sep,Okt,Nov,Des',
  min: 'min',
  hour: 'timer',
  day: 'd',
  week: 'u'

}

