moot.language = {

  // the language code
  $code: 'pt-br',


  /* New stuff */
  my_profile: 'My profile',
  post_in: 'Post in',
  address_now: 'Obrigado! Seu email foi confirmado.',
  open_pw: 'Por Favor, clique no botão abaixo para o procedimento de alteração da senha',
  non_anon: 'Você precisa estar logado para efetuar esta ação',

  plan: 'Plano',
  trial: 'Iniciar teste gratuito',

  is_private: "Esta comunidade é privada",
  owner_msg: "Sua mensagem para o responsável do forum...(Opcional)",
  req_access: "Solicitar acesso",
  req_sent: "Solicitação de acesso enviada",
  or_join: "ou <a>Cadastre-se</a> para ter acesso a comunidade.",
  save_with: "Economize 20% no plano anual",
  rem_post: "Remover este post?",
  is_spam: "Este post é spam?",

  channels: 'Canais',
  ch_name: 'Nome do canal',
  ban:  'Banir usuário',
  banned:  'Banido',
  ban_acc: 'Conta banida',
  ban_msg: 'Você está temporariamente banido desde fórum.',
  days:  'Dias',
  forever: 'Para Sempre',
  slogan:  'Fóruns e comentários gratuitos  por Muut',

  add: '+ Adicionar',
  addons: 'Add-ons',
  myaccount: "Minha conta",
  untitled: "Sem título",
  design: "Design",
  no_title: "Necessário título",
  designer: "Designer",
  developer: "Desenvolvedor",



  img_needed: "Favor carregar um arquivo de imagem",
  max: 'Tamanho máximo de imagem é 4Mb',
  yes: 'Sim',
  upload: 'Carregar imagens',
  show: 'mostrar',
  hide: 'esconder',
  invisible: 'Invisível',
  givebody: 'Corpo não pode estar vazio.',
  show_old: 'Mostrar respostas antigas',
  show_more: 'Mostrar mais respostas',
  show_new: 'Mostrar respostas novas',
  start: 'Iniciar uma nova discussão…',
  error: 'Opa, um erro. Favor copie isto, recarrega a página e tente novamente. Desculpe – ajeitaremos isto!',
  body: 'Corpo do texto',
  admin: 'Admin',
  someone: 'Alguém',
  writing: 'está escrevendo…',
  manage: 'Gerenciar',
  fullview: 'Ver por completo',
  title: 'Título',
  link: 'link',
  avatar: 'Mudar avatar',
  upgrade_link: 'Upgrade',
  branding: 'Branding',
  logo: 'Logo',
  css: 'CSS file',
  single: 'uma palavra',



  /* End new stuff */

  username_fail: 'Use letras, números ou traços',
  bold: 'em negrito',
  italics: 'itálico',
  monospaced: 'monospaçado',
  learn: 'Saiba mais...',
  settings: 'Configurações',
  all: 'Todos os posts', // or alternatively: All
  anon_1: 'anônimo',  // singular
  anon: 'anônimos',  // plural

  badforum: 'Fórum inválido',
  c_acc1: 'Sua conta agora funciona em todos os sites usando Muut',
  c_acc: 'Conta confirmada',
  c_email: 'Email atualizado',
  cancel: 'Cancelar',
  change: 'Alterar',
  changepw: 'Alterar senha',
  close: 'Fechar',
  collapse: 'Reduzir tudo',
  comm_count_1: 'comentário',  // singular: "1 comment"
  comm_count_n: 'comentários',  // plural: "3 comments"
  comment1: 'Seja o primeiro(a) a comentar...',
  comment: 'Comentar...',
  edit: 'editar',
  email: 'Email',
  email_taken: 'Este email já esta sendo usado',
  emailtip: 'Seu email nunca será compartilhado',
  enter: 'ctrl + enter',
  expired1: 'Acabamos de enviar um novo. Por favor verifique seu email.', // http://d.pr/i/1OEV
  expired: 'Link expirado',

  feed: 'Pessoal', // alternatives: My own, personal


  help2: 'post',
  help3: 'texto citado',
  help5: 'código, língua adivinhada',
  help6: 'Código HTML',
  in_forum: 'em',
  invalid: 'Valor inválido',
  join: 'Inscrever-se no Muut',
  later: 'Depois...',
  less: 'menos',
  like: 'Curtir',
  likepost: 'Curtir este post',
  loading: 'Carregando...',
  login: 'Entrar',
  login1: 'Entre primeiro',
  login_and: "Entrar e ",

  logout: 'Sair',
  mark: 'Ofensivo ou spam',
  mean: 'Você quis dizer',
  name: 'Nome de exibição',
  nametip: 'Seu nome verdadeiro, para que as pessoas te reconheçam',
  newpass: 'Nova senha',
  noresults: 'Nenhum resultado para',
  nospam: 'Sem spam no seu fórum!',
  notexist: 'não existe.',
  ok: 'ok',
  online: 'Online',
  post: 'Post',
  preview: 'Visualizar',
  progress: ['carregando...', 'ainda carregando...', 'e carregando...', 'desistindo'],
  reconnect: 'Reconectando...',
  removepost: 'Remover este post',
  reply: 'Responder...',
  replybtn: 'Responder',
  save: 'Salvar alterações',
  saved: 'salvo',
  search: 'Pesquisar',
  select: 'Selecionar fórum',
  setup: 'Configure agora',
  showing: 'Exibindo',
  spam: 'Spam',
  step1: 'Nós te enviamos um email de confirmação. Seu email não será atualizado antes de completar esta etapa!',
  step: 'Mais uma etapa',
  terms: 'Concordo com os <a>termos de serviço</a>.',
  thanks: 'Obrigado!',
  uname_len: 'Digite 4 ou mais caracteres',
  uname_taken: 'Este nome de usuário já esta sendo usado!',
  unametip: 'Não pode ser alterado no futuro',
  undo: 'Desfazer',
  unlike: 'Não curtir',
  unspam: 'Não é spam',
  unver1: 'Conta não verificada',
  unver2: 'Por favor, verifique seu email para ativar sua conta.',
  unver3: 'Novo código de verificação',
  unver4: "Enviado. Verifique seu email.",
  unver: 'Não verificado',
  unwall: 'desacompanhar tudo',
  unwatch: 'Não acompanhar',
  upgrade2: 'Muut usa WebSockets ou CORS para comunicação cross domain. Todos navegadores modernos, exceto Opera 11 e IE7 funcionam.',
  upgrade: 'Por favor atualize seu navegador',
  username_taken: 'Nome de usuário já usado',
  watch: 'Acompanhar este moot',
  welcome1: 'Por favor, verifique seu email para concluir o registro. Se não receber o email entre um ou dois minutos, verifique sua caixa de spam.',
  welcome2: 'Por favor escolha um nome de usuário Muut',
  welcome: 'Bem vindo(a) ao Muut',
  you: 'Você',

  // times
  now: 'agora',
  months: "Jan,Fev,Mar,Abr,Mai,Jun,Jul,Ago,Set,Out,Nov,Dez",
  min: 'm',
  hour: 'h',
  day: 'd',
  week: 'w'

}
