moot.language = {

   // the language code
   $code: 'pt-br',

   all: 'Todos os posts', // or alternatively: All

   anon_1: 'anônimo',    // singular
   anon: 'anônimos',      // plural

   badforum: 'Fórum inválido',
   c_acc1: 'Sua conta agora funciona em todos os sites usando Moot',
   c_acc: 'Conta confirmada',
   c_email: 'Email atualizado',
   cancel: 'Cancelar',
   change: 'Alterar',
   changepw: 'Alterar senha',
   close: 'Fechar',
   collapse: 'Reduzir tudo',
   comm_count_1: 'comentário',   // singular: "1 comment"
   comm_count_n: 'comentários',  // plural: "3 comments"
   comment1: 'Seja o primeiro(a) a comentar...',
   comment: 'Comentar...',
   edit: 'editar',
   email: 'Email',
   email_taken: 'Este email já esta sendo usado',
   emailtip: 'Seu email nunca será compartilhado',
   enter: 'ctrl + enter',
   expired1: 'Acabamos de enviar um novo. Por favor verifique seu email.', // http://d.pr/i/1OEV
   expired: 'Link expirado',

   feed: 'Pessoal', // alternatives: My own, personal

   forumname: 'Nome do fórum',
   forums: 'Fóruns',
   help1: 'Primeira linha é o título',
   help2: 'post',
   help3: 'texto citado',
   help4: 'segunda linha',
   help5: 'código, língua adivinhada',
   help6: 'Código HTML',
   in_forum: 'em',
   invalid: 'Valor inválido',
   join: 'Inscrever-se no Moot',
   later: 'Depois...',
   less: 'menos',
   like: 'Curtir',
   likepost: 'Curtir este post',
   loading: 'Carregando...',
   login: 'Entrar',
   login1: 'Entre primeiro',
   login_and: "Entrar e ",

   logout: 'Sair',
   mark: 'Ofensivo ou spam',
   mean: 'Você quis dizer',
   name: 'Nome de exibição',
   nametip: 'Seu nome verdadeiro, para que as pessoas te reconheçam',
   newcat: 'Nova categoria',
   newpass: 'Nova senha',
   noresults: 'Nenhum resultado para',
   nospam: 'Sem spam no seu fórum!',
   notexist: 'não existe.',
   notify: 'Me avise sobre novidades',
   ok: 'ok',
   online: 'Online',
   post: 'Post',
   preview: 'Visualizar',
   progress: ['carregando...', 'ainda carregando...', 'e carregando...', 'desistindo'],
   reconnect: 'Reconectando...',
   removecat: 'Remover. Os posts não serão removidos',
   removepost: 'Remover este post',
   reply: 'Responder...',
   replybtn: 'Responder',
   save: 'Salvar alterações',
   saved: 'salvo',
   search: 'Pesquisar',
   select: 'Selecionar fórum',
   setup: 'Configure agora',
   showing: 'Exibindo',
   slogan: 'Fóruns e comentários re-imaginados',
   spam: 'Spam',
   start: 'E ai?',
   step1: 'Nós te enviamos um email de confirmação. Seu email não será atualizado antes de completar esta etapa!',
   step: 'Mais uma etapa',
   terms: 'Concordo com os <a>termos de serviço</a>.',
   thanks: 'Obrigado!',
   uname_len: 'Digite 6 ou mais caracteres',
   uname_taken: 'Este nome de usuário já esta sendo usado!',
   unametip: 'Não pode ser alterado no futuro',
   undo: 'Desfazer',
   unlike: 'Não curtir',
   unspam: 'Não é spam',
   unver1: 'Conta não verificada',
   unver2: 'Por favor, verifique seu email para ativar sua conta. Usuários verificados podem acessar moots e receber notificações por email. <a>Novo código de verificação...</a>',
   unver3: '<a>Enviar novo</a> código de verificação para:',
   unver4: "Enviado. Verifique seu email.",
   unver: 'Não verificado',
   unwall: 'desacompanhar tudo',
   unwatch: 'Não acompanhar',
   upgrade2: 'Moot usa WebSockets ou CORS para comunicação cross domain. Todos navegadores modernos, exceto Opera 11 e IE7 funcionam.',
   upgrade: 'Por favor atualize seu navegador',
   username_taken: 'Nome de usuário já usado',
   watch: 'Acompanhar este moot',
   welcome1: 'Por favor, verifique seu email para concluir o registro. Se não receber o email entre um ou dois minutos, verifique sua caixa de spam.',
   welcome2: 'Por favor escolha um nome de usuário Moot',
   welcome: 'Bem vindo(a) ao Moot',
   you: 'Você',

   // times
   now: 'agora',
   months: "Jan,Fev,Mar,Abr,Mai,Jun,Jul,Ago,Set,Out,Nov,Dez",
   min: 'm',
   hour: 'h',
   day: 'd',
   week: 'w'

}
