moot.language = {

   // the language code
   $code: 'pt',

   /* New stuff */
   mods:    'Moderators',
   ban:     'Ban user',
   banned:  'Banned',
   ban_usr: 'Banned users',
   ban_acc: 'Banned account',
   ban_msg: 'You are temporarily banned from posting on this forum.',
   days:    'Days',
   forever: 'Forever',
   slogan:  'Free forums and commenting by Muut',

   add: '+ Add',
   addons: 'Add-ons',
   myaccount: "My account",
   untitled: "Untitled",
   design: "Design",
   no_title: "Title must be given",
   designer: "Designer",
   developer: "Developer",

   no_index: 'Disable indexing under muut.com',
   mkpriv: 'Make this forum private',
   sign: 'This forum must be <a>signed</a> first.',

   s3: 'Custom S3 bucket',
   s3_tip: 'Allows custom domain for search engines and a backup storage.',
   s3_tip2: 'Add full access permissions for <em>moot-aws@moot.it</em>',
   s3_no_access: "moot-aws@moot.it cannot access this bucket",
   s3_missing: "This bucket does not exist",

   img_needed: "Please upload an image file",
   max: 'Maximum image size is 4Mb',
   yes: 'Yes',
   upload: 'Upload images',
   show: 'show',
   hide: 'hide',
   invisible: 'Invisible',
   givebody: 'Body cannot be empty.',
   show_old: 'Show oldest replies',
   show_more: 'Show more replies',
   show_new: 'Show newest replies',
   start: 'Start a new topic...',
   error: 'Oops, an error. Please copy the post to clipboard, reload and try again. Sorry – we will fix this!',
   body: 'Body text',
   admin: 'Admin',
   someone: 'Someone',
   writing: 'is writing...',
   basic: 'Basic (free)',
   subs: 'Subscriptions',
   manage: 'Manage',
   fullview: 'Full view',
   title: 'Title',
   link: 'link',
   avatar: 'Alterar avatar',
   seo_update: 'The SEO pages will be updated within the hour',
   upgrade_link: 'Actualizar',
   branding: 'Branding',
   logo: 'Logo',
   bgcolor: 'Background color',
   css: 'CSS file',
   mootbrand: 'Use Muut branding',
   sso: 'Single Sign-On',
   apikey: 'API key',
   apisecret: 'Secret key',
   single: 'single word',



   /* End new stuff */

   username_fail: 'Use letras, números ou hifens',
   bold: 'negrito',
   italics: 'itálico',
   monospaced: 'espaço',
   domain: 'URL do fórum',
   domaintip: 'URL do fórum onde os utilizadores são direcionados a partir dos resultados da pesquisa',
   learn: 'Saiba mais...',
   ga: 'Id Google Analytics',
   admins: 'Administradores',
   adminstip: 'Um utilizador por linha',
   settings: 'Configurações',
   all: 'Todos os posts', // or alternatively: All
   anon_1: 'anônimo',    // singular
   anon: 'anônimos',      // plural

   badforum: 'Fórum inválido',
   c_acc1: 'A sua conta agora funciona em todos os sites que usam o Muut',
   c_acc: 'Conta validada',
   c_email: 'Email atualizado',
   cancel: 'Cancelar',
   change: 'Alterar',
   changepw: 'Alterar palavra-passe',
   close: 'Fechar',
   collapse: 'Reduzir tudo',
   comm_count_1: 'comentário',   // singular: "1 comment"
   comm_count_n: 'comentários',  // plural: "3 comments"
   comment1: 'Seja o primeiro(a) a comentar...',
   comment: 'Comentar...',
   edit: 'editar',
   email: 'Email',
   email_taken: 'Este email já está a ser usado',
   emailtip: 'Seu email nunca será partilhado',
   enter: 'ctrl + enter',
   expired1: 'Acabamos de enviar um novo email. Por favor verifique a sua conta de email.', // http://d.pr/i/1OEV
   expired: 'Link expirado',

   feed: 'Pessoal', // alternatives: My own, personal

   forumname: 'Nome do fórum',
   forums: 'Fóruns',

   help2: 'post',
   help3: 'texto citado',
   help5: 'código, detectar idioma',
   help6: 'Código HTML',
   in_forum: 'em',
   invalid: 'Valor incorrecto',
   join: 'Inscrever-se no Muut',
   later: 'Depois...',
   less: 'menos',
   like: 'Gostar',
   likepost: 'Gostar deste post',
   loading: 'A carregar...',
   login: 'Entrar',
   login1: 'Entre primeiro',
   login_and: "Entrar e ",

   logout: 'Sair',
   mark: 'Ofensivo ou spam',
   mean: 'Você quis dizer',
   name: 'Nome a mostrar',
   nametip: 'Utilize o seu nome verdadeiro, para que as pessoas te reconheçam',
   newcat: 'Nova categoria',
   newpass: 'Nova palavra-passe',
   noresults: 'Nenhum resultado para',
   nospam: 'Sem spam no seu fórum!',
   notexist: 'não existe.',
   notify: 'Avise-me sobre as novidades',
   ok: 'ok',
   online: 'Online',
   post: 'Post',
   preview: 'Visualizar',
   progress: ['A carregar...', 'ainda a carregar...', 'e a carregar...', 'desisto'],
   reconnect: 'A ligar...',
   removecat: 'Remover. Os posts não serão removidos',
   removepost: 'Remover este post',
   reply: 'Responder...',
   replybtn: 'Responder',
   save: 'Guardar alterações',
   saved: 'Guardado',
   search: 'Pesquisar',
   select: 'Selecionar fórum',
   setup: 'Configure agora',
   showing: 'Mostrar',
   spam: 'Spam',

   step1: 'Vai ser enviado um email de confirmação. A sua conta de email não será atualizada antes de completar esta fase!',
   step: 'Mais uma fase',
   terms: 'Concordo com os <a>termos de serviço</a>.',
   thanks: 'Obrigado!',
   uname_len: 'Digite 6 ou mais caracteres',
   uname_taken: 'Este nome de utilizador já está a ser usado!',
   unametip: 'Não pode ser alterado no futuro',
   undo: 'Voltar atrás',
   unlike: 'Não gosto',
   unspam: 'Não é spam',
   unver1: 'Conta não validada',
   unver2: 'Por favor, verifique a sua conta de email para ativar a conta de utilizador. Os utilizadores validados podem aceder ao moots e receber notificações por email. <a>Novo código de validação...</a>',
   unver3: '<a>Enviar novo</a> código de validação para:',
   unver4: "Enviado. Verifique a sua conta email.",
   unver: 'Não foi validada',
   unwall: 'não seguir tudo',
   unwatch: 'Não seguir',
   upgrade2: 'Muut usa WebSockets ou CORS para comunicação cross domain. Funciona em todos os navegadores actuais, exceto Opera 11 e IE7.',
   upgrade: 'Por favor atualize o seu navegador - F5',
   username_taken: 'Nome de utilizador já está registado',
   watch: 'Acompanhar este moot',
   welcome1: 'Por favor, verifique a sua conta de email para concluir o registro. Se não receber o email dentro de um ou dois minutos, verifique a caixa de spam.',
   welcome2: 'Por favor escolha um nome de utilizador Muut',
   welcome: 'Bem vindo(a) ao Muut',
   you: 'Você',

   // times
   now: 'agora',
   months: "Jan,Fev,Mar,Abr,Mai,Jun,Jul,Ago,Set,Out,Nov,Dez",
   min: 'm',
   hour: 'h',
   day: 'd',
   week: 'w'

}
