moot.language = {

  // the language code
  $code: 'pt',

  /* New stuff */
  no_notify: 'Disable all email notifications',
  watchall: 'Watch for all new threads',
  move: 'Move thread',
  moved: 'Thread moved',
  custom_path1: 'Custom path',
  custom_path: 'Enter custom path',
  invalid_path: 'Invalid custom path',
  from: 'From',
  to: 'To',

  retire: 'Retire',
  retire_title: 'Retire thread',
  retire_desc: 'Retired threads no longer get bumped to top in the feeds they appear in.',
  retired_desc: 'This thread is retired. New replies no longer bump it to the top of the feed.',
  is_retired: 'This thread has been retired',

  unretire: 'Unretire',
  unretire_title: 'Unretire thread',
  unretire_desc: 'This thread will be bumped to top in the feeds they appear in.',
  quote_help1: 'Select',
  quote_help2: 'to quote or share',

  trial_left: 'left of free trial.',
  after_trial: 'After the trial ends you can continue using Muut with the',
  free_plan: 'Free plan',
  reward: 'Referral reward',
  off33: 'Upgrade now and get 33% off all our paid plans!',
  spread: 'Spread the word!',
  invite: 'Invite a friend to start a Muut community and you’ll both get rewarded!',
  start_now: 'Start your own community now – it\'s free!',
  start_btn: 'Create',
  reserve: 'Reserve your forum name',
  free_acc: 'Free account',
  no_dialog: 'and remove this dialogue',
  click_change: 'Click to change',

  moderator: 'Moderator',
  mkadmin: 'Make administrator',
  mkmod: 'Make moderator',
  upgrade_mod: 'to make this user a moderator',
  upgrade_admin: 'to make this user administrator or moderator',

  my_profile: 'My profile',
  post_in: 'Post in',
  address_now: 'Thank you! Your email address has been confirmed.',
  open_pw: 'Please hit the button below to open a password change dialog',
  non_anon: 'You need to be logged in to perform this action',

  plan: 'Plan',
  trial: 'Start free trial',

  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spam?",

  channels: 'Channels',
  ch_name: 'Channel name',
  ban:  'Ban user',
  banned:  'Banned',
  ban_acc: 'Banned account',
  ban_msg: 'You are temporarily banned from posting on this forum.',
  days:  'Days',
  forever: 'Forever',
  slogan:  'Free forums and commenting by Muut',

  add: '+ Add',
  addons: 'Add-ons',
  myaccount: "Account",
  untitled: "Untitled",
  design: "Design",
  no_title: "Title must be given",
  designer: "Designer",
  developer: "Developer",



  img_needed: "Please upload an image file",
  max: 'Maximum image size is 4Mb',
  yes: 'Yes',
  upload: 'Upload images',
  show: 'show',
  hide: 'hide',
  invisible: 'Invisible',
  givebody: 'Body cannot be empty.',
  show_old: 'Show oldest replies',
  show_more: 'Show more replies',
  show_new: 'Show newest replies',
  start: 'Start a new topic...',
  error: 'Oops, an error. Please copy the post to clipboard, reload and try again. Sorry – we will fix this!',
  body: 'Body text',
  admin: 'Admin',
  someone: 'Someone',
  writing: 'is writing...',
  manage: 'Manage',
  fullview: 'Full view',
  title: 'Title',
  link: 'link',
  avatar: 'Alterar avatar',
  upgrade_link: 'Actualizar',
  branding: 'Branding',
  logo: 'Logo',
  css: 'CSS file',
  single: 'single word',



  /* End new stuff */

  username_fail: 'Use letras, números ou hifens',
  bold: 'negrito',
  italics: 'itálico',
  monospaced: 'espaço',
  learn: 'Saiba mais...',
  settings: 'Configurações',
  all: 'Todos os posts', // or alternatively: All
  anon_1: 'anônimo',  // singular
  anon: 'anônimos',  // plural

  badforum: 'Fórum inválido',
  c_acc1: 'A sua conta agora funciona em todos os sites que usam o Muut',
  c_acc: 'Conta validada',
  c_email: 'Email atualizado',
  cancel: 'Cancelar',
  change: 'Alterar',
  changepw: 'Alterar palavra-passe',
  close: 'Fechar',
  collapse: 'Reduzir tudo',
  comm_count_1: 'comentário',  // singular: "1 comment"
  comm_count_n: 'comentários',  // plural: "3 comments"
  comment1: 'Seja o primeiro(a) a comentar...',
  comment: 'Comentar...',
  edit: 'editar',
  email: 'Email',
  email_taken: 'Este email já está a ser usado',
  emailtip: 'Seu email nunca será partilhado',
  enter: 'ctrl + enter',
  expired1: 'Acabamos de enviar um novo email. Por favor verifique a sua conta de email.', // http://d.pr/i/1OEV
  expired: 'Link expirado',

  feed: 'Pessoal', // alternatives: My own, personal


  help2: 'post',
  help3: 'texto citado',
  help5: 'código, detectar idioma',
  help6: 'Código HTML',
  in_forum: 'em',
  invalid: 'Valor incorrecto',
  join: 'Inscrever-se no Muut',
  later: 'Depois...',
  less: 'menos',
  like: 'Gostar',
  likepost: 'Gostar deste post',
  loading: 'A carregar...',
  login: 'Entrar',
  login1: 'Entre primeiro',
  login_and: "Entrar e ",

  logout: 'Sair',
  mark: 'Ofensivo ou spam',
  mean: 'Você quis dizer',
  name: 'Nome a mostrar',
  nametip: 'Utilize o seu nome verdadeiro, para que as pessoas te reconheçam',
  newpass: 'Nova palavra-passe',
  noresults: 'Nenhum resultado para',
  nospam: 'Sem spam no seu fórum!',
  notexist: 'não existe.',
  ok: 'ok',
  online: 'Online',
  post: 'Post',
  preview: 'Visualizar',
  progress: ['A carregar...', 'ainda a carregar...', 'e a carregar...', 'desisto'],
  reconnect: 'A ligar...',
  removepost: 'Remover este post',
  reply: 'Responder...',
  replybtn: 'Responder',
  save: 'Guardar alterações',
  saved: 'Guardado',
  search: 'Pesquisar',
  select: 'Selecionar fórum',
  setup: 'Configure agora',
  showing: 'Mostrar',
  spam: 'Spam',

  step1: 'Vai ser enviado um email de confirmação. A sua conta de email não será atualizada antes de completar esta fase!',
  step: 'Mais uma fase',
  terms: 'Concordo com os <a>termos de serviço</a>.',
  thanks: 'Obrigado!',
  uname_len: 'Digite 4 ou mais caracteres',
  uname_taken: 'Este nome de utilizador já está a ser usado!',
  unametip: 'Não pode ser alterado no futuro',
  undo: 'Voltar atrás',
  unlike: 'Não gosto',
  unspam: 'Não é spam',
  unver1: 'Conta não validada',
  unver2: 'Por favor, verifique a sua conta de email para ativar a conta de utilizador.',
  unver3: 'Novo código de validação',
  unver4: "Enviado. Verifique a sua conta email.",
  unver: 'Não foi validada',
  unwall: 'não seguir tudo',
  unwatch: 'Não seguir',
  upgrade2: 'Muut usa WebSockets ou CORS para comunicação cross domain. Funciona em todos os navegadores actuais, exceto Opera 11 e IE7.',
  upgrade: 'Por favor atualize o seu navegador - F5',
  username_taken: 'Nome de utilizador já está registado',
  watch: 'Acompanhar este moot',
  welcome1: 'Por favor, verifique a sua conta de email para concluir o registro. Se não receber o email dentro de um ou dois minutos, verifique a caixa de spam.',
  welcome2: 'Por favor escolha um nome de utilizador Muut',
  welcome: 'Bem vindo(a) ao Muut',
  you: 'Você',

  // times
  now: 'agora',
  months: "Jan,Fev,Mar,Abr,Mai,Jun,Jul,Ago,Set,Out,Nov,Dez",
  min: 'm',
  hour: 'h',
  day: 'd',
  week: 's'

}
