moot.language = {

  // the language code
  $code: 'ro',

  /* New stuff */
  address_now: 'Your address is now: ',
  open_pw: 'Please hit the button below to open a password change dialog',
  non_anon: 'You need to be logged in to perform this action',

  plan: 'Plan',
  trial: 'Start free trial',

  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spam?",

  channels: 'Channels',
  ch_name: 'Channel name',
  ban:  'Ban user',
  banned:  'Banned',
  days:  'Days',
  forever: 'Forever',
  slogan:  'Free forums and commenting by Muut',

  add: '+ Add',
  addons: 'Add-ons',
  myaccount: "My account",
  untitled: "Untitled",
  design: "Design",
  no_title: "Title must be given",
  designer: "Designer",
  developer: "Developer",



  img_needed: "Please upload an image file",
  max: 'Maximum image size is 4Mb',
  yes: 'Yes',
  upload: 'Upload images',
  show: 'show',
  hide: 'hide',
  invisible: 'Invisible',

  ban_acc: 'Cont suspendat',
  ban_msg: 'Esti suspendat temporar si nu mai poti scrie pe acest forum, deoarece nu ai respectat regulile. A mai ramas:',
  banned4: 'Nu mai poti scrie pe acest forum.',
  warning: 'Atentie',
  profanity: 'Nu putem permite lipsa de respect. Abuzul continuat va duce la suspendarea definitiva a contului.',

  givebody: 'Textul nu poate fi gol.',
  show_old: 'Arata raspunsurile cele mai vechi',
  show_more: 'Arata mai multe raspunsuri',
  show_new: 'Arata raspunsurile cele mai noi',
  start: 'Porneste o discutie noua...',
  error: 'Oops, o eroare. Te rog da "copy" la text, reincarca pagina si da "paste" pentru a incerca din nou. Ne pare rau - o sa rezolvam!',
  body: 'Text',
  admin: 'Admin',
  someone: 'Cineva',
  title: 'Titlu',
  writing: 'scrie...',
  manage: 'Manage',
  fullview: 'Complet',
  link: 'link',
  avatar: 'Schimba imagine',
  upgrade_link: 'Upgrade',
  branding: 'Branding',
  logo: 'Logo',
  title: 'Titlu',
  css: 'Fisier CSS',
  single: 'cuvant simplu',
  /* End new stuff */



  username_fail: 'Foloseste doar litere, numere si cratima',
  bold: 'bold',
  italics: 'italic',
  monospaced: 'monospace',
  learn: 'Afla mai mult...',
  settings: 'Setari',

  all: 'Toate', // or alternatively: All
  anon_1: 'anonim',  // singular
  anon: 'anonimi',  // plural

  badforum: 'Forum invalid',
  c_acc1: 'Contul tau merge acum pe toate site-urile care folosesc Muut',
  c_acc: 'Cont confirmat!',
  c_email: 'Email nou salvat',
  cancel: 'Anuleaza',
  change: 'Schimba',
  changepw: 'Schimba parola',
  close: 'Inchide',
  collapse: 'Inchide tot',
  comm_count_1: 'comentariu',  // singular: "1 comment"
  comm_count_n: 'comentarii',  // plural: "3 comments"
  comment1: 'Pune primul comentariu...',
  comment: 'Comenteaza...',
  edit: 'editeaza',
  email: 'Email',
  email_taken: 'Acest email e folosit deja',
  emailtip: 'Email-ul tau va ramane confidential',
  enter: 'ctrl + enter',
  expired1: 'Ti-am trimis unul nou, verifica pe mail.', // http://d.pr/i/1OEV
  expired: 'Acest link a expirat',

  feed: 'Personal', // alternatives: My own, personal


  help2: 'post',
  help3: 'citat',
  help5: 'cod',
  help6: 'HTML',
  in_forum: 'in',
  invalid: 'Valoare invalida',
  join: 'Intra pe Muut',
  later: 'Mai tarziu...',
  less: 'mai putin',
  like: 'Like',
  likepost: 'Like',
  loading: 'Incarca...',
  login: 'Login',
  login1: 'Login primul',
  login_and: "Login si",

  logout: 'Log out',
  mark: 'Offensive or spam',
  mean: 'Ai vrut sa spui',
  name: 'Display name',
  nametip: 'Numele tau real, ca oamenii sa te recunoasca',
  newpass: 'Parola noua',
  noresults: 'Nu sunt rezultate pentru',
  nospam: 'Forumul tau nu are spam!',
  notexist: 'nu exista.',
  notify: 'Anunta-ma cand apar versiuni noi',
  ok: 'ok',
  online: 'Online',
  post: 'Post',
  preview: 'Preview',
  progress: ['incarca...', 'inca se incarca...', 'inca putin...', 'am renuntat'],
  reconnect: 'Se re-conecteaza...',
  removepost: 'Sterge',
  reply: 'Raspunde...',
  replybtn: 'Raspunde',
  save: 'Salveaza schimbarile',
  saved: 'salvat',
  search: 'Cauta',
  select: 'Selecteaza forum',
  setup: 'Seteaza acum',
  showing: 'Afisate',
  spam: 'Spam',
  step1: 'Ti-am trimis un email de verificare. Nu vom salva noua adresa pana nu o verifici!',
  step: 'Inca un pas',
  terms: 'Sunt de acord cu <a>termenii si conditiile</a>.',
  thanks: 'Mersi!',
  uname_len: 'Scrie 4 caractere sau mai mult!',
  uname_taken: 'Acest nume e folosit!',
  unametip: 'Nu va putea fi schimbat mai tarziu',
  undo: 'Undo',
  unlike: 'Unlike',
  unspam: 'Nu e spam',
  unver1: 'Cont ne-verificat',
  unver2: 'Te rog verifica-ti emailul pentru a valida contul.',
  unver3: 'Trimite din nou codul de verificare',
  unver4: "Trimis. Verifica-ti emailul.",
  unver: 'Nu e verificat',
  unwall: 'nu mai urmari nimic',
  unwatch: 'nu mai urmari',
  upgrade2: 'Muut foloseste WebSockets sau CORS pentru comunicare intre domenii diferite. Functioneaza toate browserele moderne peste Opera 11 si IE7.',
  upgrade: 'Va trebui sa folosesti un browser mai nou.',
  username_taken: 'Acest username este deja folosit de altcineva',
  watch: 'Urmareste discutia pe email',
  welcome1: 'Te rugam sa verifici emailul pentru a termina inregistrarea. Daca nu primesti un mail in cateva minute, verifica folderul de spam.',
  welcome2: 'Te rog sa ne dai un username pentru Muut.',
  welcome: 'Bine ai venit pe Muut',
  you: 'Tu',

  // times
  now: 'acum',
  months: "Ian,Feb,Mar,Apr,Mai,Iun,Iul,Aug,Sep,Oct,Noi,Dec",
  min: 'm',
  hour: 'o',
  day: 'z',
  week: 's'

}
