moot.language = {

   // the language code
   $code: 'ro',

   /* New stuff */
   ban:     'Ban user',
   banned:  'Banned',
   ban_usr: 'Banned users',
   days:    'Days',
   forever: 'Forever',
   slogan:  'Free forums and commenting by Muut',

   add: '+ Add',
   addons: 'Add-ons',
   myaccount: "My account",
   untitled: "Untitled",
   design: "Design",
   no_title: "Title must be given",
   designer: "Designer",
   developer: "Developer",

   no_index: 'Disable indexing under muut.com',
   mkpriv: 'Make this forum private',
   sign: 'This forum must be <a>signed</a> first.',

   s3: 'Custom S3 bucket',
   s3_tip: 'Allows custom domain for search engines and a backup storage.',
   s3_tip2: 'Add full access permissions for <em>moot-aws@moot.it</em>',
   s3_no_access: "moot-aws@moot.it cannot access this bucket",
   s3_missing: "This bucket does not exist",

   img_needed: "Please upload an image file",
   max: 'Maximum image size is 4Mb',
   yes: 'Yes',
   upload: 'Upload images',
   show: 'show',
   hide: 'hide',
   invisible: 'Invisible',

   ban_acc: 'Cont suspendat',
   ban_msg: 'Esti suspendat temporar si nu mai poti scrie pe acest forum, deoarece nu ai respectat regulile. A mai ramas:',
   banned4: 'Nu mai poti scrie pe acest forum.',
   warning: 'Atentie',
   profanity: 'Nu putem permite lipsa de respect. Abuzul continuat va duce la suspendarea definitiva a contului.',

   givebody: 'Textul nu poate fi gol.',
   show_old: 'Arata raspunsurile cele mai vechi',
   show_more: 'Arata mai multe raspunsuri',
   show_new: 'Arata raspunsurile cele mai noi',
   start: 'Porneste o discutie noua...',
   error: 'Oops, o eroare. Te rog da "copy" la text, reincarca pagina si da "paste" pentru a incerca din nou. Ne pare rau - o sa rezolvam!',
   body: 'Text',
   admin: 'Admin',
   someone: 'Cineva',
   title: 'Titlu',
   writing: 'scrie...',
   basic: 'Basic (gratuit)',
   subs: 'Abonati',
   manage: 'Manage',
   fullview: 'Complet',
   link: 'link',
   avatar: 'Schimba imagine',
   seo_update: 'Paginile SEO vor fi updatate intr-o ora',
   upgrade_link: 'Upgrade',
   branding: 'Branding',
   logo: 'Logo',
   bgcolor: 'Culoare de fundal',
   brand_name: 'Brand',
   title: 'Titlu',
   css: 'Fisier CSS',
   mootbrand: 'Foloseste branding Muut',
   sso: 'Single Sign-On',
   apikey: 'API key',
   apisecret: 'Cheie secreta',
   single: 'cuvant simplu',
   /* End new stuff */



   username_fail: 'Foloseste doar litere, numere si cratima',
   bold: 'bold',
   italics: 'italic',
   monospaced: 'monospace',
   domain: 'Linkul forumului',
   domaintip: 'Link-ul complet la forumurile unde sunt trimisi userii din rezultatele de cautare',
   learn: 'Afla mai mult...',
   ga: 'Google Analytics Id',
   admins: 'Administratori',
   adminstip: 'Un username pe linie',
   settings: 'Setari',

   all: 'Toate', // or alternatively: All
   anon_1: 'anonim',    // singular
   anon: 'anonimi',      // plural

   badforum: 'Forum invalid',
   c_acc1: 'Contul tau merge acum pe toate site-urile care folosesc Muut',
   c_acc: 'Cont confirmat!',
   c_email: 'Email nou salvat',
   cancel: 'Anuleaza',
   change: 'Schimba',
   changepw: 'Schimba parola',
   close: 'Inchide',
   collapse: 'Inchide tot',
   comm_count_1: 'comentariu',   // singular: "1 comment"
   comm_count_n: 'comentarii',  // plural: "3 comments"
   comment1: 'Pune primul comentariu...',
   comment: 'Comenteaza...',
   edit: 'editeaza',
   email: 'Email',
   email_taken: 'Acest email e folosit deja',
   emailtip: 'Email-ul tau va ramane confidential',
   enter: 'ctrl + enter',
   expired1: 'Ti-am trimis unul nou, verifica pe mail.', // http://d.pr/i/1OEV
   expired: 'Acest link a expirat',

   feed: 'Personal', // alternatives: My own, personal

   forumname: 'Nume forum',
   forums: 'Forumuri',

   help2: 'post',
   help3: 'citat',
   help5: 'cod',
   help6: 'HTML',
   in_forum: 'in',
   invalid: 'Valoare invalida',
   join: 'Intra pe Muut',
   later: 'Mai tarziu...',
   less: 'mai putin',
   like: 'Like',
   likepost: 'Like',
   loading: 'Incarca...',
   login: 'Login',
   login1: 'Login primul',
   login_and: "Login si",

   logout: 'Log out',
   mark: 'Offensive or spam',
   mean: 'Ai vrut sa spui',
   name: 'Display name',
   nametip: 'Numele tau real, ca oamenii sa te recunoasca',
   newcat: 'Categorie noua',
   newpass: 'Parola noua',
   noresults: 'Nu sunt rezultate pentru',
   nospam: 'Forumul tau nu are spam!',
   notexist: 'nu exista.',
   notify: 'Anunta-ma cand apar versiuni noi',
   ok: 'ok',
   online: 'Online',
   post: 'Post',
   preview: 'Preview',
   progress: ['incarca...', 'inca se incarca...', 'inca putin...', 'am renuntat'],
   reconnect: 'Se re-conecteaza...',
   removecat: 'Sterge. Posturile nu vor fi sterse',
   removepost: 'Sterge',
   reply: 'Raspunde...',
   replybtn: 'Raspunde',
   save: 'Salveaza schimbarile',
   saved: 'salvat',
   search: 'Cauta',
   select: 'Selecteaza forum',
   setup: 'Seteaza acum',
   showing: 'Afisate',
   spam: 'Spam',
   step1: 'Ti-am trimis un email de verificare. Nu vom salva noua adresa pana nu o verifici!',
   step: 'Inca un pas',
   terms: 'Sunt de acord cu <a>termenii si conditiile</a>.',
   thanks: 'Mersi!',
   uname_len: 'Scrie 6 caractere sau mai mult!',
   uname_taken: 'Acest nume e folosit!',
   unametip: 'Nu va putea fi schimbat mai tarziu',
   undo: 'Undo',
   unlike: 'Unlike',
   unspam: 'Nu e spam',
   unver1: 'Cont ne-verificat',
   unver2: 'Te rog verifica-ti emailul pentru a valida contul. Utilizatorii verificati pot urmari post-uri pe email. <a>Trimite din nou codul de verificare...</a>',
   unver3: '<a>Trimite</a> codul de verificare la:',
   unver4: "Trimis. Verifica-ti emailul.",
   unver: 'Nu e verificat',
   unwall: 'nu mai urmari nimic',
   unwatch: 'nu mai urmari',
   upgrade2: 'Muut foloseste WebSockets sau CORS pentru comunicare intre domenii diferite. Functioneaza toate browserele moderne peste Opera 11 si IE7.',
   upgrade: 'Va trebui sa folosesti un browser mai nou.',
   username_taken: 'Acest username este deja folosit de altcineva',
   watch: 'Urmareste discutia pe email',
   welcome1: 'Te rugam sa verifici emailul pentru a termina inregistrarea. Daca nu primesti un mail in cateva minute, verifica folderul de spam.',
   welcome2: 'Te rog sa ne dai un username pentru Muut.',
   welcome: 'Bine ai venit pe Muut',
   you: 'Tu',

   // times
   now: 'acum',
   months: "Ian,Feb,Mar,Apr,Mai,Iun,Iul,Aug,Sep,Oct,Noi,Dec",
   min: 'm',
   hour: 'o',
   day: 'z',
   week: 's'

}
