moot.language = {

  // the language code
  $code: 'se',

  // new stuff
  move: 'Move thread',
  moved: 'Thread moved',
  custom_path1: 'Custom path',
  custom_path: 'Enter custom path',
  invalid_path: 'Invalid custom path',
  from: 'From',
  to: 'To',

  retire: 'Retire',
  retire_title: 'Retire thread',
  retire_desc: 'Retired threads no longer get bumped to top in the feeds they appear in.',
  retired_desc: 'This thread is retired. New replies no longer bump it to the top of the feed.',
  is_retired: 'This thread has been retired',

  unretire: 'Unretire',
  unretire_title: 'Unretire thread',
  unretire_desc: 'This thread will be bumped to top in the feeds they appear in.',
  quote_help1: 'Select',
  quote_help2: 'to quote or share',

  trial_left: 'left of free trial.',
  after_trial: 'After the trial ends you can continue using Muut with the',
  free_plan: 'Free plan',
  reward: 'Referral reward',
  off33: 'Upgrade now and get 33% off all our paid plans!',
  spread: 'Spread the word!',
  invite: 'Invite a friend to start a Muut community and you’ll both get rewarded!',
  start_now: 'Start your own community now – it\'s free!',
  start_btn: 'Create',
  reserve: 'Reserve your forum name',
  free_acc: 'Free account',
  no_dialog: 'and remove this dialogue',
  click_change: 'Click to change',

  moderator: 'Moderator',
  mkadmin: 'Make administrator',
  mkmod: 'Make moderator',
  upgrade_mod: 'to make this user a moderator',
  upgrade_admin: 'to make this user administrator or moderator',

  my_profile: 'Min profil',
  post_in: 'Post in',
  address_now: 'Thank you! Your email address has been confirmed.',
  open_pw: 'Please hit the button below to open a password change dialog',
  non_anon: 'You need to be logged in to perform this action',

  plan: 'Plan',
  trial: 'Start free trial',

  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spam?",

  channels: 'Channels',
  ch_name: 'Channel name',
  ban:  'Ban user',
  banned:  'Banned',
  ban_acc: 'Banned account',
  ban_msg: 'You are temporarily banned from posting on this forum.',
  days:  'Days',
  forever: 'Forever',
  slogan:  'Free forums and commenting by Muut',

  add: '+ Add',
  addons: 'Add-ons',
  myaccount: "Account",
  untitled: "Untitled",
  design: "Design",
  no_title: "Title must be given",
  designer: "Designer",
  developer: "Developer",



  img_needed: "Please upload an image file",
  max: 'Maximum image size is 4Mb',
  yes: 'Yes',
  upload: 'Upload images',
  show: 'show',
  hide: 'hide',


  invisible: 'Invisible',
  givebody: 'Brödtexten får inte vara tom',
  show_old: 'Visa äldsta svar',
  show_more: 'Visa fler svar',
  show_new: 'Visa senaste svar',
  start: 'Starta ny diskussionstråd',
  error: 'Oops, ett fel uppstod. Kopiera inlägget till clipboard, ladda om sidan och försök igen. Beklagar – vi kommer fixa detta!',
  body: 'Brödtext',
  admin: 'Admin',
  someone: 'Någon',
  writing: 'skriver...',
  manage: 'Hantera',
  fullview: 'Fullständig vy',
  title: 'Rubrik',
  link: 'länk',
  single: 'enkelord',


  username_fail: 'Använd bokstäver, siffror eller bindestreck',
  avatar: 'Ändra avatar',
  upgrade_link: 'Uppgradera',
  branding: 'Branding',
  logo: 'Logotyp',
  css: 'CSS-fil',

  bold: 'fet',
  italics: 'kursiv',
  monospaced: 'monospace',
  learn: 'Lär dig mer...',
  settings: 'Inställningar',

  all: 'Alla inlägg', // or alternatively: All
  anon_1: 'anonym',  // singular
  anon: 'anonyma',  // plural

  badforum: 'Felaktigt forum',
  c_acc1: 'Ditt konto fungerar nu på alla sajter som använder Muut',
  c_acc: 'Kontot bekräftat',
  c_email: 'E-postadress uppdaterad',
  cancel: 'Avbryt',
  change: 'Ändra',
  changepw: 'Ändra lösenord',
  close: 'Stäng',
  collapse: 'Fäll ihop alla',
  comm_count_1: 'kommentar',  // singular: "1 comment"
  comm_count_n: 'kommentarer',  // plural: "3 comments"
  comment1: 'Bli den första att kommentera...',
  comment: 'Kommentera...',
  edit: 'redigera',
  email: 'E-post',
  email_taken: 'Denna e-postadress är redan tagen',
  emailtip: 'Din e-postadress delas aldrig',
  enter: 'ctrl + enter',
  expired1: 'Vi skickade just ett nytt, var vänlig och kontrollera din e-post.', // http://d.pr/i/1OEV
  expired: 'Länken är inte längre aktiv',

  feed: 'Mitt flöde', // alternatives: My own, personal


  help2: 'postar',
  help3: 'citat',
  help5: 'kod, språket gissas',
  help6: 'HTML-kod',
  in_forum: 'i',
  invalid: 'Ogiltigt värde',
  join: 'Skapa ett Muut-konto',
  later: 'Senare...',
  less: 'färre',
  like: 'Gilla',
  likepost: 'Gilla detta inlägg',
  loading: 'Laddar...',
  login: 'Logga in',
  login1: 'Logga in först',
  login_and: "Logga in och",

  logout: 'Logga ut',
  mark: 'Stötande eller spam',
  mean: 'Menade du',
  name: 'Visningsnamn',
  nametip: 'Ditt riktiga namn, så människor känner igen dig',
  newpass: 'Nytt lösenord',
  noresults: 'Inga resultat på',
  nospam: 'Ingen spam på ditt forum!',
  notexist: 'existerar inte.',
  ok: 'ok',
  online: 'Online',
  post: 'Skicka',
  preview: 'Förhandsgranska',
  progress: ['laddar...', 'laddar mer...', 'och ännu mer...', 'ger upp'],
  reconnect: 'Ansluter igen...',
  removepost: 'Ta bort',
  reply: 'Svara...',
  replybtn: 'Svara',
  save: 'Spara ändringar',
  saved: 'sparad',
  search: 'Sök',
  select: 'Välj forum',
  setup: 'Installera nu',
  showing: 'Visar',
  spam: 'Spam',
  step1: 'Vi har skickat ett en bekräftelse till din e-post. Din e-post kommer inte uppdateras förrän du slutfört detta steg!',
  step: 'Ett steg kvar',
  terms: 'Jag godkänner <a>användaravtalet</a>.',
  thanks: 'Tackar!',
  uname_len: 'Skriv fyra tecken eller mer',
  uname_taken: 'Detta användarnamn är upptaget!',
  unametip: 'Detta kan inte ändras i efterhand',
  undo: 'Ångra',
  unlike: 'Sluta gilla',
  unspam: 'Inte spam',
  unver1: 'Overifierat konto',
  unver2: 'Var snäll och kontrollera din e-post för att verifiera ditt konto.',
  unver3: 'Skicka ny verifieringskod',
  unver4: "Skickat. Var snäll och kontrollera din e-postinkorg.",
  unver: 'Overifierad',
  unwall: 'Sluta prenumerera på alla',
  unwatch: 'Sluta prenumerera',
  upgrade2: 'Muut använder WebSockets eller CORS för korsdomänskommunikation. Alla moderna webbläsare utom Opera 11 och IE7 fungerar.',
  upgrade: 'Var snäll och uppgradera din webbläsare',
  username_taken: 'Detta användarnamn är taget',
  watch: 'Prenumerera på nya svar',
  welcome1: 'Var snäll och kontrollera din e-post för att slutföra registreringen. Om du inte får e-post inom en minut eller två, kontrollera din spam-folder.',
  welcome2: 'Ange ett Muut-användarnamn',
  welcome: 'Välkommen till Muut',
  you: 'Du',

  // times
  now: 'precis nu',
  months: "Jan,Feb,Mar,Apr,Maj,Jun,Jul,Aug,Sep,Okt,Nov,Dec",
  min: 'min',
  hour: 'tim',
  day: 'd',
  week: 'v'

}
