moot.language = {

   // the language code
   $code: 'se',

   /* New stuff */
   avatar: 'Ändra avatar',
   seo_update: 'SEO-sidorna kommer uppdateras inom en timme',
   upgrade_link: 'Uppgradera',
   branding: 'Branding',
   logo: 'Logotyp',
   bgcolor: 'Bakgrundsfärg',
   css: 'CSS-fil',
   mootbrand: 'Använd Moot-branding',
   sso: 'Single Sign-On',
   apikey: 'API-nyckel',
   apisecret: 'Hemlig nyckel',

   /* End new stuff */


   bolded: 'fet',
   italics: 'kursiv',
   monospaced: 'monospace',
   domain: 'Forum-URL',
   domaintip: 'Hela URL:en till forumen dit användare skickas från sökresultaten',
   learn: 'Lär dig mer...',
   ga: 'Google Analytics-ID',
   gatip: 'Används på de statiska sidorna',
   admins: 'Administratörer',
   adminstip: 'Ett användarnamn per rad',
   settings: 'Inställningar',

   all: 'Alla inlägg', // or alternatively: All
   anon_1: 'anonym',    // singular
   anon: 'anonyma',      // plural

   badforum: 'Felaktigt forum',
   c_acc1: 'Ditt konto fungerar nu på alla sajter som använder Moot',
   c_acc: 'Kontot bekräftat',
   c_email: 'E-postadress uppdaterad',
   cancel: 'Avbryt',
   change: 'Ändra',
   changepw: 'Ändra lösenord',
   close: 'Stäng',
   collapse: 'Fäll ihop alla',
   comm_count_1: 'kommentar',   // singular: "1 comment"
   comm_count_n: 'kommentarer',  // plural: "3 comments"
   comment1: 'Bli den första att kommentera...',
   comment: 'Kommentera...',
   edit: 'redigera',
   email: 'E-post',
   email_taken: 'Denna e-postadress är redan tagen',
   emailtip: 'Din e-postadress delas aldrig',
   enter: 'ctrl + enter',
   expired1: 'Vi skickade just ett nytt, var vänlig och kontrollera din e-post.', // http://d.pr/i/1OEV
   expired: 'Länken är inte längre aktiv',

   feed: 'Mitt flöde', // alternatives: My own, personal

   forumname: 'Forumnamn',
   forums: 'Forum',
   help1: 'Första raden blir rubrik',
   help2: 'postar',
   help3: 'citat',
   help5: 'kod, språket gissas',
   help6: 'HTML-kod',
   in_forum: 'i',
   invalid: 'Ogiltigt värde',
   join: 'Gå med i Moot',
   later: 'Senare...',
   less: 'färre',
   like: 'Gilla',
   likepost: 'Gilla detta inlägg',
   loading: 'Laddar...',
   login: 'Logga in',
   login1: 'Logga in först',
   login_and: "Logga in och",

   logout: 'Logga ut',
   mark: 'Stötande eller spam',
   mean: 'Menade du',
   name: 'Visningsnamn',
   nametip: 'Ditt riktiga namn, så människor känner igen dig',
   newcat: 'Ny kategori',
   newpass: 'Nytt lösenord',
   noresults: 'Inga resultat på',
   nospam: 'Ingen spam på ditt forum!',
   notexist: 'existerar inte.',
   notify: 'Meddela mig om nya releaser',
   ok: 'ok',
   online: 'Online',
   post: 'Inlägg',
   preview: 'Förhandsgranska',
   progress: ['laddar...', 'laddar mer...', 'och ännu mer...', 'ger upp'],
   reconnect: 'Ansluter igen...',
   removecat: 'Ta bort. Inläggen tas inte bort.',
   removepost: 'Ta bort',
   reply: 'Svara...',
   replybtn: 'Svara',
   save: 'Spara ändringar',
   saved: 'sparad',
   search: 'Sök',
   select: 'Välj forum',
   setup: 'Installera nu',
   showing: 'Visar',
   slogan: 'Forum och kommentarer på ett helt nytt sätt',
   spam: 'Spam',
   start: 'Hur står det till?',
   step1: 'Vi har skickat ett en bekräftelse till din e-post. Din e-post kommer inte uppdateras förrän du slutfört detta steg!',
   step: 'Ett steg kvar',
   terms: 'Jag godkänner <a>användaravtalet</a>.',
   thanks: 'Tackar!',
   uname_len: 'Skriv sex tecken eller mer',
   uname_taken: 'Detta användarnamn är upptaget!',
   unametip: 'Detta kan inte ändras i efterhand',
   undo: 'Ångra',
   unlike: 'Sluta gilla',
   unspam: 'Inte spam',
   unver1: 'Overifierat konto',
   unver2: 'Var snäll och kontrollera din e-post för att verifiera ditt konto. Verifierade användare kan följa moots och få e-postnotifikationer. <a>Skicka ny verifieringskod...</a>',
   unver3: '<a>Skicka ny</a> verifieringskod till:',
   unver4: "Skickat. Var snäll och kontrollera din e-postinkorg.",
   unver: 'Overifierad',
   unwall: 'Sluta prenumerera på alla',
   unwatch: 'Sluta prenumerera',
   upgrade2: 'Moot använder WebSockets eller CORS för korsdomänskommunikation. Alla moderna webbläsare utom Opera 11 och IE7 fungerar.',
   upgrade: 'Var snäll och uppgradera din webbläsare',
   username_taken: 'Detta användarnamn är taget',
   watch: 'Prenumerera på nya svar',
   welcome1: 'Var snäll och kontrollera din e-post för att slutföra registreringen. Om du inte får e-post inom en minut eller två, kontrollera din spam-folder.',
   welcome2: 'Ange ett Moot-användarnamn',
   welcome: 'Välkommen till Moot',
   you: 'Du',

   // times
   now: 'precis nu',
   months: "Jan,Feb,Mar,Apr,Maj,Jun,Jul,Aug,Sep,Okt,Nov,Dec",
   min: 'min',
   hour: 'tim',
   day: 'd',
   week: 'v'

}
