moot.language = {

  // the language code
  $code: 'sk',

  no_notify: 'Vypnúť všetky e-mailové notifikácie',
  watchall: 'Sledovať všetky nové príspevky',
  move: 'Presunúť tému',
  moved: 'Téma presunutá',
  custom_path1: 'Vlastná cesta',
  custom_path: 'Vložte vlastnú cestu',
  invalid_path: 'Neplatná vlastná cesta',
  from: 'Od',
  to: 'Komu',

  retire: 'Označiť ako starú',
  retire_title: 'Označiť tému ako starú',
  retire_desc: 'Staré témy sa nepripínajú na vrch svojho feedu.',
  retired_desc: 'Táto téma je stará. Nové odpovede sa nezobrazujú na vrchu feedu.',
  is_retired: 'Táto téma bola označená ako stará',

  unretire: 'Obnoviť',
  unretire_title: 'Obnoviť tému',
  unretire_desc: 'Táto téma sa bude opäť zobrazovať na vrchu feedu.',
  quote_help1: 'Označiť',
  quote_help2: 'citovať alebo zdieľať',

  trial_left: 'zostáva z trialu zadarmo.',
  after_trial: 'Po tom, ako trial skončí, Muut môžete používať s',
  free_plan: 'Plán zadarmo',
  reward: 'Odmena refferalov',
  off33: 'Upgradnite teraz a získajte 33% zľavu zo všetkých platených plánov',
  spread: 'Šíte do sveta!',
  invite: 'Pozvite priateľov aby si založili Muut komunitu a obaja budete odmenení!',
  start_now: 'Založte si online komunitu teraz - je to zadarmo!',
  start_btn: 'Vytvoriť',
  reserve: 'Rezervujte si vaše meno fóra.',
  free_acc: 'Účet zadarmo',
  no_dialog: 'a odstráňte túto hlášku',
  click_change: 'Klikni a zmeň',

  moderator: 'Moderátor',
  mkadmin: 'Urobiť administrátorom',
  mkmod: 'Urobiť moderátorom',
  upgrade_mod: 'povýšiť tohto používateľa na moderátora',
  upgrade_admin: 'povýšiť tohto používateľa na admina alebo moderátora',

  my_profile: 'Myôj profil',
  post_in: 'Prispieť v',
  address_now: 'Ďakujeme! Vaša mailová adresa bola potvrdená.',
  open_pw: 'Pre otvorenie dialógu na zmenu hesla, stlačte tlačidlo nižšie.',
  non_anon: 'Aby ste mohli vykonať túto akciu, musíte byť prihlásený.',

  plan: 'Plán',
  trial: 'Začnite s trialom zadarmo',

  is_private: "Táto komunita je súkromná",
  owner_msg: "Vaša správa majiteľovi fóra... (Voliteľné)",
  req_access: "Vyžiadať prístup",
  req_sent: "Žiadosť o prístup poslaná",
  or_join: "alebo sa <a>Pripojte</a> ku komunite.",
  save_with: "Ušetrite 20% z ročnej ceny",
  rem_post: "Odstrániť tento príspevok?",
  is_spam: "Je tento príspevok spam?",

  channels: 'Kanály',
  ch_name: 'Meno kanálu',
  ban: 'Zablokovať používateľa',
  banned: 'Zablokovaný',
  ban_acc: 'Zablokovaný účet',
  ban_msg: 'Ste dočasne zablokovaný z prispievania na toto fórum.',
  days: 'Dni',
  forever: 'Navždy',
  slogan: 'Fóra a komentovanie zadarmo od Muut',

  add: '+ Pridať',
  addons: 'Rozšírenia',
  myaccount: "Účet",
  untitled: "Nepomenovaný",
  design: "Dizajn",
  no_title: "Názov je povinný",
  designer: "Dizajnér",
  developer: "Vývojár",


  warning: 'Varovanie',
  profanity: 'Neúctivé príspevky na tomto fóre nie sú dovolené. Opakované porušenie tejto podmienky bude riešené zablokovaním.',

  img_needed: "Prosím, nahrajte súbor obrázku.",
  max: 'Maximálna veľkosť obrázku je 4Mb',
  yes: 'Áno',
  upload: 'Nahrať obrázky',
  show: 'zobraziť',
  hide: 'skryť',
  invisible: 'Neviditeľný',
  givebody: 'Telo správy nemôže byť prázdne.',
  show_old: 'Najstaršie odpovede',
  show_more: 'Viac odpovedí',
  show_new: 'Najnovšie odpovede',
  start: 'Začať novú tému...',
  error: 'Hups, error. Prosím, skopírujte príspevok do schránky, obnovte stránku a skúste to znovu. Prepáčte – opravíme to!',
  body: 'Telo textu',
  admin: 'Administrátor',
  someone: 'Someone',
  title: 'Názov',
  writing: 'práve píše...',
  manage: 'Manažovať',
  fullview: 'Rozšítený pohľad',
  link: 'odkaz',
  avatar: 'Zmeniť avatar',

  upgrade_link: 'Upgradnúť',
  branding: 'Značka',
  logo: 'Logo',

  title: 'Názov',
  css: 'CSS súbor',

  single: 'jedno slovo',

  username_fail: 'Používajte písmená, čísla alebo pomlčky',
  bold: 'bold',
  italics: 'italic',
  monospaced: 'monospaced',

  settings: 'Nastavenia',

  all: 'Všetky príspevky', // or alternatively: All
  anon_1: 'anonym',  // singular
  anon: 'anonymovia',  // plural

  badforum: 'Neplatné fórum',
  c_acc1: 'Váš účet teraz funguje na všetkých stránkach ktoré používajú Muut.',
  c_acc: 'ůčet potvrdený',
  c_email: 'E-amilová adresa aktualizovaná',
  cancel: 'Zrušiť',
  change: 'Zmeniť',
  changepw: 'Zmeniť heslo',
  close: 'Zavrieť',
  collapse: 'Zasunúť',
  comm_count_1: 'komentár',  // singular: "1 comment"
  comm_count_n: 'komentárov',  // plural: "3 comments"
  comment1: 'Pridajte komentár ako prvý...',
  comment: 'Pridať komentár...',
  edit: 'Upraviť',
  email: 'E-mail',
  email_taken: 'Tento e-mail je už obsadený',
  emailtip: 'Váš e-mail nikdy nie je verejný',
  enter: 'ctrl + enter',
  expired1: 'Práve sme vám poslali nový. Prosím, skontrolujte si e-mail.', // http://d.pr/i/1OEV
  expired: 'Odkaz je neplatný',
  feed: 'Môj feed', // alternatives: My own, personal

  help2: 'príspevok',
  help3: 'citované',
  help5: 'kód, odhadnutý jazyk',
  help6: 'HTML kód',
  in_forum: 'v',
  invalid: 'Neplatná hodnota',
  join: 'Pripojde sa do Muut',
  later: 'Neskôr...',
  less: 'Menej',
  like: 'Páči sa mi',
  likepost: 'Páči sa mi tento príspevok',
  loading: 'Načítavanie...',
  login: 'Prihlásiť',
  login1: 'Najskôr sa prihláste',
  login_and: "Prihlásiť a",

  logout: 'Odhlásiť',
  mark: 'Útočný alebo spam',
  mean: 'Mysleli ste',
  name: 'Zobrazované meno',
  nametip: 'Vaše skutočné meno, aby vás ľudia spoznali',

  newpass: 'Nové heslo',
  noresults: 'Žiadne výsedky pre',
  nospam: 'Žiadny spam na našom fóre!',
  notexist: 'neexistuje.',
  ok: 'ok',
  online: 'Online',
  post: 'Pridať príspevok',
  preview: 'Náhľad',
  progress: ['načítavanie...', 'stále pracujeme...', 'a pracujeme...', 'vzdávame sa'],
  reconnect: 'Pripájam...',
  removepost: 'Odstrániť',
  reply: 'Odpovedať...',
  replybtn: 'Odpovedať',

  saved: 'uložené',
  search: 'Vyhľadať',
  select: 'Zvoliť kanál',
  setup: 'Nastviť teraz',
  showing: 'Zorazuje sa',

  spam: 'Spam',
  step1: 'Poslali sme vám potvrdzujúci e-mail. Váš e-mail sa neaktualizuje, pokiaľ nedokončíte tento krok!',
  step: 'Už len jeden krok',
  terms: 'Súhlasím s <a>podmienkami používania</a>.',
  thanks: 'Ďakujeme!',
  uname_len: 'Vložte 4 znaky alebo viac',
  uname_taken: 'Toto meno je obsadené',
  unametip: 'Toto sa už nedá neskôr zmeniť',
  undo: 'Späť',
  unlike: 'Už sa mi to nepáči',
  unspam: 'Nie je spam',
  unver1: 'Nepotvrdený účet',
  unver2: 'Prosím skontrolujte si e-mail a potvrďte svoj účet.',
  unver3: 'Poslať znovu potvrdzujúci e-mail',
  unver4: "Poslané, skontrolujte si e-mail",
  unver: 'Nepotvrdené',
  unwall: 'prestať sledovať všetky',
  unwatch: 'Prestať sledovať',
  upgrade2: 'Muut používa WebSockets alebo CORS pre medzidoménovú komunikáciu. Fungujú všetky moderné prehliadače vyššie ako Opera 11 a IE7.',
  upgrade: 'Prosím, aktualizujte svoj prehliadač.',
  username_taken: 'Toto používateľské meno je obsadené.',
  watch: 'Sledovať nové odpovede.',
  welcome1: 'Na dokončenie registrácie si skontrolujte e-amil. Ak vám e-mail nepríde za 1-2 minúty, skontrolujte si spam.',
  welcome2: 'Prosím zvoľte si Muut meno',
  welcome: 'Vitajte v Muut',
  you: 'Vy',

  // times
  now: 'práve teraz',
  months: "Jan,Feb,Mar,Apr,Máj,Jún,Júl,Aug,Sep,Okt,Nov,Dec",
  min: 'm',
  hour: 'h',
  day: 'd',
  week: 't'

}
