var language = {

  // the language code
  $code: 'ta',


  /* New stuff */
  no_notify: 'Disable all email notifications',
  watchall: 'Watch for all new threads',
  move: 'Move thread',
  moved: 'Thread moved',
  custom_path1: 'Custom path',
  custom_path: 'Enter custom path',
  invalid_path: 'Invalid custom path',
  from: 'From',
  to: 'To',
  show_preview: 'Show preview',

  retire: 'Retire',
  retire_title: 'Retire thread',
  retire_desc: 'Retired threads no longer get bumped to top in the feeds they appear in.',
  retired_desc: 'This thread is retired. New replies no longer bump it to the top of the feed.',
  is_retired: 'This thread has been retired',

  unretire: 'Unretire',
  unretire_title: 'Unretire thread',
  unretire_desc: 'This thread will be bumped to top in the feeds they appear in.',
  quote_help1: 'Select',
  quote_help2: 'to quote or share',

  trial_left: 'left of free trial.',
  after_trial: 'After the trial ends you can continue using Muut with the',
  free_plan: 'Free plan',
  reward: 'Referral reward',
  off33: 'Upgrade now and get 33% off all our paid plans!',
  spread: 'Spread the word!',
  invite: 'Invite a friend to start a Muut community and you’ll both get rewarded!',
  start_now: 'Start your own community now – it\'s free!',
  start_btn: 'Create',
  reserve: 'Reserve your forum name',
  free_acc: 'Free account',
  no_dialog: 'and remove this dialogue',
  click_change: 'Click to change',

  moderator: 'Moderator',
  mkadmin: 'Make administrator',
  mkmod: 'Make moderator',
  upgrade_mod: 'to make this user a moderator',
  upgrade_admin: 'to make this user administrator or moderator',

  my_profile: 'My profile',
  post_in: 'Post in',
  address_now: 'Thank you! Your email address has been confirmed.',
  open_pw: 'Please hit the button below to open a password change dialog',
  non_anon: 'You need to be logged in to perform this action',

  plan: 'Plan',
  trial: 'Start free trial',

  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spam?",

  channels: 'Channels',
  ch_name: 'Channel name',
  ban:  'Ban user',
  banned:  'Banned',
  ban_acc: 'Banned account',
  ban_msg: 'You are temporarily banned from posting on this forum.',
  days:  'Days',
  forever: 'Forever',
  slogan:  'Free forums and commenting by Muut',

  add: '+ Add',
  addons: 'Add-ons',
  myaccount: "Account",
  untitled: "Untitled",
  design: "Design",
  no_title: "Title must be given",
  designer: "Designer",
  developer: "Developer",



  img_needed: "Please upload an image file",
  max: 'Maximum image size is 4Mb',
  yes: 'Yes',
  upload: 'Upload images',
  show: 'show',
  hide: 'hide',
  invisible: 'Invisible',
  givebody: 'Body cannot be empty.',
  show_old: 'Show oldest replies',
  show_more: 'Show more replies',
  show_new: 'Show newest replies',
  start: 'Start a new topic...',


  single: 'single word',
  bold: 'bold',
  italics: 'italics',
  monospaced: 'monospaced',
  learn: 'Learn more...',
  settings: 'Settings',
  error: 'Oops, an error. Please copy the post to clipboard, reload and try again. Sorry – we will fix this!',
  body: 'Body text',
  admin: 'Admin',
  someone: 'Someone',
  writing: 'is writing...',
  manage: 'Manage',
  fullview: 'Full view',
  title: 'Title',
  link: 'link',
  avatar: 'Change avatar',
  upgrade_link: 'Upgrade',
  branding: 'Branding',
  logo: 'Logo',
  css: 'CSS file',



  /* End new stuff */


  username_fail: 'சிற்றெழுத்துக்கள், எண்கள் அல்லது கோடுகளை பயன்படுத்தவும்',
  all: 'அனைத்து பதிவுகள்', // or alternatively: All

  anon_1: 'பெயரிலி',
  anon: 'பெயரிலிகள்',

  badforum: 'தவரான மன்றம்',
  c_acc1: 'இப்பொழுது தங்கள் பயனர் பதிவு, மூட் மன்றத்தை உபயோகிக்கும் எல்லா இணையங்களிலும் செல்லுபடும்',
  c_acc: 'தங்கள் பயனர் பதிவு உறுதி செய்யப்பட்டது',
  c_email: 'மின்னஞ்சல் முகவரி புதுப்பிக்கப்பட்டது',
  cancel: 'நிருத்து',
  change: 'மாற்று',
  changepw: 'கடவுச்சொல் மாற்றம்',
  close: 'மூடு',
  collapse: 'அனைத்தையும் சுருக்கவும்',
  comm_count_1: 'கருத்து',
  comm_count_n: 'கருத்துக்கள்',
  comment1: 'முதல் கருத்து தங்களதே...',
  comment: 'கருத்து...',
  edit: 'திருத்தம்',
  email: 'மின்னஞ்சல்',
  email_taken: 'இந்த மின்னஞ்சல் முகவரி ஏற்கனவே உபயோகத்தில் உள்ளது',
  emailtip: 'தங்கள் மின்னஞ்சல் முகவரி என்றும் பகிரப்படாது',
  enter: 'ctrl + enter',
  expired1: 'புதிய தகவலை அனுப்பி உள்ளோம். தங்கள் மின்னஞ்சலை திறந்து பார்க்கவும்.',
  expired: 'இந்த இணைப்பு காலாவதியானது',

  feed: 'என் பதிவோட்டம்', // alternatives: My own, personal


  help2: 'பதிவு',
  help3: 'மேற்கோள்',
  help5: 'கணினி குறியீடு, மொழி யூகிக்கப்படும்',
  help6: 'HTML குறியீடு',
  in_forum: '',
  invalid: 'தவறான உள்ளிட்ட மதிப்பு',
  join: 'மூட் இணையத்தில் சேரவும்',
  later: 'பிறகு...',
  less: 'சில',
  like: 'பிடித்தது',
  likepost: 'இந்த பதிவு பிடித்தது',
  loading: 'வேலை நடை பெறுகிறது...',
  login: 'புகுபதிகை செய்யவும்',
  login1: 'முதலில் புகுபதிகை செய்யவும்',
  login_and: "புகுபதிகை செய்து, பின்னர்",

  logout: 'விடுபதிகை செய்யவும்',
  mark: 'தகாதது அல்லது கூளம்',
  mean: 'இதை நினைத்தீர்களா?',
  name: 'காணும் பெயர்',
  nametip: 'உங்கள் உண்மைப்பெயர், மக்கள் அங்கீகாரத்திற்கு',
  newpass: 'புதிய கடவுச்சொல்',
  noresults: 'ஒன்றும் கிடைக்கவில்லை:',
  nospam: 'உங்கள் மன்றத்தில் கூளம் இல்லை!',
  notexist: 'என்று எதுவும் இல்லை.',
  ok: 'சரி',
  online: 'இணைப்புள்ளவர்கள்',
  post: 'பதிவு',
  preview: 'முன்னோட்டம்',
  progress: ['வேலை ஆரம்பம்...', 'வேலை நடை பெறுகிறது...', 'இன்னும் வேலை நடை பெறுகிறது...', 'முடியவில்லை'],
  reconnect: 'மீண்டும் இணைக்க முயற்சி...',
  removepost: 'இந்த பதிவை நீக்கு',
  reply: 'பதில்...',
  replybtn: 'பதில்',
  save: 'மாற்றங்களை பதிவு செய்யவும்',
  saved: 'பதிவுபெற்றது',
  search: 'தேடு',
  select: 'மன்றத்தை தேர்ந்தெடுக்கவும்',
  setup: 'இப்பொழுது உருவாக்கவும்',
  showing: 'காண்பிக்கிறோம்',
  spam: 'கூளம்',
  step1: 'உங்கள் மின்னஞ்சலுக்கு ஒரு ஒப்புதல் பதிவை அணுப்பி உள்ளோம். ஒப்புதல் கிடைத்த பின்பே உங்கல் மின்னஞ்சல் புதுப்பிக்கப்படும்!',
  step: 'இன்னும் ஒரே படி உள்ளது',
  terms: '<a>பணி நிபந்தனைகளை</a> நான் ஏற்கிறேன்.',
  thanks: 'நன்றி!',
  uname_len: '4 அல்லது அதற்கு மேற்பட்ட எழுத்துக்களை தட்டச்சு செய்யவும்',
  uname_taken: 'இந்த பயனர் பெயர் ஏற்கனவே உபயோகத்தில் உள்ளது!',
  unametip: 'இது மாற்றக்கூடியது அல்ல',
  undo: 'மீள்',
  unlike: 'பிடிக்கவில்லை',
  unspam: 'கூளம் அல்ல',
  unver1: 'சோதிக்கப்படாத பயனர்',
  unver2: 'தயவு செய்து தங்கள் மின்னஞ்சலில் உள்ள ஒப்புதலை சமர்ப்பிக்கவும்.',
  unver3: 'புதிய ஒப்புதல் பதிவை அணுப்பவும்',
  unver4: "அணுப்பி விட்டோம். தங்கள் மின்னஞ்சலை திறந்து பார்க்கவும்.",
  unver: 'சரிபார்க்கப்படாதது',
  unwall: 'எதையும் கரை வைக்காதே',
  unwatch: 'கரை வைக்காதே',
  upgrade2: 'மூட் WebSockets அல்லது CORS தொழில்னுட்பங்களை குறுக்கு இணையதளத் தொடர்புக்கு பயன்படுத்துகிறது. ஓபெரா 11 மற்றும் ஐஈ 7 தவிர பிற நவீன உலாவிகள் சரியாக வேலை செய்யும்.',
  upgrade: 'தங்கள் இணைய உலாவியை புதுப்பிக்கவும்',
  username_taken: 'இந்த பயனர் பெயர் ஏற்கனவே உபயோகத்தில் உள்ளது',
  watch: 'இந்த மூட் பதிவை கரை வைக்கவும்',
  welcome1: 'தங்கள் மின்னஞ்சலை திறந்து பதிவை நிறைவேற்றவும். ஒன்றிரண்டு நிமிடங்களிள் மின்னஞ்சல் வரவில்லையெனில் கூள கோப்புரையை திறந்து பார்க்கவும்.',
  welcome2: 'தயவு செய்து தங்கள் பயனர் பெயரை அளியுங்கள்',
  welcome: 'மூட் மன்றங்களுக்கு நல்வரவு',
  you: 'நீங்கள்',

  // times
  now: 'சற்று முன்',
  months: "ஜன,பிப்,மார்,ஏப்,மே,ஜூன்,ஜூலை,ஆக்,செப்,அக்ட்,நவ,டிச",
  min: 'நி',
  hour: 'ம',
  day: 'நா',
  week: 'வா'
}

if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
  module.exports = language;
} else {
  window.moot.language = language;
}