var language = {

  // the language code
  $code: 'th',

  no_notify: 'Disable all email notifications',
  watchall: 'Watch for all new threads',
  move: 'Move thread',
  moved: 'Thread moved',
  custom_path1: 'Custom path',
  custom_path: 'Enter custom path',
  invalid_path: 'Invalid custom path',
  from: 'From',
  to: 'To',
  show_preview: 'Show preview',

  retire: 'Retire',
  retire_title: 'Retire thread',
  retire_desc: 'Retired threads no longer get bumped to top in the feeds they appear in.',
  retired_desc: 'This thread is retired. New replies no longer bump it to the top of the feed.',
  is_retired: 'This thread has been retired',

  unretire: 'Unretire',
  unretire_title: 'Unretire thread',
  unretire_desc: 'This thread will be bumped to top in the feeds they appear in.',
  quote_help1: 'Select',
  quote_help2: 'to quote or share',

  trial_left: 'left of free trial.',
  after_trial: 'After the trial ends you can continue using Muut with the',
  free_plan: 'Free plan',
  reward: 'Referral reward',
  off33: 'Upgrade now and get 33% off all our paid plans!',
  spread: 'Spread the word!',
  invite: 'Invite a friend to start a Muut community and you’ll both get rewarded!',
  start_now: 'Start your own community now – it\'s free!',
  start_btn: 'Create',
  reserve: 'Reserve your forum name',
  free_acc: 'Free account',
  no_dialog: 'and remove this dialogue',
  click_change: 'Click to change',

  moderator: 'Moderator',
  mkadmin: 'Make administrator',
  mkmod: 'Make moderator',
  upgrade_mod: 'to make this user a moderator',
  upgrade_admin: 'to make this user administrator or moderator',

  my_profile: 'My profile',
  post_in: 'Post in',
  address_now: 'Thank you! Your email address has been confirmed.',
  open_pw: 'Please hit the button below to open a password change dialog',
  non_anon: 'You need to be logged in to perform this action',

  plan: 'รูปแบบ',
  trial: 'ทดลองใช้งาน',

  is_private: "สังคมนี้ไม่เปิดสู่สาธารณะ",
  owner_msg: "ส่งข้อความถึงเจ้าของกระทู้... (ไม่บังคับ)",
  req_access: "ส่งคำร้อง",
  req_sent: "คำร้องถูกส่งแล้ว",
  or_join: "หรือ <a>เข้าร่วม</a> เพื่อเข้าสู่ระบบ",
  save_with: "ลด 20% สำหรับการชำระเงินแบบรายปี",
  rem_post: "ลบโพสท์?",
  is_spam: "โพสท์นี้คือสแปม?",

  channels: 'เลือกห้อง',
  ch_name: 'ชื่อห้อง',
  ban: 'ระงับการใช้งาน',
  banned: 'ระงับแล้ว',
  ban_acc: 'บัญชีถูกระงับการใช้งาน',
  ban_msg: 'คุณถูกระงับการใช้งานชั่วคราว',
  days: 'วัน',
  forever: 'ตลอดไป',
  slogan: 'กระทู้สนทนาฟรีสนับสนุนโดย Muut',

  add: '+ เพิ่ม',
  addons: 'แอด-ออน',
  myaccount: "บัญชีของคุณ",
  untitled: "ไม่ได้ตั้งชื่อ",
  design: "ออกแบบ",
  no_title: "จำเป็นต้องมีชื่อ",
  designer: "ผู้ออกแบบ",
  developer: "ผู้พัฒนา",


  warning: 'คำเตือน',
  profanity: 'ไม่อนุญาตให้ใช้คำพูดที่ไม่เหมาะสม หากละเมิดคุณอาจถูกระงับการใช้งาน',

  img_needed: "กรุณาเลือกรูปภาพ",
  max: 'เลือกรูปขนาดไม่เกิน 4Mb',
  yes: 'ตกลง',
  upload: 'อัพโหลดรูปภาพ',
  show: 'แสดง',
  hide: 'ซ่อน',
  invisible: 'มองไม่เห็น',
  givebody: 'เนื้อหาไม่สามารถเว้นว่างได้',
  show_old: 'แสดงความเห็นแรกสุด',
  show_more: 'แสดงมากกว่านี้',
  show_new: 'แสดงความเห็นล่าสุด',
  start: 'ตั้งหัวข้อใหม่...',
  error: 'ขออภัย มีข้อผิดพลาด กรุณาทำการคัดลองโพสท์ของคุณไว้บนคลิปบอร์ด โหลดหน้านี้และทดลองโพสท์ใหม่ ขออภัยในความไม่สะดวก',
  body: 'ข้อความ',
  admin: 'แอดมิน',
  someone: 'บุคคลทั่วไป',
  title: 'หัวข้อ',
  writing: 'กำลังพิมพ์...',
  manage: 'จัดการ',
  fullview: 'มองแบบเต็มหน้าจอ',
  link: 'ลิงค์',
  avatar: 'เปลี่ยนรูปส่วนตัว',

  upgrade_link: 'อัพเกรด',
  branding: 'แบรนด์ดิ้ง',
  logo: 'โลโก้',

  title: 'หัวข้อ',
  css: 'ไฟล์ CSS',

  single: 'คำพูดเดียว',

  username_fail: 'ใช้ตัวอักษร, ตัวเลข หรือสัญลักษณ์ขีด',
  bold: 'ตัวหนา',
  italics: 'ตัวเอียง',
  monospaced: 'ฟอนท์กว้างขนาดเดียว',

  settings: 'ตั้งค่า',

  all: 'โพสท์ทั้งหมด', // or alternatively: All
  anon_1: 'บุคคลทั่วไป',  // singular
  anon: 'บุคคลทั่วไป',  // plural

  badforum: 'กระทู้ผิดพลาด',
  c_acc1: 'บัญชีของคุณสามารถใช้งานกับทุกเว็บไซท์ที่ใช้งาน Muut',
  c_acc: 'ยืนยันบัญชีแล้ว',
  c_email: 'แก้ไขอีเมล์แล้ว',
  cancel: 'ยกเลิก',
  change: 'เปลี่ยน',
  changepw: 'เปลี่ยนรหัสผ่าน',
  close: 'ปิด',
  collapse: 'ย่อทั้งหมด',
  comm_count_1: 'ความเห็น',  // singular: "1 comment"
  comm_count_n: 'ความเห็น',  // plural: "3 comments"
  comment1: 'ตอบกลับเป็นคนแรก...',
  comment: 'ความเห็น...',
  edit: 'แก้ไข',
  email: 'อีเมล์',
  email_taken: 'อีเมล์ซ้ำในระบบ',
  emailtip: 'อีเมล์ของคุณจะไม่ถูกส่งต่อ',
  enter: 'ctrl + enter',
  expired1: 'เราดำเนินการส่งไปให้คุณอีกครั้งแล้ว กรุณาตรวจสอบอีเมล์ของคุณ', // http://d.pr/i/1OEV
  expired: 'ลิงค์นี้หมดอายุแล้ว',
  feed: 'ฟีดของฉัน', // alternatives: My own, personal

  help2: 'โพสท์',
  help3: 'อ้างอิงคำพูด',
  help5: 'โค้ด, language guessed',
  help6: 'โค้ด HTML',
  in_forum: 'in',
  invalid: 'ข้อมูลผิดพลาด',
  join: 'เข้าร่วม Muut',
  later: 'อ่านภายหลัง...',
  less: 'ย่อ',
  like: 'Like',
  likepost: 'Like โพสท์นี้',
  loading: 'กำลังอ่าน...',
  login: 'เข้าสู่ระบบ',
  login1: 'เข้าสู่ระบบก่อน',
  login_and: "เข้าสู่ระบบ และ",

  logout: 'ออกจากระบบ',
  mark: 'ละเมิดหรือสแปม',
  mean: 'คุณหมายถึง',
  name: 'ชื่อที่แสดง',
  nametip: 'ชื่อจริงของคุณ เพื่อให้ผู้อื่นจดจำได้',

  newpass: 'รหัสผ่านใหม่',
  noresults: 'ไม่มีผลลัพธ์สำหรับ',
  nospam: 'กระทู้ของคุณไม่มีสแปม',
  notexist: 'ไม่มีอยู่',
  ok: 'ok',
  online: 'Online',
  post: 'โพสท์',
  preview: 'Preview',
  progress: ['กำลังประมวลผล...', 'รออีกสักนิด...', 'กำลังประมวลผล...', 'ยกเลิก'],
  reconnect: 'กำลังต่อใหม่...',
  removepost: 'เอาออก',
  reply: 'ตอบ...',
  replybtn: 'ตอบ',

  saved: 'บันทึก',
  search: 'ค้นหา',
  select: 'เลือกห้อง',
  setup: 'ตั้งค่า',
  showing: 'กำลังแสดง',

  spam: 'สแปม',
  step1: 'เราได้ส่งอีเมล์ยืนยันไปให้คุณแล้ว กรุณาอย่าเปลี่ยนอีเมล์ในขั้นตอนนี้',
  step: 'อีกขั้นตอน',
  terms: 'ยอมรับเงื่อนไข <a>terms of service</a>.',
  thanks: 'ขอบคุณ!',
  uname_len: 'ใส่ตัวอักษร 4 ตัวหรือมากกว่า',
  uname_taken: 'มีผู้ใช้ชื่อนี้แล้ว',
  unametip: 'ชื่อผู้ใช้งานจะไม่สามารถเปลี่ยนแปลงได้',
  undo: 'ย้อนกลับ',
  unlike: 'Unlike',
  unspam: 'ไม่ใช่สแปม',
  unver1: 'ชื่อผู้ใช้งานไม่ได้รับการรับรอง',
  unver2: 'กรุณาตรวจสอบอีเมล์เพื่อยืนยันชื่อผู้ใช้งานของคุณ',
  unver3: 'ส่งลิงค์เพื่อยืนยันใหม่อีกครั้ง',
  unver4: "จัดส่งแล้ว กรุณาตรวจสอบอีเมล์ของคุณ",
  unver: 'ไม่รับรอง',
  unwall: 'เลิกติดตามทุกความเห็น',
  unwatch: 'เลิกติดตาม',
  upgrade2: 'Muut ใช้ WebSockets หรือ CORS สำหรับการสื่อสารข้ามโดเมน บราวเซอร์ที่สูงกว่า Opera 11 และ IE7 work สามารถใช้งานได้',
  upgrade: 'กรุณาอัพเกรดบราวเซอร์ของคุณ',
  username_taken: 'มีผู้ใช้ชื่อนี้แล้ว',
  watch: 'ติดตามความเห็นใหม่',
  welcome1: 'ลงทะเบียนเสร็จแล้ว กรุณาตรวจสอบอีเมล์ของคุณ หากคุณไม่ได้รับอีเมล์จากเราภายใน 1-2 นาที คุณควรเช็คที่แฟ้มสแปม',
  welcome2: 'กรุณาใส่ชื่อผู้ใช้งาน Muut',
  welcome: 'ยินดีต้อนรับสู่ Muut',
  you: 'คุณ',

  // times
  now: 'ตอนนี้',
  months: "ม.ค.,ก.พ.,มี.ค.,เม.ย.,พ.ค.,มิ.ย.,ก.ค.,ส.ค.,ก.ย.,ต.ต.,พ.ย.,ธ.ค.",
  min: 'นาที',
  hour: 'ชั่วโมง',
  day: 'วัน',
  week: 'สัปดาห์'

}

if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
  module.exports = language;
} else {
  window.moot.language = language;
}