moot.language = {

   // the language code
   $code: 'tr',


   /* New stuff */
   show_old: 'Show oldest replies',
   show_more: 'Show more replies',
   show_new: 'Show newest replies',
   start: 'Start a new topic...',
   someone: 'Birisi',
   writing: 'yazıyor...',
   basic: 'Temel (Ücretsiz)',
   subs: 'Abonelikler',
   manage: 'Yönet',
   bolded: 'koyu',
   italics: 'yatık',
   monospaced: 'monospace',
   domain: 'Forum URL',
   domaintip: 'Kullanıcılara sonuçların iletildiği açık domain URL',
   learn: 'Daha fazla...',
   ga: 'Google Analytics Id',
   admins: 'Adminler',
   adminstip: 'Satır başına bir kullanıcı',
   settings: 'Ayarlar',
   fullview: 'Tam görüntü',
   title: 'Başlık',
   link: 'bağlantı',
   avatar: 'Avatar değiştir',
   seo_update: 'SEO sayfaları bir saat içinde güncellenecektir',
   upgrade_link: 'Yükselt',
   branding: 'Markalama',
   logo: 'Logo',
   bgcolor: 'Arka plan rengi',
   brand_name: 'Marka',
   css: 'CSS dosyası',
   mootbrand: 'Moot markasını kullan',
   sso: 'Tek şifre girişi',
   apikey: 'API anahtarı',
   apisecret: 'Gizli anahtar',



   /* End new stuff */


   email_fail: 'Geçersiz email adresi',
   all: 'Tüm yazılar', // or alternatively: All

   anon_1: 'ziyaretçi',    // singular
   anon: 'ziyaretçi',      // plural

   badforum: 'Geçersiz forum',
   c_acc1: 'Hesabınız artık Moot kullanan tüm sitelerde geçerlidir',
   c_acc: 'Hesap onaylandı',
   c_email: 'Email adresi güncellendi',
   cancel: 'İptal',
   change: 'Değiştir',
   changepw: 'Şifre değiştir',
   close: 'Kapat',
   collapse: 'Hepsini kapat',
   comm_count_1: 'yorum',   // singular: "1 comment"
   comm_count_n: 'yorum',  // plural: "3 comments"
   comment1: 'İlk yorumu siz yapın...',
   comment: 'Yorum...',
   edit: 'düzenle',
   email: 'Email',
   email_taken: 'Bu email başkası tarafından alınmış',
   emailtip: 'Email adresiniz asla paylaşılmaz',
   enter: 'ctrl + enter',
   expired1: 'Size yeni bir tane gönderdik. Lütfen email hesabınızı kontrol edin.', // http://d.pr/i/1OEV
   expired: 'Bu bağlantı geçersiz',

   feed: 'Kişisel', // alternatives: My own, personal

   forumname: 'Forum adı',
   forums: 'Forumlar',

   help2: 'yayınla',
   help3: 'alıntı metin',
   help5: 'kod, dil tahmin edilmektedir',
   help6: 'HTML kodu',
   in_forum: 'kategori',
   invalid: 'Geçersiz değer',
   join: 'Moot\'a katılın',
   later: 'Daha sonra...',
   less: 'daha az',
   like: 'Beğen',
   likepost: 'Bu yazıyı beğen',
   loading: 'Yükleniyor...',
   login: 'Giriş yap',
   login1: 'Önce giriş yapınız',
   login_and: "Giriş yap ve",

   logout: 'Çıkış yap',
   mark: 'Hakaret veya spam',
   mean: 'Kastettiğiniz',
   name: 'Görünecek isim',
   nametip: 'İnsanlar sizi bu isimle tanıyacaklar',
   newcat: 'Yeni kategori',
   newpass: 'Yeni şifre',
   noresults: 'Sonuç bulunamadı',
   nospam: 'Spamsiz forum!',
   notexist: 'bulunmuyor.',
   notify: 'Gelişmelerinden beni haberdar et',
   ok: 'tamam',
   online: 'Çevrimiçi',
   post: 'Yayınla',
   preview: 'Önizleme',
   progress: ['yükleniyor...', 'hala devam ediyor...', 've devam ediyor...', 'vazgeçiyor'],
   reconnect: 'Tekrar bağlanıyor...',
   removecat: 'Sil. Yazılar silinmedi.',
   removepost: 'Bu yazıyı sil',
   reply: 'Cevap...',
   replybtn: 'Cevap',
   save: 'Değişiklikleri kaydet',
   saved: 'kaydedildi',
   search: 'Arama',
   select: 'Forum seç',
   setup: 'Şimdi ayarla',
   showing: 'Gösterilen',
   slogan: 'Forum ve yorum anlayışı yeniden tasarlandı',
   spam: 'Spam',
   step1: 'Email hesabınıza bir onay maili gönderdik. Bu adımı tamamlamadan email bilginiz güncellenmez!',
   step: 'Bir adım daha',
   terms: '<a>Kullanım koşulları</a>nı kabul ediyorum.',
   thanks: 'Teşekkürler!',
   uname_len: '6 veya daha fazla karakter giriniz',
   uname_taken: 'Bu kullanıcı adı başkası tarafından alınmış!',
   unametip: 'Bu bilgi daha sonra değiştirilemez',
   undo: 'Geri al',
   unlike: 'Beğenmekten vazgeç',
   unspam: 'Spam değil',
   unver1: 'Onaylanmamış hesap',
   unver2: 'Hesabınızı onaylamak için lütfen email hesabınızı kontrol edin. Onaylı kullanıcılar moot takibi yapabilir ve email bilgilendirmeleri alabilirler. <a>Yeni doğrulama kodu gönder...</a>',
   unver3: 'Şuraya yeni doğrulama kodu <a>gönder</a> :',
   unver4: "Gönderildi. Lütfen gelen kutunuzu kontrol edin.",
   unver: 'Onaylanamadı',
   unwall: 'tümü için takibi bırak',
   unwatch: 'Takibi bırak',
   upgrade2: 'Moot karşılıklı alan adı iletişimi için WebSockets veya CORS kullanmaktadır. Opera 11 ve IE7 hariç tüm modern tarayıcılarda çalışmaktadır.',
   upgrade: 'Lütfen tarayıcınızı güncelleyin',
   username_taken: 'Bu kullanıcı adı baþkası tarafından alınmış',
   watch: 'Bu moot\'u takip et',
   welcome1: 'Kaydı tamamlamak için lütfen email hesabınızı kontrol edin. Bir iki dakika içerisinde email gelmez ise spam kutusunu kontrol ediniz.',
   welcome2: 'Lütfen Moot kullanıcı adını girin',
   welcome: 'Moot\'a hoşgeldiniz',
   you: 'Siz',

   // times
   now: 'az önce',
   months: "Oca,Şub,Mar,Nis,May,Haz,Tem,Ağu,Eyl,Eki,Kas,Ara",
   min: ' dakika önce',
   hour: ' saat önce',
   day: ' gün önce',
   week: ' hafta önce'

}
