moot.language = {

   // the language code
   $code: 'tr',

   all: 'Tüm yazýlar', // or alternatively: All

   anon_1: 'ziyaretçi',    // singular
   anon: 'ziyaretçi',      // plural

   badforum: 'Geçersiz forum',
   c_acc1: 'Hesabýnýz artýk Moot kullanan tüm sitelerde geçerlidir',
   c_acc: 'Hesap onaylandý',
   c_email: 'Email adresi güncellendi',
   cancel: 'Ýptal',
   change: 'Deðiþtir',
   changepw: 'Þifre deðiþtir',
   close: 'Kapat',
   collapse: 'Hepsini kapat',
   comm_count_1: 'yorum',   // singular: "1 comment"
   comm_count_n: 'yorum',  // plural: "3 comments"
   comment1: 'Ýlk yorumu siz yapýn...',
   comment: 'Yorum...',
   edit: 'düzenle',
   email: 'Email',
   email_taken: 'Bu email baþkasý tarafýndan alýnmýþ',
   emailtip: 'Email adresiniz asla paylaþýlmaz',
   enter: 'ctrl + enter',
   expired1: 'Size yeni bir tane gönderdik. Lütfen email hesabýnýzý kontrol edin.', // http://d.pr/i/1OEV
   expired: 'Bu baðlantý geçersiz',

   feed: 'Kiþisel', // alternatives: My own, personal

   forumname: 'Forum adý',
   forums: 'Forumlar',
   help1: 'Ýlk satýr baþlýk içindir',
   help2: 'yayýnla',
   help3: 'alýntý metin',
   help4: 'alýntý metin ikinci satýr',
   help5: 'kod, dil tahmin edilmektedir',
   help6: 'HTML kodu',
   in_forum: 'kategori',
   invalid: 'Geçersiz deðer',
   join: 'Moot\'a katýlýn',
   later: 'Daha sonra...',
   less: 'daha az',
   like: 'Beðen',
   likepost: 'Bu yazýyý beðen',
   loading: 'Yükleniyor...',
   login: 'Giriþ yap',
   login1: 'Önce giriþ yapýnýz',
   login_and: "Giriþ yap ve",

   logout: 'Çýkýþ yap',
   mark: 'Hakaret veya spam',
   mean: 'Kastettiðiniz',
   name: 'Görünecek isim',
   nametip: 'Ýnsanlar sizi bu isimle tanýyacaklar',
   newcat: 'Yeni kategori',
   newpass: 'Yeni þifre',
   noresults: 'Sonuç bulunamadý',
   nospam: 'Spamsiz forum!',
   notexist: 'bulunmuyor.',
   notify: 'Geliþmelerinden beni haberdar et',
   ok: 'tamam',
   online: 'Çevrimiçi',
   post: 'Yayýnla',
   preview: 'Önizleme',
   progress: ['yükleniyor...', 'hala devam ediyor...', 've devam ediyor...', 'vazgeçiyor'],
   reconnect: 'Tekrar baðlanýyor...',
   removecat: 'Sil. Yazýlar silinmedi.',
   removepost: 'Bu yazýyý sil',
   reply: 'Cevap...',
   replybtn: 'Cevap',
   save: 'Deðiþiklikleri kaydet',
   saved: 'kaydedildi',
   search: 'Arama',
   select: 'Forum seç',
   setup: 'Þimdi ayarla',
   showing: 'Gösterilen',
   slogan: 'Forum ve yorum anlayýþý yeniden tasarlandý',
   spam: 'Spam',
   start: 'Ne düþünüyorsun?',
   step1: 'Email hesabýnýza bir onay maili gönderdik. Bu adýmý tamamlamadan email bilginiz güncellenmez!',
   step: 'Bir adým daha',
   terms: '<a>Kullaným koþullarý</a>ný kabul ediyorum.',
   thanks: 'Teþekkürler!',
   uname_len: '6 veya daha fazla karakter giriniz',
   uname_taken: 'Bu kullanýcý adý baþkasý tarafýndan alýnmýþ!',
   unametip: 'Bu bilgi daha sonra deðiþtirilemez',
   undo: 'Geri al',
   unlike: 'Beðenmekten vazgeç',
   unspam: 'Spam deðil',
   unver1: 'Onaylanmamýþ hesap',
   unver2: 'Hesabýnýzý onaylamak için lütfen email hesabýnýzý kontrol edin. Onaylý kullanýcýlar moot takibi yapabilir ve email bilgilendirmeleri alabilirler. <a>Yeni doðrulama kodu gönder...</a>',
   unver3: 'Þuraya yeni doðrulama kodu <a>gönder</a> :',
   unver4: "Gönderildi. Lütfen gelenler kutunuzu kontrol edin.",
   unver: 'Onaylanamadý',
   unwall: 'hepsi için takibi býrak',
   unwatch: 'Takibi býrak',
   upgrade2: 'Moot karþýlýklý alan adý iletiþimi için WebSockets veya CORS kullanmaktadýr. Opera 11 ve IE7 hariç tüm modern tarayýcýlarda çalýþmaktadýr.',
   upgrade: 'Lütfen tarayýcýnýzý güncelleyin',
   username_taken: 'Bu kullanýcý adý baþkasý tarafýndan alýnmýþ',
   watch: 'Bu moot\'u takip et',
   welcome1: 'Kaydý tamamlamak için lütfen email hesabýnýzý kontrol edin. Bir iki dakika içerisinde email gelmez ise spam kutusunu kontrol ediniz.',
   welcome2: 'Lütfen Moot kullanýcý adýný girin',
   welcome: 'Moot\'a hoþgeldiniz',
   you: 'Siz',

   // times
   now: 'az önce',
   months: "Oca,Þub,Mar,Nis,May,Haz,Tem,Aðu,Eyl,Eki,Kas,Ara",
   min: ' dakika önce',
   hour: ' saat önce',
   day: ' gün önce',
   week: ' hafta önce'

}
