moot.language = {

  // the language code
  $code: 'tw',


  /* New stuff */
  moderator: 'Moderator',
  mkadmin: 'Make administrator',
  mkmod: 'Make moderator',
  upgrade_mod: 'to make this user a moderator',
  upgrade_admin: 'to make this user administrator or moderator',

  my_profile: 'My profile',
  post_in: 'Post in',
  address_now: 'Thank you! Your email address has been confirmed.',
  open_pw: 'Please hit the button below to open a password change dialog',
  non_anon: 'You need to be logged in to perform this action',

  plan: 'Plan',
  trial: 'Start free trial',

  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spam?",

  channels: 'Channels',
  ch_name: 'Channel name',
  ban:  'Ban user',
  banned:  'Banned',
  ban_acc: 'Banned account',
  ban_msg: 'You are temporarily banned from posting on this forum.',
  days:  'Days',
  forever: 'Forever',
  slogan:  'Free forums and commenting by Muut',

  add: '+ Add',
  addons: 'Add-ons',
  myaccount: "My account",
  untitled: "Untitled",
  design: "Design",
  no_title: "Title must be given",
  designer: "Designer",
  developer: "Developer",



  img_needed: "Please upload an image file",
  max: 'Maximum image size is 4Mb',
  yes: 'Yes',
  upload: 'Upload images',
  show: 'show',
  hide: 'hide',
  invisible: 'Invisible',
  givebody: 'Body cannot be empty.',
  show_old: 'Show oldest replies',
  show_more: 'Show more replies',
  show_new: 'Show newest replies',
  start: 'Start a new topic...',
  error: 'Oops, an error. Please copy the post to clipboard, reload and try again. Sorry – we will fix this!',
  body: 'Body text',
  admin: 'Admin',
  someone: 'Someone',
  writing: 'is writing...',
  manage: 'Manage',
  fullview: 'Full view',
  title: 'Title',
  link: 'link',
  avatar: 'Change avatar',
  upgrade_link: 'Upgrade',
  branding: 'Branding',
  logo: 'Logo',
  css: 'CSS file',
  single: 'single word',


  /* End new stuff */
  username_fail: '使用小寫字母、數字或橫線',
  bold: '粗體',
  italics: '斜體',
  monospaced: '等寬',
  learn: '了解更多 ...',
  settings: '設定',

  all: '所有文章', // or alternatively: All
  anon_1: '匿名使用者',
  anon: '匿名使用者',
  badforum: '非法論壇',
  c_acc1: '你的帳號已經可以在所有使用Muut的網站上登入了',
  c_acc: '帳號已確認',
  c_email: 'Email已更新',
  cancel: '取消',
  change: '更改',
  changepw: '更改密碼',
  close: '關閉',
  collapse: '全部收合',
  comm_count_1: '評論',
  comm_count_n: '評論',
  comment1: '第一個發表評論...',
  comment: '評論...',
  edit: '編輯',
  email: 'Email',
  email_taken: '這個Email已經被註冊過了',
  emailtip: '您的Email絕不會被公開',
  enter: 'ctrl + enter',
  expired1: '我們剛剛送了一個新連結給您，請檢查您的Email信箱',
  expired: '這個連結已過期',

  feed: '我的發文', // alternatives: My own, personal


  help2: '發文',
  help3: '引用文字',
  help5: '程式碼，自動猜測語言類型',
  help6: 'HTML碼',
  in_forum: '於',
  invalid: '無效值',
  join: '加入 Muut',
  later: '稍候...',
  less: '收合',
  like: '喜愛',
  likepost: '喜愛此發文',
  loading: '載入中...',
  login: '登入',
  login1: '請先登入',
  login_and: "登入 而且",

  logout: '登出',
  mark: '不雅的 或 垃圾內容',
  mean: '您是否意指',
  name: '顯示名稱',
  nametip: '建議填寫真實姓名，以便人們可以認出您',
  newpass: '新的密碼',
  noresults: '沒有搜尋到關於',
  nospam: '您的論壇中無垃圾內容！',
  notexist: '不存在',
  ok: 'ok',
  online: '線上',
  post: '發文',
  preview: '預覽',
  progress: ['載入中...', '仍在載入中...', '仍在進行中...', '放棄了'],
  reconnect: '重新連結...',
  removepost: '移除此發文',
  reply: '回覆...',
  replybtn: '回覆',
  save: '儲存變更',
  saved: '已儲存',
  search: '搜尋',
  select: '選擇論壇類別',
  setup: '現在就設定',
  showing: '展示中',
  spam: '垃圾內容',
  step1: '我們已經送出確認信。在您完成此步驟前，您的Email不會被更新！',
  step: '下一步',
  terms: '我同意 <a>服務條款</a>',
  thanks: '謝謝！',
  uname_len: '輸入六個以上字元',
  uname_taken: '這個使用者名稱已經被註冊過了！',
  unametip: '這部份往後無法修改',
  undo: '取消',
  unlike: '不喜愛',
  unspam: '不是垃圾內容',
  unver1: '未驗證過的帳號',
  unver2: '請檢查您的Email以驗證您的帳號。',
  unver3: '發送新的確認碼',
  unver4: "已送出。請檢查您的信箱。",
  unver: '未驗證',
  unwall: '取消所有關注',
  unwatch: '取消關注',
  upgrade2: 'Muut使用WebSockets或CORS達成跨網域溝通。除了Opera 11和IE7，現行的瀏覽器都可以正確執行。',
  upgrade: '請升級您的瀏覽器',
  username_taken: '這個使用者名稱已經被註冊了',
  watch: '關注此討論',
  welcome1: '請檢查您的Email以完成註冊。如果您在一兩分鐘內沒有收到Email，請檢查您的垃圾郵件。',
  welcome2: '請提供一個Muut使用者名稱',
  welcome: '歡迎使用 Muut',
  you: '您',

  // times

  now: '現在',
  months: "1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月",
  min: '分',
  hour: '時',
  day: '天',
  week: '週'


}
