moot.language = {

   // the language code
   $code: 'tw',


   all: '所有文章', // or alternatively: All
   anon_1: '匿名使用者',
   anon: '匿名使用者',
   badforum: '非法論壇',
   c_acc1: '你的帳號已經可以在所有使用Moot的網站上登入了',
   c_acc: '帳號已確認',
   c_email: 'Email已更新',
   cancel: '取消',
   change: '更改',
   changepw: '更改密碼',
   close: '關閉',
   collapse: '全部收合',
   comm_count_1: '評論',
   comm_count_n: '評論',
   comment1: '第一個發表評論...',
   comment: '評論...',
   edit: '編輯',
   email: 'Email',
   email_taken: '這個Email已經被註冊過了',
   emailtip: '您的Email絕不會被公開',
   enter: 'ctrl + enter',
   expired1: '我們剛剛送了一個新連結給您，請檢查您的Email信箱',
   expired: '這個連結已過期',

   feed: '我的發文', // alternatives: My own, personal

   forumname: '論壇名稱',
   forums: '論壇',
   help1: '第一行是標題',
   help2: '發文',
   help3: '引用文字',
   help4: '第二行',
   help5: '程式碼，自動猜測語言類型',
   help6: 'HTML碼',
   in_forum: '於',
   invalid: '無效值',
   join: '加入 Moot',
   later: '稍候...',
   less: '收合',
   like: '喜愛',
   likepost: '喜愛此發文',
   loading: '載入中...',
   login: '登入',
   login1: '請先登入',
   login_and: "登入 而且",

   logout: '登出',
   mark: '不雅的 或 垃圾內容',
   mean: '您是否意指',
   name: '顯示名稱',
   nametip: '建議填寫真實姓名，以便人們可以認出您',
   newcat: '新增類別',
   newpass: '新的密碼',
   noresults: '沒有搜尋到關於',
   nospam: '您的論壇中無垃圾內容！',
   notexist: '不存在',
   notify: '有新的發佈消息通知我',
   ok: 'ok',
   online: '線上',
   post: '發文',
   preview: '預覽',
   progress: ['載入中...', '仍在載入中...', '仍在進行中...', '放棄了'],
   reconnect: '重新連結...',
   removecat: '移除。屬於此類別的發文不會被移除',
   removepost: '移除此發文',
   reply: '回覆...',
   replybtn: '回覆',
   save: '儲存變更',
   saved: '已儲存',
   search: '搜尋',
   select: '選擇論壇類別',
   setup: '現在就設定',
   showing: '展示中',
   slogan: '創新設計的論壇及評論平台',
   spam: '垃圾內容',
   start: '分享點什麼？',
   step1: '我們已經送出確認信。在您完成此步驟前，您的Email不會被更新！',
   step: '下一步',
   terms: '我同意 <a>服務條款</a>',
   thanks: '謝謝！',
   uname_len: '輸入六個以上字元',
   uname_taken: '這個使用者名稱已經被註冊過了！',
   unametip: '這部份往後無法修改',
   undo: '取消',
   unlike: '不喜愛',
   unspam: '不是垃圾內容',
   unver1: '未驗證過的帳號',
   unver2: '請檢查您的Email以驗證您的帳號。已驗證過的使用者能看到發文及收到Email通知。<a>發送新的確認碼...</a>',
   unver3: '<a>重新發送</a> 確認碼給：',
   unver4: "已送出。請檢查您的信箱。",
   unver: '未驗證',
   unwall: '取消所有關注',
   unwatch: '取消關注',
   upgrade2: 'Moot使用WebSockets或CORS達成跨網域溝通。除了Opera 11和IE7，現行的瀏覽器都可以正確執行。',
   upgrade: '請升級您的瀏覽器',
   username_taken: '這個使用者名稱已經被註冊了',
   watch: '關注此討論',
   welcome1: '請檢查您的Email以完成註冊。如果您在一兩分鐘內沒有收到Email，請檢查您的垃圾郵件。',
   welcome2: '請提供一個Moot使用者名稱',
   welcome: '歡迎使用 Moot',
   you: '您',

   // times

   now: '現在',
   months: "1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月",
   min: '分',
   hour: '時',
   day: '天',
   week: '週'


}
