moot.language = {

   // the language code
   $code: 'uk',

   banned: 'Заблокований обліковий запис',
   banned2: 'Для вашого облікового запису тимчасово заблоковано можливість писати на цьому форумі через порушення правил форума. Доведеться ще зачекати от стільки:',
   banned4: 'Ви більше не зможете писати на цьому форумі.',
   warning: 'Попередження',
   profanity: 'Profanity is not allowed on this forum. Continued abuse of this policy will result in being banned.',

   upload: 'Завантажити зображення на сервер',
   show: 'показати',
   hide: 'сховати',
   invisible: 'Invisible',
   givebody: 'Body cannot be empty.',
   show_old: 'Show oldest replies',
   show_more: 'Show more replies',
   show_new: 'Show newest replies',
   start: 'Start a new topic...',
   error: 'Oops, an error. Please copy the post to clipboard, reload and try again. Sorry – we will fix this!',
   body: 'Body text',
   admin: 'Admin',
   someone: 'Someone',
   title: 'Title',
   writing: 'is writing...',
   basic: 'Basic (free)',
   subs: 'Subscriptions',
   manage: 'Manage',
   fullview: 'Full view',
   link: 'link',
   avatar: 'Change avatar',
   seo_update: 'The SEO pages will be updated within the hour',
   upgrade_link: 'Upgrade',
   branding: 'Branding',
   logo: 'Logo',
   bgcolor: 'Background color',
   brand_name: 'Brand name',
   title: 'Title',
   css: 'CSS file',
   mootbrand: 'Use Moot branding',
   sso: 'Single Sign-On',
   apikey: 'API key',
   apisecret: 'Secret key',
   single: 'single word',




   username_fail: 'Використовуйте букви, цифри або тире',
   bold: 'жирний',
   italics: 'курсив',
   monospaced: 'моноширинний',
   domain: 'URL-адреса форума',
   domaintip: 'Full URL to the forums where users are pushed from the search results',
   learn: 'Детальніше...',
   ga: 'Google Analytics Id',
   admins: 'Адміністратори',
   adminstip: 'Одна назва користувача на рядок',
   settings: 'Налаштування',

   all: 'Усі теми', // or alternatively: All
   anon_1: 'анонім',    // singular
   anon: 'аноніми',      // plural

   badforum: 'Invalid forum',
   c_acc1: 'Your account now works on all sites using Moot',
   c_acc: 'Account confirmed',
   c_email: 'Email address updated',
   cancel: 'Cancel',
   change: 'Change',
   changepw: 'Change password',
   close: 'Close',
   collapse: 'Collapse all',
   comm_count_1: 'comment',   // singular: "1 comment"
   comm_count_n: 'comments',  // plural: "3 comments"
   comment1: 'Be the first to comment...',
   comment: 'Comment...',
   edit: 'edit',
   email: 'Email',
   email_taken: 'Така електронна адреса вже використовується',
   emailtip: 'Вашу електронну адресу нікому не буде розкрито',
   enter: 'ctrl + enter',
   expired1: 'We just sent you a new one. Please check your email.', // http://d.pr/i/1OEV
   expired: 'This link has expired',

   feed: 'My feed', // alternatives: My own, personal

   forumname: 'Forum name',
   forums: 'Forums',

   help2: 'post',
   help3: 'quoted',
   help5: 'code, language guessed',
   help6: 'HTML code',
   in_forum: 'in',
   invalid: 'Invalid value',
   join: 'Join Moot',
   later: 'Later...',
   less: 'less',
   like: 'Like',
   likepost: 'Like this post',
   loading: 'Loading...',
   login: 'Log in',
   login1: 'Log in first',
   login_and: "Login and",

   logout: 'Log out',
   mark: 'Offensive or spam',
   mean: 'Did you mean',
   name: 'Display name',
   nametip: 'Your real name, so people will recognize you',
   newcat: 'New category',
   newpass: 'New password',
   noresults: 'No results for',
   nospam: 'No spam on your forum!',
   notexist: 'does not exist.',
   notify: 'Notify me of new releases',
   ok: 'ok',
   online: 'Online',
   post: 'Post',
   preview: 'Preview',
   progress: ['loading...', 'still working...', 'and working...', 'giving up'],
   reconnect: 'Reconnecting...',
   removecat: 'Remove. The posts are not removed',
   removepost: 'Remove',
   reply: 'Reply...',
   replybtn: 'Reply',
   save: 'Save changes',
   saved: 'saved',
   search: 'Пошук',
   select: 'Оберіть розділ на форумі',
   setup: 'Setup now',
   showing: 'Showing',
   slogan: 'Forums and commenting re-imagined',
   spam: 'Spam',
   step1: 'We have sent you a confirmation email. Your email is not updated before you complete this step!',
   step: 'One more step',
   terms: 'I agree to the <a>terms of service</a>.',
   thanks: 'Thanks!',
   uname_len: 'Type 6 characters or more',
   uname_taken: 'This username is taken!',
   unametip: 'This cannot be changed later',
   undo: 'Undo',
   unlike: 'Unlike',
   unspam: 'Not spam',
   unver1: 'Unverified account',
   unver2: 'Please check your email to verify your account. Verified users can watch moots and receive email notifications. <a>Send a new verification code...</a>',
   unver3: '<a>Send a new</a> verification code to:',
   unver4: "Sent. Please check your inbox.",
   unver: 'Unverified',
   unwall: 'unwatch all',
   unwatch: 'Unwatch',
   upgrade2: 'Moot uses WebSockets or CORS for cross domain communication. All modern browsers above Opera 11 and IE7 work.',
   upgrade: 'Please upgrade your browser',
   username_taken: 'This username is taken',
   watch: 'Watch for new replies',
   welcome1: 'Please check your email to complete the registration. If you dont receive email within a minute or two, check your spam folder.',
   welcome2: 'Please provide a Moot username',
   welcome: 'Ласкаво просимо на Moot!',
   you: 'Ви',

   // times
   now: 'прямо зараз',
   months: "січ,лют,бер,кві,тра,чер,лип,сер,вер,жов,лис,гру",
   min: 'хв',
   hour: 'г',
   day: 'дн',
   week: 'тж'

}
