moot.language = {

  // the language code
  $code: 'zh',

  /* New stuff */
  is_private: "This community is private",
  owner_msg: "Your message to the forum owner... (Optional)",
  req_access: "Request access",
  req_sent: "Access request sent",
  or_join: "or <a>Join</a> to access the community.",
  save_with: "Save 20% with yearly billing",
  rem_post: "Remove this post?",
  is_spam: "This post is spam?",

  channels: '频道',
  ch_name:  '频道名称',
  mods:     '仲裁人', // 版主不确切
  ban:      '禁止该用户发言',
  banned:   '已被禁言',
  ban_usr:  '被禁用户',
  ban_acc:  '该账户已被禁言',
  ban_msg:  '你暂时被禁止在该论坛发言',
  days:     '天',
  forever:  '永久',
  slogan:   'Muut 免费论坛与评论',

  add: '+ 添加',
  addons: '附加组件',
  myaccount: "我的账户",
  untitled: "无题",
  design: "设计",
  img_needed: "请上传图像类文件",
  no_title: "标题必填",
  designer: "深度设计",
  developer: "高级开发",
  max: '图片大小上限为 4 MB',
  yes: '好的',
  upload: '上传图片',
  show: '显示',
  hide: '隐藏',
  invisible: '隐形',
  givebody: '正文不得空白',
  show_old: '显示最早回复',
  show_more: '显示更多回复',
  show_new: '显示最新回复',
  start: '开启新话题……',
  single: '用于单个词语',
  bold: '粗体',
  italics: '斜体',
  monospaced: '等宽体',
  learn: '进一步了解……',
  settings: '设置',
  error: '出故障了……请备份当前帖子内容，然后刷新页面，再试一次。很抱歉，我们会解决这个问题！',
  body: '正文',
  admin: '管理员',
  someone: '某人',
  writing: '正在写……',
  basic: '基本（免费）',
  subs: '服务',
  manage: '管理',
  fullview: '进入全文',
  title: '标题',
  link: 'URL',
  avatar: '更改头像',
  upgrade_link: '升级',
  branding: '品牌定制',
  logo: '标志',
  css: 'CSS 文件',
  /* End new stuff */


  username_fail: '请使用小写字母、数字或破折号（减号）',
  all: '所有话题', // or alternatively: All
  anon_1: '个匿名用户', // singular
  anon: '个匿名用户', // plural
  badforum: '无效论坛',
  c_acc1: '现在您的账户可以在所有嵌入 Muut 的网站上通行了',
  c_acc: '账户已确认',
  c_email: '邮箱地址已更新',
  cancel: '取消',
  change: '更改',

  changepw: '更改密码',
  close: '关闭',
  collapse: '全部缩拢',
  comm_count_1: '篇评论', // singular: "1 comment"
  comm_count_n: '篇评论', // plural: "3 comments"
  comment1: '率先评论……',
  comment: '评论……',
  edit: '编辑',
  email: '邮箱',
  email_taken: '邮箱已被注册使用',
  emailtip: '您的邮箱地址决不会被泄露给第三方',
  enter: 'Ctrl + Enter',
  expired1: '我们发出了新链接，请查收',
  expired: '链接已过期',

  feed: '关注中', // same as watching/following


  help2: '发表',
  help3: '引用内容',
  help5: '代码（自动语言识别）',
  help6: 'HTML 代码',
  in_forum: '发表于',
  invalid: '无效值',
  join: '加入 Muut',
  later: '稍后……',
  less: '收起',
  like: '喜欢',
  likepost: '喜欢这个帖子',
  loading: '加载中……',
  login: '登录',
  login1: '请先登录',
  login_and: "登录再", // Login and post

  logout: '注销',
  mark: '冒犯、低俗的语言，或垃圾信息',
  mean: '您是指',
  name: '显示名',
  nametip: '建议用真名，好让朋友们认出你',
  newpass: '新密码',
  noresults: '找不到',
  nospam: '您的论坛没有垃圾！',
  notexist: '不存在',
  notify: '发布新版本时通知我',
  ok: 'OK',
  online: '在线',
  post: '发表',
  preview: '预览',
  progress: ['加载中……', '仍在努力……', '继续努力……', '放弃'],
  reconnect: '重新连接中……',
  removepost: '删除',
  reply: '回复……',
  replybtn: '回复',
  save: '保存',
  saved: '已保存',
  search: '搜索',
  select: '选择频道',
  setup: '马上创建论坛',
  showing: '当前搜索', // Showing search results (instead) for
  spam: '垃圾',
  step1: '我们已发出一封确认信，收到后您须按指示完成这一步才能更新您的邮箱地址',
  step: '还有一步',
  terms: '我同意<a>服务条款</a>',
  thanks: '谢谢！',
  uname_len: '请输入至少 6 个字符',
  uname_taken: '用户名已被注册使用',
  unametip: '提交以后用户名无法更改',
  undo: '撤销',
  unlike: '取消喜欢',
  unspam: '并非垃圾',
  unver1: '未验证账户',
  unver2: '请按邮件指示验证您的账户！经验证用户能够关注论坛话题并接收更新通知。<a>发送新验证码……</a>',
  unver3: '<a>发送</a>新验证码到：',
  unver4: "已发送，请查收",
  unver: '未验证',
  unwall: '取消所有关注',
  unwatch: '取消关注',
  upgrade2: 'Muut 跨域通讯运用 WebSockets 以及 CORS 技术，目前 Opera 11 和 IE 7 以上版本，以及所有其他新式浏览器均能胜任',
  upgrade: '请升级您的浏览器',
  username_taken: '用户名已被注册使用',
  watch: '关注最新回复',
  welcome1: '请按邮件指示完成注册！如果几分钟内没有收到，请检查您的垃圾邮件',
  welcome2: '请选定您的 Muut 用户名',
  welcome: '欢迎来到 Muut！',
  you: '您',

  // times
  now: '刚刚',
  months: '1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月',
  min: '分钟前',
  hour: '小时前',
  day: '天前',
  week: '周前'

}

